Repository thin-edge/thin-edge.io, pull requests merged in 2022-02, with the labels that each got.

#914 #911 systemd init and connection reset fix
  configuration/debian/tedge_agent/postinst
  configuration/init/systemd/tedge-agent.service
  crates/core/c8y_api/src/http_proxy.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
  plugins/log_request_plugin/src/main.rs
Labels: bug, WIP

#899 #814 --config-dir option for tedge commands
  crates/common/tedge_config/src/tedge_config.rs
  crates/common/tedge_config/src/tedge_config_location.rs
  crates/common/tedge_utils/src/paths.rs
  crates/core/tedge/src/cli/mod.rs
  crates/core/tedge/src/main.rs
  crates/core/tedge/tests/main.rs
  crates/core/tedge_agent/src/agent.rs
  crates/core/tedge_agent/src/main.rs
  crates/core/tedge_mapper/src/core/error.rs
  crates/core/tedge_mapper/src/main.rs
Labels: feature, WIP

#920 Fix: We only need one approval right now
  CONTRIBUTING.md
Labels: documentation
