Repository thin-edge/thin-edge.io, pull requests merged in 2022-03, with the labels that each got.

#930 #912 feature gate for apt install test
  .github/workflows/integration-test-workflow.yml
  plugins/tedge_apt_plugin/Cargo.toml
  plugins/tedge_apt_plugin/tests/main.rs
Labels: improvement, WIP

#921 GitHub templates comments
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/doc_improvement.md
  .github/ISSUE_TEMPLATE/feature_improvement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: documentation, improvement, idea

#922 Add note about fixup commits
  CONTRIBUTING.md
Labels: documentation, idea

#978 (misc) Remove warnings
  crates/common/tedge_config/src/models/ipaddress.rs
  crates/core/c8y_smartrest/src/operations.rs
  crates/core/plugin_sm/tests/plugin.rs
Labels: improvement

#939 #858 configurable run/log path
  crates/common/flockfile/src/unix.rs
  crates/common/tedge_config/src/models/file_path.rs
  crates/common/tedge_config/src/settings.rs
  crates/common/tedge_config/src/tedge_config.rs
  crates/common/tedge_config/src/tedge_config_defaults.rs
  crates/common/tedge_config/src/tedge_config_dto.rs
  crates/common/tedge_config/tests/test_tedge_config.rs
  crates/core/tedge/src/cli/config/config_key.rs
  crates/core/tedge_agent/src/agent.rs
  crates/core/tedge_agent/src/restart_operation_handler.rs
  crates/core/tedge_mapper/src/main.rs
Labels: WIP

#985 #984 Error: Couldn't acquire file lock.
  crates/common/flockfile/src/unix.rs
  crates/common/tedge_config/src/tedge_config.rs
  crates/core/tedge_agent/src/restart_operation_handler.rs
Labels: bug

#971 #882 agent start up failures
  crates/core/c8y_smartrest/src/error.rs
  crates/core/c8y_smartrest/src/operations.rs
  crates/core/plugin_sm/src/plugin_manager.rs
  crates/core/tedge_agent/src/agent.rs
  crates/core/tedge_agent/src/state.rs
Labels: bug
