Repository thin-edge/thin-edge.io, pull requests merged in 2022-12, with the labels that each got.

#1635 support auto git semver versioning of packages
  .github/workflows/build-workflow.yml
  .github/workflows/ci_pipeline.yml
  ci/build_scripts/build.sh
  crates/core/tedge/build.rs
  crates/core/tedge_agent/build.rs
  crates/core/tedge_mapper/build.rs
  crates/core/tedge_watchdog/build.rs
  plugins/c8y_configuration_plugin/build.rs
  plugins/c8y_log_plugin/build.rs
  plugins/tedge_apama_plugin/build.rs
  plugins/tedge_apt_plugin/build.rs
  plugins/tedge_dummy_plugin/build.rs
Labels: ci/cd, theme:packaging

#1628 remove $ prefix in shells
  CODING_GUIDELINES.md
  ci/az_upload_device_cert.py
  ci/roundtrip_local_to_az.py
  docs/src/BUILDING.md
  docs/src/architecture/mapper.md
  docs/src/howto-guides/003_registration.md
  docs/src/howto-guides/004_connect.md
  docs/src/howto-guides/010_add_self_signed_trusted.md
  docs/src/howto-guides/011_retrieve_jwt_token_from_cumulocity.md
  docs/src/howto-guides/024_smartrest_templates.md
  docs/src/references/c8y-configuration-management.md
  docs/src/references/c8y-log-management.md
  docs/src/references/plugin-api.md
  docs/src/references/thin-edge-config-files.md
  docs/src/tutorials/connect-azure.md
  docs/src/tutorials/connect-c8y.md
  docs/src/tutorials/device-monitoring.md
  docs/src/tutorials/getting-started.md
  docs/src/tutorials/send-events.md
  docs/src/tutorials/send-thin-edge-data.md
  docs/src/tutorials/supported_operations.md
  docs/src/tutorials/write-my-software-management-plugin.md
  tests/PySys/software_management_end_to_end/dummy_plugin_configuration/Info.md
Labels: documentation

#1226 Create vision.md
  vision.md
Labels: discovery

#1654 Add output to `tedge cert create` and `tedge cert remove` commands
  crates/core/tedge/src/cli/certificate/create.rs
  crates/core/tedge/src/cli/certificate/remove.rs
  docs/src/howto-guides/003_registration.md
  docs/src/references/thin-edge-config-files.md
  docs/src/tutorials/connect-azure.md
  docs/src/tutorials/connect-c8y.md
Labels: improvement, theme:cli

#1651 publish debian packages to jfrog for development purposes
  .github/workflows/build-workflow.yml
  .gitignore
  ci/build_scripts/build.sh
  ci/build_scripts/publish_debian.sh
Labels: ci/cd, theme:packaging

#1653 Improve formatting in RobotFramework README
  tests/RobotFramework/README.md
Labels: documentation

#1666 Sort dependencies
  .github/workflows/pull-request-checks.yml
  crates/common/batcher/Cargo.toml
  crates/common/certificate/Cargo.toml
  crates/common/logged_command/Cargo.toml
  crates/common/mqtt_channel/Cargo.toml
  crates/common/tedge_config/Cargo.toml
  crates/common/tedge_utils/Cargo.toml
  crates/core/plugin_sm/Cargo.toml
  crates/core/tedge/Cargo.toml
  crates/core/tedge_agent/Cargo.toml
  crates/core/tedge_api/Cargo.toml
  crates/core/tedge_mapper/Cargo.toml
  crates/core/tedge_watchdog/Cargo.toml
  crates/tests/mqtt_tests/Cargo.toml
  crates/tests/sawtooth_publisher/Cargo.toml
  crates/tests/tedge_test_utils/Cargo.toml
  plugins/c8y_log_plugin/Cargo.toml
  plugins/tedge_apt_plugin/Cargo.toml
Labels: dependencies
