Repository thin-edge/thin-edge.io, pull requests merged in 2023-06, with the labels that each got.

#1999 ci: remove usage of actions-rs/toolchain@v1 as it is not actively maintained
  .github/workflows/pull-request-checks.yml
Labels: ci/cd

#1997 CI improvements
  .github/workflows/pull-request-checks.yml
  crates/core/plugin_sm/tests/plugin.rs
  crates/core/plugin_sm/tests/plugin_manager.rs
Labels: ci/cd

#2009 fix(ci): use official github hosted runner names
  .github/workflows/build-workflow.yml
  .github/workflows/ci_pipeline.yml
  .github/workflows/pull-request-checks.yml
Labels: ci/cd

#2016 docker/docker-compose images are always pruned
  docs/src/tutorials/write-my-software-management-plugin.md
  plugins/tedge_docker-compose_plugin/docker-compose
  plugins/tedge_docker_plugin/tedge_docker_plugin.sh
Labels: refactoring, theme:plugins

#2022 fix(ci): remove erroneous prefix before run commands
  .github/workflows/gh-pages.yml
Labels: bug, ci/cd

#2025 Add workflow to upload coverage report on pushes to main
  .github/codecov.yml
  .github/workflows/head_coverage.yml
Labels: github_actions
