Repository thin-edge/thin-edge.io, pull requests merged in 2023-03, with the labels that each got.

#1780 use relative svg link to prevent CORB error
  docs/src/tutorials/child-device-config-management.md
Labels: documentation

#1781 remove duplicate container networks before tests
  tests/RobotFramework/tasks.py
Labels: bug, ci/cd, theme:testing

#1788 All service statuses are set to down and remain down after restarting mosquitto
  crates/common/mqtt_channel/src/config.rs
  crates/common/mqtt_channel/src/connection.rs
  crates/core/c8y_api/src/smartrest/monitor.rs
  crates/core/tedge_agent/src/agent.rs
  crates/core/tedge_api/src/health.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
  crates/core/tedge_mapper/src/collectd/monitor.rs
  crates/core/tedge_mapper/src/core/mapper.rs
  crates/core/tedge_watchdog/src/systemd_watchdog.rs
  crates/extensions/c8y_config_manager/src/actor.rs
  crates/extensions/c8y_log_manager/src/actor.rs
  plugins/c8y_configuration_plugin/src/config_manager.rs
  plugins/c8y_firmware_plugin/src/firmware_manager.rs
  plugins/c8y_log_plugin/src/main.rs
  tests/RobotFramework/requirements/requirements.adapter-docker.txt
  tests/RobotFramework/requirements/requirements.adapter-local.txt
  tests/RobotFramework/requirements/requirements.adapter-ssh.txt
  tests/RobotFramework/requirements/requirements.txt
  tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
Labels: theme:mqtt, theme:monitoring

#1800 Fix the dependency of c8y-firmware-plugin and add test
  plugins/c8y_firmware_plugin/Cargo.toml
  tests/RobotFramework/tasks.py
  tests/RobotFramework/tests/installation/install_apt.robot
  tests/images/debian-systemd/files/bootstrap.sh
Labels: theme:firmware, theme:testing

#1796 update yocto documentation
  docs/src/tutorials/yocto-linux.md
Labels: documentation

#1813 build linux/musl target by default for host arch
  ci/build_scripts/build.sh
Labels: theme:developer-exp

#1798 tedge command for updating the service type
  crates/common/tedge_config/src/tedge_config_cli/settings.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config_defaults.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config_dto.rs
  crates/common/tedge_config/tests/test_tedge_config.rs
  crates/core/tedge/src/cli/config/config_key.rs
  crates/core/tedge_mapper/src/c8y/converter.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
  crates/core/tedge_mapper/src/c8y/service_monitor.rs
  crates/core/tedge_mapper/src/c8y/tests.rs
  docs/src/howto-guides/028_c8y_service_monitoring.md
  tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
Labels: theme:monitoring

#1821 fix duplicate child device serial number bug in test
  tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
Labels: theme:monitoring, theme:testing

#1866 fix: always remove/purge if package exists
  uninstall-thin-edge_io.sh
Labels: theme:installation
