Repository thin-edge/thin-edge.io, pull requests merged in 2023-11, with the labels that each got.

#2381 Add requester prefix with timestamp to command operations
  Cargo.lock
  crates/core/c8y_api/src/smartrest/smartrest_deserializer.rs
  crates/core/tedge_agent/src/software_manager/actor.rs
  crates/core/tedge_agent/src/software_manager/tests.rs
  crates/core/tedge_agent/src/tedge_operation_converter/tests.rs
  crates/core/tedge_api/Cargo.toml
  crates/core/tedge_api/src/lib.rs
  crates/core/tedge_api/src/messages.rs
  crates/core/tedge_api/src/mqtt_topics.rs
  crates/core/tedge_watchdog/Cargo.toml
  crates/extensions/c8y_mapper_ext/Cargo.toml
  crates/extensions/c8y_mapper_ext/src/compatibility_adapter.rs
  crates/extensions/c8y_mapper_ext/src/config_operations.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/log_upload.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
  tests/RobotFramework/tests/cumulocity/log/log_operation.robot
  tests/RobotFramework/tests/cumulocity/restart/restart_device.robot
  tests/RobotFramework/tests/cumulocity/software_management/software.robot
Labels: theme:mqtt

#2400 docs: fix typo in tedge-configuration-management
  docs/src/references/agent/tedge-configuration-management.md
Labels: documentation

#2402 tests: skip benchmarking tests by default
  .github/workflows/integration-tests.yml
  tests/RobotFramework/tasks.py
  tests/RobotFramework/tests/cumulocity/benchmarks/benchmarks.robot
Labels: ci/cd, theme:testing

#2406 tests: update tests after latest 0.13.0 release
  crates/common/download/examples/simple_download.rs
  crates/common/download/src/lib.rs
  tests/RobotFramework/README.md
  tests/RobotFramework/tasks/E2E_Tutorials/Connect_to_c8y.robot
  tests/RobotFramework/tests/installation/install_tedge.robot
  tests/RobotFramework/tests/tedge/call_tedge.robot
  tests/images/debian-systemd/files/bootstrap.sh
Labels: theme:installation, theme:testing

#2408 docs: enforce/normalize v1 format on all te2mqtt code blocks
  docs/src/contribute/design/mqtt-topic-design.md
  docs/src/contribute/writing-documentation/markdown-components.md
  docs/src/operate/c8y/child_device_config_management_agent.md
  docs/src/operate/c8y/retrieve_jwt_token_from_cumulocity.md
  docs/src/operate/configuration/child-device-config-management.md
  docs/src/operate/monitoring/enable_tedge_watchdog_using_systemd.md
  docs/src/operate/telemetry/pub_sub.md
  docs/src/operate/troubleshooting/monitor_tedge_health.md
  docs/src/operate/troubleshooting/trouble_shooting_monitoring.md
  docs/src/references/agent/device-management-api.md
  docs/src/references/agent/restart-operation.md
  docs/src/references/agent/software-management.md
  docs/src/references/agent/tedge-configuration-management.md
  docs/src/references/agent/tedge-log-management.md
  docs/src/references/mappers/c8y-mapper.md
  docs/src/references/mqtt-api.md
  docs/src/start/connect-aws.md
  docs/src/start/connect-azure.md
  docs/src/start/connect-c8y.md
  docs/src/start/device-monitoring.md
  docs/src/start/getting-started.md
  docs/src/start/raise-alarm.md
  docs/src/start/send-events.md
  docs/src/start/send-thin-edge-data.md
  docs/src/understand/tedge-mapper.md
  docs/src/understand/thin-edge-json.md
Labels: documentation

#2410 tests: include more readable mqtt logs in Get Logs keyword
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
Labels: theme:testing

#2415 tests: use stop/start over restart for service to improve flaky system test
  tests/RobotFramework/tests/configuration/lock_file.robot
Labels: theme:testing

#2425 tests: hide cumulocity iot token message from the test log output
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
Labels: theme:testing

#2431 docs: fix incorrect mqtt sub command
  docs/src/contribute/design/mqtt-topic-design.md
Labels: documentation

#2435 tedge-log-manager: wait for upload before marking operation successful
  crates/extensions/tedge_log_manager/src/actor.rs
Labels: theme:troubleshooting

#2439 custom operation option to disable quoting of results to enable c8y_RelayArray compatibility
  crates/core/c8y_api/src/smartrest/operations.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  docs/src/operate/c8y/supported_operations.md
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_c8y_RelayArray/c8y_RelayArray
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_c8y_RelayArray/operation_relay_array.robot
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_c8y_RelayArray/set_relay.sh
Labels: theme:c8y

#2470 Fix typos
  .typos.toml
  crates/common/tedge_utils/src/notify.rs
  docs/src/references/tedge-cumulocity-proxy.md
Labels: documentation

#2071 Operation Workflow Specification & Implementation
  Cargo.lock
  Cargo.toml
  crates/core/tedge_agent/Cargo.toml
  crates/core/tedge_agent/src/agent.rs
  crates/core/tedge_agent/src/restart_manager/actor.rs
  crates/core/tedge_agent/src/restart_manager/tests.rs
  crates/core/tedge_agent/src/software_manager/actor.rs
  crates/core/tedge_agent/src/software_manager/tests.rs
  crates/core/tedge_agent/src/tedge_operation_converter/actor.rs
  crates/core/tedge_agent/src/tedge_operation_converter/builder.rs
  crates/core/tedge_agent/src/tedge_operation_converter/tests.rs
  crates/core/tedge_api/src/lib.rs
  crates/core/tedge_api/src/messages.rs
  crates/core/tedge_api/src/mqtt_topics.rs
  crates/core/tedge_api/src/workflow.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/tedge_config_manager/src/actor.rs
  crates/extensions/tedge_log_manager/src/actor.rs
  docs/src/references/agent/device-management-api.md
  docs/src/references/agent/index.md
  docs/src/references/agent/operation-workflow.md
  docs/src/references/agent/tedge-configuration-management.md
  docs/src/references/agent/tedge-log-management.md
  tests/RobotFramework/tests/tedge_agent/workflows/check-download.sh
  tests/RobotFramework/tests/tedge_agent/workflows/custom-download.toml
  tests/RobotFramework/tests/tedge_agent/workflows/custom_operation.robot
  tests/RobotFramework/tests/tedge_agent/workflows/download-command-expected.log
  tests/RobotFramework/tests/tedge_agent/workflows/init-software-list.sh
  tests/RobotFramework/tests/tedge_agent/workflows/launch-download.sh
  tests/RobotFramework/tests/tedge_agent/workflows/schedule-download.sh
  tests/RobotFramework/tests/tedge_agent/workflows/software_list.toml
Labels: improvement, feature
