Repository thin-edge/thin-edge.io, pull requests merged in 2023-09, with the labels that each got.

#2212 fix: align tedge-log-plugin settings
  Cargo.lock
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  plugins/tedge_log_plugin/src/main.rs
Labels: theme:troubleshooting

#2230 docs(health): fix header level to produce an anchor which can be referenced
  docs/src/operate/troubleshooting/monitor_tedge_health.md
Labels: documentation

#2229 docs(collectd): align installation instructions and avoid installing unnecessary packages
  docs/src/start/device-monitoring.md
  docs/src/start/getting-started.md
Labels: documentation, theme:monitoring

#2228 chore(tests): bump python requests lib due to security notification
  tests/requirements.txt
Labels: dependencies, theme:testing

#2227 chore(deps): update dependencies which required Rust 1.70
  Cargo.lock
  Cargo.toml
  crates/core/tedge/Cargo.toml
  crates/core/tedge/src/cli/config/commands/list.rs
Labels: refactoring, dependencies

#2240 build: limit cargo-zigbuild version due to bug in newly released version
  ci/build_scripts/build.sh
Labels: ci/cd

#2232 Add netcat, netstat, and ping to test image
  tests/images/debian-systemd/debian-systemd.dockerfile
Labels: theme:containers, theme:developer-exp, theme:testing

#2231 Add `mqtt.topic_root` and `mqtt.device_topic_id` options
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/tedge_agent/src/agent.rs
  crates/core/tedge_agent/src/main.rs
  crates/extensions/tedge_log_manager/src/config.rs
  crates/extensions/tedge_log_manager/src/tests.rs
  plugins/tedge_log_plugin/src/main.rs
  tests/RobotFramework/tests/tedge_agent/tedge_agent.robot
Labels: theme:mqtt, theme:cli

#2239 Fix device_id lookup while sending large events over HTTP #2234
  crates/core/tedge/src/cli/mqtt/mod.rs
  crates/core/tedge/src/cli/mqtt/publish.rs
  crates/core/tedge/src/cli/mqtt/subscribe.rs
  crates/extensions/c8y_http_proxy/src/actor.rs
  tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
Labels: theme:telemetry, theme:c8y

#2248 chore(build): update cargo-zigbuild version
  ci/build_scripts/build.sh
Labels: ci/cd

#2254 fix(build): update python version used to publish linux packages
  .github/workflows/build-workflow.yml
Labels: ci/cd

#2255 fix(build): remove c8y-log-plugin as the ci_pipeline uses the list to install all the packages
  ci/package_list.sh
Labels: ci/cd

#2252 remove trailing full stop in log entries as it is unnecessary
  crates/extensions/c8y_firmware_manager/src/actor.rs
  crates/extensions/tedge_log_manager/src/actor.rs
Labels: theme:developer-exp

#2141 chore(collectd): increase the default intervals to avoid spamming iot platforms
  configuration/contrib/collectd/collectd.conf
  docs/src/operate/troubleshooting/trouble_shooting_monitoring.md
  docs/src/start/device-monitoring.md
  tests/RobotFramework/tests/cumulocity/monitoring/monitor_device_collectd.robot
Labels: theme:monitoring

#2268 chore(build): switch from unmaintained users crate to fork to fix security warning
  Cargo.lock
  Cargo.toml
  crates/common/tedge_utils/Cargo.toml
  crates/common/tedge_utils/src/file.rs
Labels: ci/cd, theme:security

#2270 test: check registration of log file request capability
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
  tests/RobotFramework/tests/cumulocity/log/log_operation_child.robot
Labels: theme:troubleshooting, theme:testing

#2269 Change tedge mosquitto configuration file permissions to 644
  crates/common/tedge_utils/src/paths.rs
  crates/core/tedge/src/cli/connect/command.rs
Labels: theme:mqtt

#2278 feat(az): extend supported topics on Azure IoT Hub bridge
  crates/core/tedge/src/cli/connect/bridge_config.rs
  crates/core/tedge/src/cli/connect/bridge_config_azure.rs
Labels: improvement, theme:mqtt, theme:az

#2286 fix(packaging): use release suffix in version dependency to avoid version mismatches
  configuration/package_manifests/virtual/nfpm.tedge-full.yaml
  configuration/package_manifests/virtual/nfpm.tedge-minimal.yaml
Labels: bug, theme:packaging

#2277 Run remote access plugin with correct executable path in child process
  Cargo.lock
  plugins/c8y_remote_access_plugin/Cargo.toml
  plugins/c8y_remote_access_plugin/src/main.rs
Labels: theme:troubleshooting, theme:c8y

#2266 C8y mapping of entity registration messages
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/c8y_api/src/json_c8y.rs
  crates/core/c8y_api/src/smartrest/inventory.rs
  crates/core/c8y_api/src/smartrest/mod.rs
  crates/core/c8y_api/src/smartrest/topic.rs
  crates/core/tedge_api/src/entity_store.rs
  crates/core/tedge_api/src/event.rs
  crates/core/tedge_api/src/mqtt_topics.rs
  crates/extensions/c8y_mapper_ext/src/actor.rs
  crates/extensions/c8y_mapper_ext/src/config.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/error.rs
  crates/extensions/c8y_mapper_ext/src/log_upload.rs
  crates/extensions/c8y_mapper_ext/src/serializer.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  docs/src/contribute/design/mqtt-topic-design.md
  docs/src/references/mappers/c8y-mapper.md
  docs/src/references/mqtt-api.md
  tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device.robot
  tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device_retry.robot
  tests/RobotFramework/tests/cumulocity/log/log_operation_child.robot
  tests/RobotFramework/tests/cumulocity/registration/device_registration.robot
  tests/RobotFramework/tests/cumulocity/restart/restart_device_child.robot
  tests/RobotFramework/tests/cumulocity/telemetry/c8y_child_alarms_rpi.robot
  tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot
  tests/RobotFramework/tests/customizing/data_path_config.robot
  tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
Labels: theme:mqtt
