Repository thin-edge/thin-edge.io, pull requests merged in 2023-07, with the labels that each got.

#2054 feat: publish docusaurus docs to github pages
  .github/workflows/gh-pages.yml
Labels: documentation

#2057 docs: fix management typo in title
  docs/src/operate/installation/install_and_enable_software_management.md
Labels: documentation

#2056 docs: fix getting started step indentation
  docs/src/start/getting-started.md
Labels: documentation

#2058 Move out Install section
  docs/src/SUMMARY.md
  docs/src/install/index.md
  docs/src/operate/connection/connect.md
  docs/src/operate/index.md
  docs/src/operate/installation/install_and_enable_software_management.md
  docs/src/operate/installation/installation_without_deb_support.md
  docs/src/overview.md
  docs/src/start/connect-aws.md
  docs/src/start/connect-azure.md
  docs/src/start/connect-c8y.md
  docs/src/start/index.md
Labels: documentation

#2059 docs: refactor markdown guidelines to show components
  docs/src/contribute/writing-documentation/index.md
  docs/src/contribute/writing-documentation/markdown-components.md
  docs/src/contribute/writing-documentation/markdown-guidelines.md
Labels: documentation

#2060 Add DocCardList to all index pages
  docs/src/contribute/index.md
  docs/src/contribute/writing-documentation/index.md
  docs/src/extend/index.md
  docs/src/operate/c8y/index.md
  docs/src/operate/configuration/index.md
  docs/src/operate/connection/index.md
  docs/src/operate/index.md
  docs/src/operate/installation/index.md
  docs/src/operate/monitoring/index.md
  docs/src/operate/operations/index.md
  docs/src/operate/security/index.md
  docs/src/operate/telemetry/index.md
  docs/src/operate/troubleshooting/index.md
  docs/src/references/index.md
Labels: documentation

#2046 Improve documentation of the main concepts
  docs/src/SUMMARY.md
  docs/src/overview.md
  docs/src/references/data-model.md
  docs/src/references/domain-model.md
  docs/src/references/index.md
  docs/src/start/device-monitoring.md
  docs/src/understand/digital-twin.md
  docs/src/understand/faq.md
  docs/src/understand/images/typical-iot-agent-hardware.svg
  docs/src/understand/images/typical-iot-agent.svg
  docs/src/understand/index.md
  docs/src/understand/mqtt-bus.md
  docs/src/understand/overview.md
  docs/src/understand/software-management.md
  docs/src/understand/tedge-agent.md
  docs/src/understand/tedge-mapper.md
  docs/src/understand/thin-edge-json.md
  docs/src/understand/typical-iot-agent.md
Labels: documentation

#2062 Fix broken anchor links
  docs/src/start/getting-started.md
Labels: bug, documentation

#1988 Extra tools in dev-containers
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: theme:developer-exp

#2074 docs(fix): add missing commas to json examples
  docs/src/references/data-model.md
  docs/src/understand/thin-edge-json.md
Labels: documentation

#2084 docs(mqtt): fix invalid json in an example
  docs/src/references/mqtt-api.md
Labels: documentation

#2085 test(software): use local http server with rate limiting instead of external resource
  tests/RobotFramework/tests/cumulocity/software.robot
  tests/images/debian-systemd/debian-systemd.dockerfile
  tests/images/debian-systemd/files/http-server/nginx.conf
  tests/images/debian-systemd/files/http-server/start-http-server.sh
  tests/images/debian-systemd/files/http-server/stop-http-server.sh
Labels: ci/cd, theme:testing

#2095 Switch to latest rust-analyzer vscode plugin
  .devcontainer/devcontainer.json
Labels: theme:developer-exp

#2094 docs(mqtt-spec): minor corrections and additional context
  docs/src/references/mqtt-api.md
Labels: documentation, theme:mqtt

#2091 test(tasks): add clean option to flake finder task
  tests/RobotFramework/tasks.py
Labels: theme:developer-exp, theme:testing

#2104 docs: fix broken links in readme and install script
  README.md
  get-thin-edge_io.sh
Labels: documentation, theme:packaging

#2107 docs: fix broken doc references
  README.md
  docs/README.md
  docs/src/operate/c8y/apama_software_management_plugin.md
  docs/src/operate/configuration/child-device-config-management.md
  docs/src/start/getting-started.md
Labels: documentation

#2106 docs: add more markdown examples for te2mqtt and the proposal banner
  docs/src/contribute/writing-documentation/markdown-components.md
Labels: documentation

#2111 docs: use links to files instead of folders to avoid unnecessary redirects
  docs/src/start/getting-started.md
Labels: documentation

#2115 fix(config): removing escaped newline char shown in console message
  crates/common/tedge_config_macros/src/option.rs
Labels: theme:cli
