Repository thin-edge/thin-edge.io, pull requests merged in 2023-02, with the labels that each got.

#1694 Add Cumulocity remote access plugin
  Cargo.lock
  Cargo.toml
  ci/package_list.sh
  configuration/debian/c8y-remote-access-plugin/postinst
  configuration/debian/c8y-remote-access-plugin/prerm
  docs/src/SUMMARY.md
  docs/src/howto-guides/027_remote_access_with_cumulocity.md
  docs/src/howto-guides/howto-guides.md
  docs/src/howto-guides/images/c8y-remote-access_dm.png
  docs/src/howto-guides/images/c8y-remote-access_endpoint.png
  docs/src/howto-guides/images/c8y-remote-access_websocket.png
  get-thin-edge_io.sh
  plugins/c8y_remote_access_plugin/Cargo.toml
  plugins/c8y_remote_access_plugin/src/auth.rs
  plugins/c8y_remote_access_plugin/src/csv.rs
  plugins/c8y_remote_access_plugin/src/input.rs
  plugins/c8y_remote_access_plugin/src/main.rs
  plugins/c8y_remote_access_plugin/src/proxy.rs
  uninstall-thin-edge_io.sh
Labels: idea, theme:troubleshooting, theme:plugins

#1706 Fix remove remote access install
  Cargo.lock
  get-thin-edge_io.sh
Labels: bug, theme:packaging

#1704 Update the health status document
  docs/src/howto-guides/020_monitor_tedge_health.md
Labels: documentation

#1699 Support custom fragments in alarm creation
  Cargo.lock
  crates/core/c8y_api/Cargo.toml
  crates/core/c8y_api/src/json_c8y.rs
  crates/core/c8y_api/src/smartrest/alarm.rs
  crates/core/tedge_api/Cargo.toml
  crates/core/tedge_api/src/alarm.rs
  crates/core/tedge_mapper/src/c8y/alarm_converter.rs
  crates/core/tedge_mapper/src/c8y/converter.rs
  crates/core/tedge_mapper/src/c8y/tests.rs
Labels: improvement, theme:telemetry

#1683 tedge_mapper az/collectd services start running when the thin-edge device restarts
  crates/core/tedge_mapper/Cargo.toml
Labels: bug, theme:packaging

#1702 Doc: Update the supported operation file example
  docs/src/tutorials/supported_operations.md
Labels: documentation, theme:troubleshooting, theme:plugins

#1709 Refactor the download implementation of c8y-configuration-plugin
  Cargo.lock
  crates/common/download/examples/simple_download.rs
  crates/common/download/src/download.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config_defaults.rs
  crates/common/tedge_utils/src/file.rs
  crates/core/c8y_api/Cargo.toml
  crates/core/c8y_api/src/http_proxy.rs
  crates/core/c8y_api/src/smartrest/error.rs
  crates/core/plugin_sm/src/plugin.rs
  crates/core/tedge_mapper/src/c8y/tests.rs
  plugins/c8y_configuration_plugin/src/child_device.rs
  plugins/c8y_configuration_plugin/src/download.rs
  plugins/c8y_configuration_plugin/src/error.rs
  plugins/c8y_configuration_plugin/src/tests.rs
Labels: refactoring

#1712 Build/publish artifacts - musl, zigbuild and cloudsmith
  .github/workflows/build-workflow.yml
  ci/build_scripts/build.sh
  ci/build_scripts/publish_debian.sh
  docs/src/developer/DEBIAN_PACKAGE_HOSTING.md
Labels: improvement, ci/cd, theme:packaging

#1720 remove unnecessary build jobs from pull-request-checks workflow
  .github/workflows/pull-request-checks.yml
Labels: refactoring, ci/cd

#1722 Support posix shells in uninstall script
  docs/src/howto-guides/002_installation.md
  uninstall-thin-edge_io.sh
Labels: improvement, theme:packaging

#1715 tedge alarm does not transform message fragment to text in the tedge-mapper-c8y
  crates/core/c8y_api/src/smartrest/alarm.rs
  crates/core/tedge_api/src/alarm.rs
  crates/core/tedge_mapper/src/c8y/tests.rs
  docs/src/tutorials/raise-alarm.md
Labels: improvement, theme:telemetry

#1727 Software management plugin docs: fix grammer and api mistakes
  docs/src/references/plugin-api.md
  docs/src/tutorials/write-my-software-management-plugin.md
Labels: documentation, theme:software

#1730 Wait for mapper health message before starting software list assertion
  tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
  tests/RobotFramework/tests/cumulocity/software.robot
  tests/images/debian-systemd/files/mosquitto.conf
Labels: refactoring, theme:testing

#1736 Additional dev tools in devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: improvement, theme:developer-exp

#1719 Add c8y-firmware-plugin
  Cargo.lock
  Cargo.toml
  ci/package_list.sh
  configuration/debian/c8y-firmware-plugin/postinst
  configuration/debian/c8y-firmware-plugin/prerm
  configuration/init/systemd/c8y-firmware-plugin.service
  crates/common/tedge_config/src/tedge_config_cli/models/mod.rs
  crates/common/tedge_config/src/tedge_config_cli/models/seconds.rs
  crates/common/tedge_config/src/tedge_config_cli/settings.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config_defaults.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config_dto.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config_repository.rs
  crates/common/tedge_config/tests/test_tedge_config.rs
  crates/common/tedge_utils/src/file.rs
  crates/common/tedge_utils/src/timers.rs
  crates/core/c8y_api/src/smartrest/smartrest_deserializer.rs
  crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
  crates/core/tedge/src/cli/config/config_key.rs
  plugins/c8y_firmware_plugin/Cargo.toml
  plugins/c8y_firmware_plugin/build.rs
  plugins/c8y_firmware_plugin/src/error.rs
  plugins/c8y_firmware_plugin/src/firmware_manager.rs
  plugins/c8y_firmware_plugin/src/main.rs
  plugins/c8y_firmware_plugin/src/message.rs
  plugins/c8y_firmware_plugin/src/tests.rs
Labels: feature, theme:firmware
