Repository thin-edge/thin-edge.io, pull requests merged in 2023-12, with the labels that each got.

#2513 feat(packaging) publish container image to ghcr
  .github/workflows/build-workflow.yml
  .gitignore
  ci/build_scripts/version.sh
  containers/tedge/Dockerfile
  containers/tedge/system.toml
  justfile
Labels: theme:containers, theme:packaging

#2516 feat: run initializations before starting main process
  configuration/init/systemd/c8y-firmware-plugin.service
  configuration/init/systemd/tedge-agent.service
  configuration/init/systemd/tedge-mapper-aws.service
  configuration/init/systemd/tedge-mapper-az.service
  configuration/init/systemd/tedge-mapper-c8y.service
  configuration/init/systemd/tedge-mapper-collectd.service
  configuration/init/systemd/tedge-watchdog.service
  tests/RobotFramework/tests/customizing/data_path_config.robot
  tests/RobotFramework/tests/customizing/log_path_config.robot
Labels: theme:packaging, theme:monitoring

#2519 feat: improve container default settings
  containers/tedge/Dockerfile
Labels: theme:containers

#2530 Make more robust a test detecting restart
  tests/RobotFramework/tests/tedge_agent/workflows/custom_operation.robot
Labels: theme:testing

#2529 adjust the expected return code when user is missing "Tenant manager" admin rights
  docs/src/start/c8y-user-globl-roles.png
  docs/src/start/connect-c8y.md
Labels: documentation

#2518 tedge-apt-plugin: support settings to control if configuration files are kept or replaced when included in a debian package
  crates/common/tedge_config/src/tedge_config_cli/models/apt_config.rs
  crates/common/tedge_config/src/tedge_config_cli/models/mod.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  plugins/tedge_apt_plugin/src/lib.rs
  tests/RobotFramework/tests/plugin_apt/build.sh
  tests/RobotFramework/tests/plugin_apt/install_overwrite_config_files.robot
  tests/RobotFramework/tests/plugin_apt/nfpm-version1.yaml
  tests/RobotFramework/tests/plugin_apt/nfpm-version2.yaml
  tests/RobotFramework/tests/plugin_apt/sampledeb_1.0.0_all.deb
  tests/RobotFramework/tests/plugin_apt/sampledeb_1.cfg
  tests/RobotFramework/tests/plugin_apt/sampledeb_2.0.0_all.deb
  tests/RobotFramework/tests/plugin_apt/sampledeb_2.cfg
Labels: theme:software

#2540 Fix flaky entity store persistence test
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
  tests/RobotFramework/tests/cumulocity/registration/device_registration.robot
Labels: theme:testing

#2543 build: support a release candidate version
  ci/build_scripts/version.sh
Labels: ci/cd

#2535 docs: Add documentation on how to build images
  docs/src/extend/firmware-management/building-image/index.md
  docs/src/extend/firmware-management/building-image/rugpi/index.md
  docs/src/extend/firmware-management/building-image/rugpi/tutorial.md
  docs/src/extend/firmware-management/building-image/yocto/index.md
  docs/src/extend/firmware-management/building-image/yocto/tutorial.md
  docs/src/extend/firmware-management/device-onboarding.md
  docs/src/extend/firmware-management/flashing-an-image.md
  docs/src/extend/firmware-management/images/raspberrypi-imager-open.png
  docs/src/extend/firmware-management/images/raspberrypi-imager-select-image.png
  docs/src/extend/firmware-management/images/raspberrypi-imager-select-storage.png
  docs/src/extend/firmware-management/images/raspberrypi-imager-selected-file.png
  docs/src/extend/firmware-management/images/raspberrypi-imager-write-completed.png
  docs/src/extend/firmware-management/images/raspberrypi-imager-writing.png
  docs/src/extend/firmware-management/index.md
  docs/src/extend/yocto-linux.md
Labels: documentation

#2547 Restart the device after a self-update
  tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
Labels: theme:testing

#2554 docs: remove tedge-log-plugin and tedge-configuration-plugin references
  docs/src/contribute/DEBIAN_PACKAGE_HOSTING.md
  docs/src/operate/c8y/config_management_plugin.md
  docs/src/operate/c8y/tedge_log_management.md
  docs/src/operate/configuration/update_config_paths.md
  docs/src/references/domain-model.md
  docs/src/start/getting-started.md
  docs/src/understand/tedge-agent.md
Labels: documentation
