Repository thin-edge/thin-edge.io, pull requests merged in 2023-08, with the labels that each got.

#2116 fix(tedge-apt-plugin): remove symlink using rm -f instead of using conditional logic
  configuration/debian/tedge-apt-plugin/postrm
Labels: bug

#2120 fix(c8y-remote-access-plugin): use auto versioning to align with other components
  plugins/c8y_remote_access_plugin/build.rs
Labels: bug, theme:troubleshooting, theme:c8y

#2124 refactor(uninstall): explicitly remove all packages to avoid problems when dependencies are changed
  tests/RobotFramework/tests/installation/install_tedge.robot
  uninstall-thin-edge_io.sh
Labels: improvement, theme:installation

#2126 tests(lock): improve pid detection logic by using more precise matches
  tests/RobotFramework/tests/MQTT_health_check/MQTT_health_endpoints.robot
  tests/RobotFramework/tests/MQTT_health_check/health_c8y-configuration-plugin.robot
  tests/RobotFramework/tests/MQTT_health_check/health_c8y-log-plugin.robot
  tests/RobotFramework/tests/MQTT_health_check/health_tedge-agent.robot
  tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-az.robot
  tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-collectd.robot
  tests/RobotFramework/tests/MQTT_health_check/health_tedge_mapper_c8y.robot
  tests/RobotFramework/tests/configuration/lock_file.robot
Labels: theme:testing

#2128 fix(build): use fixed ziglang 0.10.1 due to build issue with 0.11.0
  ci/build_scripts/build.sh
Labels: bug, ci/cd

#2123 fix(install): improve maintainer script compatibility in preparation for future package support
  configuration/debian/tedge-agent/postrm
  configuration/debian/tedge-mapper/postinst
  configuration/debian/tedge-mapper/postrm
  configuration/debian/tedge/postinst
  configuration/debian/tedge/postrm
  configuration/debian/tedge/preinst
Labels: bug, refactoring, theme:packaging

#2129 fix(install): improve reliability of latest version detection by using non rate limited api
  get-thin-edge_io.sh
Labels: bug, theme:installation

#2133 chore: add maintainer scripts from existing debian packages for later comparison
  configuration/package_scripts/_generated/c8y-firmware-plugin/deb/postinst
  configuration/package_scripts/_generated/c8y-firmware-plugin/deb/postrm
  configuration/package_scripts/_generated/c8y-firmware-plugin/deb/prerm
  configuration/package_scripts/_generated/c8y-log-plugin/deb/postinst
  configuration/package_scripts/_generated/c8y-log-plugin/deb/postrm
  configuration/package_scripts/_generated/c8y-log-plugin/deb/prerm
  configuration/package_scripts/_generated/c8y-remote-access-plugin/deb/postinst
  configuration/package_scripts/_generated/c8y-remote-access-plugin/deb/prerm
  configuration/package_scripts/_generated/tedge-agent/deb/postinst
  configuration/package_scripts/_generated/tedge-agent/deb/postrm
  configuration/package_scripts/_generated/tedge-agent/deb/prerm
  configuration/package_scripts/_generated/tedge-apt-plugin/deb/postinst
  configuration/package_scripts/_generated/tedge-apt-plugin/deb/postrm
  configuration/package_scripts/_generated/tedge-mapper/deb/postinst
  configuration/package_scripts/_generated/tedge-mapper/deb/postrm
  configuration/package_scripts/_generated/tedge-mapper/deb/prerm
  configuration/package_scripts/_generated/tedge-watchdog/deb/postinst
  configuration/package_scripts/_generated/tedge-watchdog/deb/postrm
  configuration/package_scripts/_generated/tedge-watchdog/deb/prerm
  configuration/package_scripts/_generated/tedge/deb/postinst
  configuration/package_scripts/_generated/tedge/deb/postrm
  configuration/package_scripts/_generated/tedge/deb/preinst
Labels: refactoring, theme:packaging

#2134 test(ci): reduce PR test report output by hiding passed tests
  .github/workflows/integration-tests.yml
Labels: improvement, ci/cd, theme:testing

#2135 chore: add c8y-configuration-plugin maintainer scripts in preparation for new packaging
  configuration/package_scripts/_generated/c8y-configuration-plugin/deb/postinst
  configuration/package_scripts/_generated/c8y-configuration-plugin/deb/postrm
  configuration/package_scripts/_generated/c8y-configuration-plugin/deb/prerm
Labels: refactoring, theme:packaging

#2148 docs(install): update installation guide to detail installing thin-edge.io on any distribution
  docs/src/install/index.md
  docs/src/operate/c8y/config_management_plugin.md
  docs/src/operate/installation/installation_without_deb_support.md
  docs/src/start/getting-started.md
Labels: documentation, theme:packaging, theme:installation

#2155 docs(install): update init system instructions
  docs/src/install/index.md
  docs/src/operate/configuration/how_to_use_preferred_init_system.md
  docs/src/operate/installation/how_to_install_thin_edge_manually.md
  docs/src/operate/installation/init_systems.md
  docs/src/references/init-system-config.md
  docs/src/references/supported-platforms.md
  docs/src/start/getting-started.md
Labels: documentation, theme:installation

#2157 dev(checks): use zigbuild to run just check task if it is available
  justfile
Labels: theme:developer-exp

#2156 feat(cli): use tedge instead of mosquitto as owner of mosquitto files/folders
  crates/core/tedge/src/cli/init.rs
  tests/RobotFramework/tests/customizing/tedge_init.robot
Labels: theme:installation, theme:cli

#2165 build: update cargo-zigbuild to support ziglang 0.11.0
  ci/build_scripts/build.sh
Labels: ci/cd, theme:packaging

#2163 fix(tests): use more portable bash shebang to prevent units test from failing
  ci/ci_smoke_test_az.sh
  ci/ci_smoke_test_c8y.sh
  crates/extensions/c8y_mapper_ext/src/tests.rs
Labels: theme:cli, theme:testing

#2171 Use MQTT clean session for the mosquitto c8y bridge connection
  crates/core/tedge/src/cli/connect/bridge_config.rs
  crates/core/tedge/src/cli/connect/bridge_config_aws.rs
  crates/core/tedge/src/cli/connect/bridge_config_azure.rs
  crates/core/tedge/src/cli/connect/bridge_config_c8y.rs
Labels: theme:mqtt, theme:c8y, theme:cli

#2173 Avoid subscribing to s/dcr and forwarding s/ucr
  crates/core/tedge/src/cli/connect/bridge_config_c8y.rs
  docs/src/references/mqtt-topics.md
Labels: theme:mqtt, theme:c8y, theme:cli

#2188 packaging: align version schema used in packaging
  ci/build_scripts/build.sh
  ci/build_scripts/package.sh
  ci/build_scripts/version.sh
  configuration/package_manifests/nfpm.c8y-configuration-plugin.yaml
  configuration/package_manifests/nfpm.c8y-firmware-plugin.yaml
  configuration/package_manifests/nfpm.c8y-log-plugin.yaml
  configuration/package_manifests/nfpm.c8y-remote-access-plugin.yaml
  configuration/package_manifests/nfpm.sawtooth-publisher.yaml
  configuration/package_manifests/nfpm.tedge-agent.yaml
  configuration/package_manifests/nfpm.tedge-apt-plugin.yaml
  configuration/package_manifests/nfpm.tedge-dummy-plugin.yaml
  configuration/package_manifests/nfpm.tedge-mapper.yaml
  configuration/package_manifests/nfpm.tedge-watchdog.yaml
  configuration/package_manifests/nfpm.tedge.yaml
  configuration/package_manifests/virtual/nfpm.tedge-full.yaml
  configuration/package_manifests/virtual/nfpm.tedge-minimal.yaml
  justfile
Labels: theme:packaging

#2196 build: install cargo-zigbuild using latest stable version
  ci/build_scripts/build.sh
Labels: bug, ci/cd

#2191 dev: activate python venv before calling integration tests
  justfile
Labels: theme:developer-exp, theme:testing

#2197 test: integration test improvements by updating libraries and reducing apt packages
  tests/RobotFramework/requirements/requirements.adapter-docker.txt
  tests/RobotFramework/requirements/requirements.adapter-local.txt
  tests/RobotFramework/requirements/requirements.adapter-ssh.txt
  tests/RobotFramework/tasks.py
  tests/RobotFramework/tests/installation/install_tedge.robot
  tests/images/debian-systemd/debian-systemd.dockerfile
  tests/images/debian-systemd/files/tedge.toml
Labels: theme:testing

#2198 Add test for sm plugin max packages (and fixes)
  crates/core/plugin_sm/src/plugin.rs
  crates/core/plugin_sm/src/plugin_manager.rs
  tests/RobotFramework/tests/cumulocity/software_management/dummy-plugin.sh
  tests/RobotFramework/tests/cumulocity/software_management/sm-plugin.robot
  tests/RobotFramework/tests/cumulocity/software_management/software.robot
Labels: theme:software, theme:plugins, theme:testing
