Repository thin-edge/thin-edge.io, pull requests merged in 2023-10, with the labels that each got.

#2295 Make tedge a multi-call binary
  Cargo.lock
  Cargo.toml
  ci/build_scripts/package.sh
  configuration/package_manifests/nfpm.c8y-configuration-plugin.yaml
  configuration/package_manifests/nfpm.c8y-firmware-plugin.yaml
  configuration/package_manifests/nfpm.c8y-remote-access-plugin.yaml
  configuration/package_manifests/nfpm.tedge-agent.yaml
  configuration/package_manifests/nfpm.tedge-apt-plugin.yaml
  configuration/package_manifests/nfpm.tedge-log-plugin.yaml
  configuration/package_manifests/nfpm.tedge-mapper.yaml
  configuration/package_manifests/nfpm.tedge-watchdog.yaml
  crates/core/tedge/Cargo.toml
  crates/core/tedge/src/cli/init.rs
  crates/core/tedge/src/cli/mod.rs
  crates/core/tedge/src/main.rs
  crates/core/tedge_agent/src/lib.rs
  crates/core/tedge_agent/src/main.rs
  crates/core/tedge_mapper/src/az/mapper.rs
  crates/core/tedge_mapper/src/lib.rs
  crates/core/tedge_mapper/src/main.rs
  crates/core/tedge_watchdog/src/lib.rs
  crates/core/tedge_watchdog/src/main.rs
  plugins/c8y_configuration_plugin/src/lib.rs
  plugins/c8y_configuration_plugin/src/main.rs
  plugins/c8y_firmware_plugin/src/lib.rs
  plugins/c8y_firmware_plugin/src/main.rs
  plugins/c8y_remote_access_plugin/src/input.rs
  plugins/c8y_remote_access_plugin/src/lib.rs
  plugins/c8y_remote_access_plugin/src/main.rs
  plugins/tedge_apt_plugin/src/lib.rs
  plugins/tedge_apt_plugin/src/main.rs
  plugins/tedge_log_plugin/src/lib.rs
  plugins/tedge_log_plugin/src/main.rs
Labels: theme:packaging

#2298 Update overview.md
  docs/src/overview.md
Labels: documentation, theme:installation

#2319 Handle binary uploads/downloads without attempting conversion to UTF-8
  Cargo.lock
  crates/core/tedge_agent/src/file_transfer_server/http_rest.rs
  crates/extensions/c8y_http_proxy/Cargo.toml
  crates/extensions/c8y_http_proxy/src/actor.rs
  tests/RobotFramework/requirements/requirements.txt
  tests/RobotFramework/tests/config_management/child_conf_mgmt_plugin.robot
  tests/RobotFramework/tests/config_management/config.txt.tar.gz
  tests/RobotFramework/tests/cumulocity/configuration/binary-config1.tar.gz
  tests/RobotFramework/tests/cumulocity/configuration/c8y-configuration-plugin.toml
  tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
Labels: theme:configuration, theme:c8y

#2339 refactor to use lib file to enable calling from the multi-call binary
  plugins/tedge_configuration_plugin/src/lib.rs
  plugins/tedge_configuration_plugin/src/main.rs
Labels: refactoring, theme:configuration

#2334 feat: allow non-root users to read c8y-bridge configuration file
  crates/core/tedge/src/cli/connect/command.rs
  tests/RobotFramework/tests/tedge_connect/tedge_connect_test.robot
Labels: theme:configuration

#2280 feat(mqtt): add docs for tedge data/inventory topic
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/tedge_api/src/mqtt_topics.rs
  crates/extensions/c8y_mapper_ext/src/config.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/inventory.rs
  crates/extensions/c8y_mapper_ext/src/lib.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  docs/src/references/mappers/c8y-mapper.md
  docs/src/references/mqtt-api.md
  tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot
  tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
  tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
Labels: theme:telemetry, theme:c8y

#2359 build: use fallback version when git describe only returns a hash
  ci/build_scripts/version.sh
Labels: theme:packaging, theme:developer-exp

#2360 fix: prevent tedge-agent service stoppage when upgrading from tedge_agent
  configuration/package_manifests/nfpm.tedge-agent.yaml
  configuration/package_scripts/_generated/tedge-agent/apk/postinst
  configuration/package_scripts/_generated/tedge-agent/deb/postinst
  configuration/package_scripts/_generated/tedge-agent/rpm/postinst
  configuration/package_scripts/tedge-agent/postinst
  tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
Labels: theme:software, theme:packaging

#2368 Switch to tedge-configuration-plugin
  Cargo.lock
  Cargo.toml
  ci/build_scripts/build.sh
  ci/package_list.sh
  configuration/init/systemd/75-tedge.preset
  configuration/init/systemd/tedge-configuration-plugin.service
  configuration/package_manifests/nfpm.c8y-configuration-plugin.yaml
  configuration/package_manifests/nfpm.tedge-configuration-plugin.yaml
  configuration/package_manifests/virtual/nfpm.tedge-full.yaml
  configuration/package_scripts/_generated/tedge-configuration-plugin/apk/postinst
  configuration/package_scripts/_generated/tedge-configuration-plugin/apk/postrm
  configuration/package_scripts/_generated/tedge-configuration-plugin/apk/preinst
  configuration/package_scripts/_generated/tedge-configuration-plugin/apk/prerm
  configuration/package_scripts/_generated/tedge-configuration-plugin/deb/postinst
  configuration/package_scripts/_generated/tedge-configuration-plugin/deb/postrm
  configuration/package_scripts/_generated/tedge-configuration-plugin/deb/preinst
  configuration/package_scripts/_generated/tedge-configuration-plugin/deb/prerm
  configuration/package_scripts/_generated/tedge-configuration-plugin/rpm/postinst
  configuration/package_scripts/_generated/tedge-configuration-plugin/rpm/postrm
  configuration/package_scripts/_generated/tedge-configuration-plugin/rpm/preinst
  configuration/package_scripts/_generated/tedge-configuration-plugin/rpm/prerm
  configuration/package_scripts/packages.json
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/common/tedge_utils/src/file.rs
  crates/core/tedge/Cargo.toml
  crates/core/tedge/src/cli/mod.rs
  crates/core/tedge/src/main.rs
  crates/core/tedge_watchdog/src/systemd_watchdog.rs
  crates/extensions/c8y_mapper_ext/src/inventory.rs
  crates/extensions/tedge_health_ext/src/lib.rs
  docs/src/contribute/DEBIAN_PACKAGE_HOSTING.md
  tests/RobotFramework/requirements/requirements.adapter-docker.txt
  tests/RobotFramework/requirements/requirements.adapter-local.txt
  tests/RobotFramework/requirements/requirements.adapter-ssh.txt
  tests/RobotFramework/requirements/requirements.txt
  tests/RobotFramework/tasks/build_install_rpi.robot
  tests/RobotFramework/tests/MQTT_health_check/MQTT_health_endpoints.robot
  tests/RobotFramework/tests/MQTT_health_check/health_tedge-configuration-plugin.robot
  tests/RobotFramework/tests/config_management/child_conf_mgmt_plugin.robot
  tests/RobotFramework/tests/config_management/inotify_crate.robot
  tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
  tests/RobotFramework/tests/cumulocity/configuration/tedge-configuration-plugin-updated.toml
  tests/RobotFramework/tests/cumulocity/configuration/tedge-configuration-plugin.toml
  tests/RobotFramework/tests/cumulocity/jwt/jwt_request.robot
  tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
  tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
  tests/RobotFramework/tests/customizing/config_dir.robot
  tests/RobotFramework/tests/installation/install_apt.robot
  tests/RobotFramework/tests/installation/install_tedge.robot
  tests/RobotFramework/tests/mqtt/remote_mqtt_broker.robot
  tests/images/debian-systemd/debian-systemd.dockerfile
  tests/images/debian-systemd/files/bootstrap.sh
  tests/images/debian-systemd/files/tedge-configuration-plugin.toml
  uninstall-thin-edge_io.sh
Labels: theme:configuration, theme:packaging

#2376 docs: fix registration examples
  docs/src/references/mappers/c8y-mapper.md
  docs/src/references/mqtt-api.md
Labels: documentation, theme:registration

#2380 Replace c8y-configuration-management doc by tedge-
  docs/src/references/c8y-configuration-management.md
  docs/src/references/tedge-configuration-management.md
Labels: documentation

#2307 Support for software list & update on child devices
  crates/core/c8y_api/src/json_c8y.rs
  crates/core/c8y_api/src/smartrest/error.rs
  crates/core/c8y_api/src/smartrest/smartrest_deserializer.rs
  crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
  crates/core/c8y_api/src/smartrest/topic.rs
  crates/core/plugin_sm/src/plugin_manager.rs
  crates/core/tedge_agent/Cargo.toml
  crates/core/tedge_agent/src/software_manager/actor.rs
  crates/core/tedge_agent/src/software_manager/builder.rs
  crates/core/tedge_agent/src/software_manager/config.rs
  crates/core/tedge_agent/src/software_manager/tests.rs
  crates/core/tedge_agent/src/tedge_operation_converter/actor.rs
  crates/core/tedge_agent/src/tedge_operation_converter/builder.rs
  crates/core/tedge_agent/src/tedge_operation_converter/tests.rs
  crates/core/tedge_api/src/lib.rs
  crates/core/tedge_api/src/messages.rs
  crates/core/tedge_api/src/mqtt_topics.rs
  crates/core/tedge_api/src/topic.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
  crates/extensions/c8y_http_proxy/src/actor.rs
  crates/extensions/c8y_mapper_ext/src/compatibility_adapter.rs
  crates/extensions/c8y_mapper_ext/src/config.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/lib.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  crates/extensions/tedge_mqtt_ext/src/test_helpers.rs
  tests/RobotFramework/tests/cumulocity/mapper_recovery/recover_and_publish_software_update_message.robot
  tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
  tests/RobotFramework/tests/cumulocity/software_management/software-update-child.robot
  tests/RobotFramework/tests/cumulocity/software_management/software.robot
  tests/RobotFramework/tests/cumulocity/supported_operations/mapper-publishing-agent-supported-ops.robot
  tests/images/debian-systemd/files/tedge.toml
Labels: theme:software

#2382 docs: fix broken links and references to tedge-configuration-plugin
  docs/src/operate/c8y/config_management_plugin.md
  docs/src/operate/configuration/update_config_paths.md
  docs/src/operate/troubleshooting/monitor_tedge_health.md
  docs/src/operate/troubleshooting/thin_edge_logs.md
  docs/src/references/agent/restart-operation.md
  docs/src/references/agent/tedge-configuration-management.md
  docs/src/references/agent/tedge-log-management.md
  docs/src/references/domain-model.md
  docs/src/start/getting-started.md
  docs/src/understand/tedge-agent.md
  tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
Labels: documentation

#2369 fix: support sending previously cleared twin property value
  crates/core/tedge_api/src/entity_store.rs
  crates/extensions/c8y_mapper_ext/src/actor.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/inventory.rs
  crates/extensions/c8y_mapper_ext/src/service_monitor.rs
  crates/extensions/tedge_health_ext/src/lib.rs
  crates/extensions/tedge_mqtt_ext/src/test_helpers.rs
  tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
Labels: bug, theme:telemetry

#2384 use mqtt v1 in docs
  docs/src/contribute/writing-documentation/markdown-components.md
  docs/src/contribute/writing-documentation/markdown-guidelines.md
  docs/src/operate/c8y/tedge_log_management.md
  docs/src/operate/telemetry/pub_sub.md
  docs/src/operate/troubleshooting/trouble_shooting_monitoring.md
  docs/src/references/agent/device-management-api.md
  docs/src/references/agent/software-management.md
  docs/src/references/data-model.md
  docs/src/references/mappers/c8y-mapper.md
  docs/src/references/mqtt-api.md
  docs/src/references/mqtt-topics.md
  docs/src/start/connect-aws.md
  docs/src/start/connect-azure.md
  docs/src/start/device-monitoring.md
  docs/src/start/getting-started.md
  docs/src/start/raise-alarm.md
  docs/src/start/send-events.md
  docs/src/start/send-thin-edge-data.md
  docs/src/understand/tedge-agent.md
  docs/src/understand/tedge-mapper.md
  docs/src/understand/thin-edge-json.md
Labels: documentation, theme:mqtt
