Repository thin-edge/thin-edge.io, pull requests merged in 2024-11, with the labels that each got.

#3210 fix: agent leaves interrupted operations in non-final state
  crates/core/tedge_agent/src/operation_workflows/actor.rs
  tests/RobotFramework/tests/tedge_agent/workflows/dynamic_workflow_reloading.robot
  tests/RobotFramework/tests/tedge_agent/workflows/sleep-command.toml
Labels: bug, theme:workflows

#3221 fix: config set instructions in certificate error message
  crates/core/tedge/src/cli/connect/error.rs
Labels: theme:troubleshooting

#3219 feat: c8y basic auth improvements
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/c8y_api/src/http_proxy.rs
  tests/RobotFramework/tests/cumulocity/smartrest_one/smartrest_one.robot
Labels: theme:c8y, skip-release-notes

#3223 fix: tedge-agent error does not show which file does not exist
  crates/common/certificate/src/lib.rs
  crates/common/certificate/src/parse_root_certificate.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/tedge/src/cli/certificate/create.rs
  crates/core/tedge/src/cli/certificate/show.rs
Labels: theme:troubleshooting

#3245 docs: remove docs for measurements with units
  docs/src/references/mappers/c8y-mapper.md
Labels: documentation, theme:c8y

#3247 test: add workflow test running on child device
  tests/RobotFramework/tests/tedge_agent/workflows/run_workflow_on_child_device.robot
Labels: theme:workflows, skip-release-notes

#3244 feat: allow profiled and non-profiled cloud configurations to co-exist
  Cargo.lock
  crates/common/tedge_config_macros/Cargo.toml
  crates/common/tedge_config_macros/impl/src/input/validate.rs
  crates/common/tedge_config_macros/impl/src/query.rs
  crates/common/tedge_config_macros/impl/src/reader.rs
  crates/common/tedge_config_macros/src/multi.rs
Labels: theme:c8y, theme:cli

#3253 ci: remove test exclusion options from workflow
  .github/workflows/build-workflow.yml
Labels: ci/cd, skip-release-notes

#3255 test: skip remote access tests that are failing to Cumulocity core issue
  tests/RobotFramework/tasks.py
  tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot
  tests/RobotFramework/tests/cumulocity/remote-access/test_remote_access.robot
  tests/RobotFramework/tests/cumulocity/remote-access/test_remote_access_custom_root_cert_path.robot
Labels: theme:testing, skip-release-notes

#3246 bug: wait for mosquitto to start rather than blindly sleeping in `tedge connect`
  Cargo.lock
  crates/common/tedge_config/src/system_services/manager.rs
  crates/common/tedge_config/src/system_services/manager_ext.rs
  crates/common/tedge_config/src/system_services/managers/config.rs
  crates/core/tedge/Cargo.toml
  crates/core/tedge/src/bridge/aws.rs
  crates/core/tedge/src/bridge/azure.rs
  crates/core/tedge/src/bridge/c8y.rs
  crates/core/tedge/src/bridge/config.rs
  crates/core/tedge/src/cli/certificate/create.rs
  crates/core/tedge/src/cli/certificate/create_csr.rs
  crates/core/tedge/src/cli/certificate/mod.rs
  crates/core/tedge/src/cli/certificate/remove.rs
  crates/core/tedge/src/cli/certificate/renew.rs
  crates/core/tedge/src/cli/certificate/show.rs
  crates/core/tedge/src/cli/certificate/upload.rs
  crates/core/tedge/src/cli/config/commands/add.rs
  crates/core/tedge/src/cli/config/commands/get.rs
  crates/core/tedge/src/cli/config/commands/list.rs
  crates/core/tedge/src/cli/config/commands/remove.rs
  crates/core/tedge/src/cli/config/commands/set.rs
  crates/core/tedge/src/cli/config/commands/unset.rs
  crates/core/tedge/src/cli/connect/c8y_direct_connection.rs
  crates/core/tedge/src/cli/connect/cli.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/cli/connect/error.rs
  crates/core/tedge/src/cli/connect/jwt_token.rs
  crates/core/tedge/src/cli/disconnect/disconnect_bridge.rs
  crates/core/tedge/src/cli/disconnect/error.rs
  crates/core/tedge/src/cli/disconnect/mod.rs
  crates/core/tedge/src/cli/init.rs
  crates/core/tedge/src/cli/log.rs
  crates/core/tedge/src/cli/mod.rs
  crates/core/tedge/src/cli/mqtt/publish.rs
  crates/core/tedge/src/cli/mqtt/subscribe.rs
  crates/core/tedge/src/cli/reconnect/command.rs
  crates/core/tedge/src/cli/refresh_bridges.rs
  crates/core/tedge/src/command.rs
  crates/core/tedge/src/main.rs
  tests/RobotFramework/tasks/build_install_rpi.robot
  tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot
  tests/RobotFramework/tests/cumulocity/remote-access/test_remote_access.robot
  tests/RobotFramework/tests/tedge/tedge_upload_cert.robot
  tests/RobotFramework/tests/tedge/tedge_upload_cert_custom_root_cert_path.robot
  tests/RobotFramework/tests/tedge_connect/tedge_connect_test.robot
Labels: theme:mqtt

#3224 refactor: simplify c8y_http_proxy
  Cargo.lock
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/c8y_api/Cargo.toml
  crates/core/c8y_api/src/http_proxy.rs
  crates/core/c8y_api/src/json_c8y.rs
  crates/core/c8y_api/src/lib.rs
  crates/core/c8y_api/src/proxy_url.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
  crates/extensions/c8y_auth_proxy/Cargo.toml
  crates/extensions/c8y_auth_proxy/src/actor.rs
  crates/extensions/c8y_auth_proxy/src/lib.rs
  crates/extensions/c8y_auth_proxy/src/server.rs
  crates/extensions/c8y_auth_proxy/src/tokens.rs
  crates/extensions/c8y_firmware_manager/Cargo.toml
  crates/extensions/c8y_firmware_manager/src/actor.rs
  crates/extensions/c8y_firmware_manager/src/config.rs
  crates/extensions/c8y_firmware_manager/src/error.rs
  crates/extensions/c8y_firmware_manager/src/lib.rs
  crates/extensions/c8y_firmware_manager/src/tests.rs
  crates/extensions/c8y_firmware_manager/src/worker.rs
  crates/extensions/c8y_http_proxy/src/actor.rs
  crates/extensions/c8y_http_proxy/src/credentials.rs
  crates/extensions/c8y_http_proxy/src/handle.rs
  crates/extensions/c8y_http_proxy/src/lib.rs
  crates/extensions/c8y_http_proxy/src/messages.rs
  crates/extensions/c8y_http_proxy/src/tests.rs
  crates/extensions/c8y_mapper_ext/Cargo.toml
  crates/extensions/c8y_mapper_ext/src/actor.rs
  crates/extensions/c8y_mapper_ext/src/config.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/operations/convert.rs
  crates/extensions/c8y_mapper_ext/src/operations/handler.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/config_update.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/device_profile.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/firmware_update.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/mod.rs
  crates/extensions/c8y_mapper_ext/src/operations/upload.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  crates/extensions/tedge_http_ext/Cargo.toml
  crates/extensions/tedge_http_ext/src/lib.rs
  crates/extensions/tedge_http_ext/src/messages.rs
  crates/extensions/tedge_http_ext/src/test_helpers.rs
  crates/extensions/tedge_http_ext/src/tests.rs
  plugins/c8y_firmware_plugin/Cargo.toml
  plugins/c8y_firmware_plugin/src/lib.rs
  plugins/c8y_remote_access_plugin/src/auth.rs
Labels: refactoring, theme:c8y

#3258 fix: builtin workflows don't have to be released
  crates/core/tedge_agent/src/operation_workflows/persist.rs
  crates/core/tedge_api/src/workflow/mod.rs
  crates/core/tedge_api/src/workflow/supervisor.rs
Labels: improvement, theme:workflows

#3265 dev: publish devcontainer image
  .devcontainer/Dockerfile
  .devcontainer/docker-compose.yml
  .github/workflows/devcontainer.yml
  justfile
Labels: theme:developer-exp

#3267 dev: don't publish image for linux armv7 as it is not supported by the Rust image
  justfile
Labels: theme:developer-exp, skip-release-notes

#3225 feat: add workflow support for custom operation (drop 2)
  crates/common/tedge_utils/src/file.rs
  crates/core/c8y_api/src/smartrest/operations.rs
  crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
  crates/core/tedge_api/src/workflow/state.rs
  crates/extensions/c8y_mapper_ext/src/config.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/operations/convert.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/custom_operation.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/mod.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  tests/RobotFramework/requirements/requirements.adapter-docker.txt
  tests/RobotFramework/requirements/requirements.adapter-local.txt
  tests/RobotFramework/requirements/requirements.adapter-ssh.txt
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_workflow/c8y_OpenDoor.template
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_workflow/c8y_TakePicture.template
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_workflow/custom_operation_workflow.robot
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_workflow/do_something.sh
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_workflow/open_door.toml
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_workflow/take_picture.toml
Labels: theme:workflows

#3270 feat: Improve custom operation workflow input
  crates/core/c8y_api/src/smartrest/operations.rs
  crates/extensions/c8y_mapper_ext/src/operations/convert.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
Labels: theme:c8y, theme:workflows

#3268 refactor: Untangle certificate request, creation and renewal
  crates/common/certificate/src/lib.rs
  crates/core/tedge/src/cli/certificate/cli.rs
  crates/core/tedge/src/cli/certificate/create.rs
  crates/core/tedge/src/cli/certificate/create_csr.rs
  crates/core/tedge/src/cli/certificate/renew.rs
Labels: refactoring, theme:certificates

#3269 dev: Update rust dev tools
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  justfile
Labels: theme:developer-exp

#3264 feat: add filtering to `tedge config list`
  crates/core/tedge/src/cli/config/cli.rs
  crates/core/tedge/src/cli/config/commands/list.rs
Labels: theme:cli
