Repository thin-edge/thin-edge.io, pull requests merged in 2024-12, with the labels that each got.

#3275 dev: only build devcontainer on main branch
  .github/workflows/devcontainer.yml
Labels: ci/cd, theme:developer-exp, skip-release-notes

#3276 test: update robotframework-c8y library
  tests/RobotFramework/requirements/requirements.txt
Labels: theme:testing

#3262 feat: add profile support to the `tedge` cli and fix mosquitto configuration
  configuration/init/systemd/tedge-mapper-aws@.service
  configuration/init/systemd/tedge-mapper-az@.service
  configuration/init/systemd/tedge-mapper-c8y@.service
  configuration/package_manifests/nfpm.tedge-mapper.yaml
  crates/common/tedge_config/src/system_services/manager.rs
  crates/common/tedge_config/src/system_services/manager_ext.rs
  crates/common/tedge_config/src/system_services/managers/general_manager.rs
  crates/common/tedge_config/src/system_services/services.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config_location.rs
  crates/common/tedge_config_macros/examples/macro.rs
  crates/common/tedge_config_macros/impl/src/input/validate.rs
  crates/common/tedge_config_macros/impl/src/query.rs
  crates/common/tedge_config_macros/impl/src/reader.rs
  crates/common/tedge_config_macros/src/define_tedge_config_docs.md
  crates/core/c8y_api/src/smartrest/operations.rs
  crates/core/tedge/src/bridge/aws.rs
  crates/core/tedge/src/bridge/azure.rs
  crates/core/tedge/src/bridge/c8y.rs
  crates/core/tedge/src/bridge/config.rs
  crates/core/tedge/src/cli/certificate/cli.rs
  crates/core/tedge/src/cli/common.rs
  crates/core/tedge/src/cli/connect/cli.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/cli/connect/error.rs
  crates/core/tedge/src/cli/disconnect/cli.rs
  crates/core/tedge/src/cli/disconnect/disconnect_bridge.rs
  crates/core/tedge/src/cli/mod.rs
  crates/core/tedge/src/cli/reconnect/cli.rs
  crates/core/tedge/src/cli/reconnect/command.rs
  crates/core/tedge/src/cli/refresh_bridges.rs
  crates/core/tedge/src/error.rs
  crates/core/tedge/src/main.rs
  crates/core/tedge_mapper/src/aws/mapper.rs
  crates/core/tedge_mapper/src/az/mapper.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
  crates/core/tedge_mapper/src/lib.rs
  crates/extensions/c8y_firmware_manager/src/config.rs
  crates/extensions/c8y_mapper_ext/src/availability/mod.rs
  crates/extensions/c8y_mapper_ext/src/config.rs
  crates/extensions/c8y_mapper_ext/src/error.rs
  crates/extensions/tedge_mqtt_bridge/src/config.rs
  plugins/c8y_remote_access_plugin/src/input.rs
  plugins/c8y_remote_access_plugin/src/lib.rs
  tests/RobotFramework/tests/cumulocity/configuration/configuration_operation_multi_cloud.robot
  tests/RobotFramework/tests/cumulocity/remote-access/test_remote_access_with_cloud_profiles.robot
Labels: theme:c8y, theme:cli, theme:aws, theme:az

#3277 refactor: Extract `supported_operations` module from `c8y_api`
  crates/core/c8y_api/src/smartrest/error.rs
  crates/core/c8y_api/src/smartrest/mod.rs
  crates/core/c8y_api/src/smartrest/operations.rs
  crates/extensions/c8y_mapper_ext/src/config.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/dynamic_discovery.rs
  crates/extensions/c8y_mapper_ext/src/error.rs
  crates/extensions/c8y_mapper_ext/src/lib.rs
  crates/extensions/c8y_mapper_ext/src/operations/convert.rs
  crates/extensions/c8y_mapper_ext/src/supported_operations/mod.rs
  crates/extensions/c8y_mapper_ext/src/supported_operations/operation.rs
Labels: refactoring

#3287 docs: remove workflow warnings
  docs/src/references/agent/operation-workflow.md
Labels: documentation, theme:workflows

#3288 dev: update code owners
  .github/CODEOWNERS
Labels: skip-release-notes

#3286 feat: add c8y createBulk topics to bridge
  crates/core/tedge/src/bridge/c8y.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
  tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot
  tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
  tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry_built-in_bridge.robot
Labels: theme:c8y

#3282 refactor: Create a module with smartrest message id consts
  crates/core/c8y_api/src/smartrest/alarm.rs
  crates/core/c8y_api/src/smartrest/inventory.rs
  crates/core/c8y_api/src/smartrest/message_ids.rs
  crates/core/c8y_api/src/smartrest/mod.rs
  crates/core/c8y_api/src/smartrest/payload.rs
  crates/core/c8y_api/src/smartrest/smartrest_deserializer.rs
  crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
  crates/core/c8y_api/src/utils.rs
  crates/core/tedge/src/cli/connect/c8y_direct_connection.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/extensions/c8y_firmware_manager/src/actor.rs
  crates/extensions/c8y_firmware_manager/src/tests.rs
  crates/extensions/c8y_firmware_manager/src/worker.rs
  crates/extensions/c8y_mapper_ext/src/operations/convert.rs
Labels: refactoring

#3280 Add documentation for custom operation workflow handler
  docs/src/operate/c8y/supported-operations.md
Labels: documentation, theme:workflows

#3283 Custom operation handler should parse extra arguments for 503/506 messages
  crates/core/tedge_api/src/mqtt_topics.rs
  crates/core/tedge_api/src/workflow/state.rs
  crates/extensions/c8y_mapper_ext/src/operations/convert.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/custom_operation.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/mod.rs
  crates/extensions/c8y_mapper_ext/src/supported_operations/operation.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_c8y_RelayArray_workflow/c8y_RelayArray.template
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_c8y_RelayArray_workflow/operation_relay_array_workflow.robot
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_c8y_RelayArray_workflow/set_relay.sh
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_c8y_RelayArray_workflow/set_relay.toml
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command_workflow/c8y_Command.template
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command_workflow/operation_command_workflow.robot
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command_workflow/shell_execute.sh
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command_workflow/shell_execute.toml
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_workflow/do_something.sh
Labels: theme:c8y

#3295 fix #3279: Create a fast path for sending `PublishMessage`s
  crates/extensions/c8y_mapper_ext/src/actor.rs
  tests/RobotFramework/tests/cumulocity/registration/processes_many_devices.robot
Labels: bug, theme:c8y

#3274 feat: tedge upload c8y
  Cargo.lock
  crates/core/c8y_api/src/http_proxy.rs
  crates/core/c8y_api/src/proxy_url.rs
  crates/core/tedge/Cargo.toml
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/cli/mod.rs
  crates/core/tedge/src/cli/upload/c8y.rs
  crates/core/tedge/src/cli/upload/mod.rs
  crates/core/tedge/src/error.rs
  crates/extensions/c8y_http_proxy/src/actor.rs
  crates/extensions/c8y_http_proxy/src/handle.rs
  crates/tests/tedge_test_utils/src/fs.rs
  docs/src/operate/c8y/upload-files.md
  docs/src/references/cli/index.md
  docs/src/references/cli/tedge-upload.md
  tests/RobotFramework/tests/cumulocity/upload/tedge_c8y_upload.robot
Labels: theme:c8y, theme:cli

#3298 docs: update yocto instructions to use new kas project location
  docs/src/extend/firmware-management/building-image/yocto/tutorial.md
Labels: documentation, theme:yocto, theme:firmware

#3296 feat(packaging): manage tedge-mapper cloud profile service instances in install/upgrade/uninstall
  configuration/init/systemd/tedge-mapper-aws.service
  configuration/init/systemd/tedge-mapper-aws.target
  configuration/init/systemd/tedge-mapper-aws@.service
  configuration/init/systemd/tedge-mapper-az.target
  configuration/init/systemd/tedge-mapper-az@.service
  configuration/init/systemd/tedge-mapper-c8y.target
  configuration/init/systemd/tedge-mapper-c8y@.service
  configuration/package_manifests/nfpm.tedge-mapper.yaml
  configuration/package_scripts/_generated/c8y-firmware-plugin/apk/postinst
  configuration/package_scripts/_generated/c8y-firmware-plugin/apk/postrm
  configuration/package_scripts/_generated/c8y-remote-access-plugin/apk/postinst
  configuration/package_scripts/_generated/c8y-remote-access-plugin/apk/postrm
  configuration/package_scripts/_generated/tedge-agent/apk/postrm
  configuration/package_scripts/_generated/tedge-mapper/apk/postinst
  configuration/package_scripts/_generated/tedge-mapper/apk/postrm
  configuration/package_scripts/_generated/tedge-mapper/deb/postinst
  configuration/package_scripts/_generated/tedge-mapper/deb/postrm
  configuration/package_scripts/_generated/tedge-mapper/deb/prerm
  configuration/package_scripts/_generated/tedge-mapper/rpm/postinst
  configuration/package_scripts/_generated/tedge-mapper/rpm/postrm
  configuration/package_scripts/_generated/tedge-mapper/rpm/prerm
  configuration/package_scripts/_generated/tedge-watchdog/apk/postinst
  configuration/package_scripts/_generated/tedge-watchdog/apk/postrm
  configuration/package_scripts/generate.py
  configuration/package_scripts/packages.json
  tests/RobotFramework/tests/cumulocity/configuration/configuration_operation_multi_cloud.robot
Labels: theme:packaging, skip-release-notes

#3301 fix: Collect multiple smartrest messages from c8y devicecontrol topic
  crates/core/c8y_api/src/smartrest/message.rs
  crates/extensions/c8y_firmware_manager/src/actor.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
Labels: theme:c8y

#3302 fix: split c8y JSON over MQTT messages using newline delimiter
  crates/core/c8y_api/src/smartrest/message.rs
  crates/extensions/c8y_firmware_manager/src/actor.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
Labels: bug, theme:c8y

#3299 doc: cloud profiles in Cumulocity
  crates/common/tedge_config_macros/src/multi.rs
  crates/core/tedge/src/cli/config/commands/list.rs
  crates/core/tedge/src/cli/connect/command.rs
  docs/src/operate/c8y/cloud-profiles.md
Labels: documentation, skip-release-notes

#3304 minor version bump
  Cargo.lock
  Cargo.toml
Labels: skip-release-notes

#3306 fix: process non-versioned in-progress commands on startup
  crates/core/tedge_api/src/workflow/supervisor.rs
  tests/RobotFramework/tests/cumulocity/self-update/apt_package_pinning
  tests/RobotFramework/tests/cumulocity/self-update/software_update.toml
  tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
Labels: theme:workflows

#3307 fix: Persist workflow definition of pending commands on start
  crates/core/tedge_agent/src/operation_workflows/actor.rs
  crates/core/tedge_agent/src/operation_workflows/persist.rs
  crates/core/tedge_api/src/workflow/supervisor.rs
Labels: bug, theme:workflows

#3308 patch version bump
  Cargo.lock
  Cargo.toml
Labels: skip-release-notes

#3310 fix: cleanup empty profiles
  crates/common/tedge_config_macros/impl/src/query.rs
  crates/common/tedge_config_macros/src/multi.rs
Labels: theme:cli
