Repository thin-edge/thin-edge.io, pull requests merged in 2024-04, with the labels that each got.

#2791 fix(#2749): Check sudo.enable in software and restart managers
  Cargo.lock
  crates/common/logged_command/src/logged_command.rs
  crates/common/tedge_config/Cargo.toml
  crates/common/tedge_config/src/lib.rs
  crates/common/tedge_config/src/sudo.rs
  crates/core/plugin_sm/src/plugin.rs
  crates/core/plugin_sm/src/plugin_manager.rs
  crates/core/plugin_sm/tests/plugin.rs
  crates/core/plugin_sm/tests/plugin_manager.rs
  crates/core/tedge_agent/src/restart_manager/actor.rs
  crates/core/tedge_agent/src/restart_manager/config.rs
  crates/core/tedge_agent/src/restart_manager/tests.rs
  crates/core/tedge_agent/src/software_manager/actor.rs
  crates/core/tedge_agent/src/software_manager/config.rs
  crates/core/tedge_agent/src/software_manager/tests.rs
  crates/core/tedge_write/Cargo.toml
  crates/core/tedge_write/src/api.rs
  crates/core/tedge_write/tests/main.rs
  crates/extensions/tedge_config_manager/src/actor.rs
  crates/extensions/tedge_config_manager/src/config.rs
Labels: theme:software, theme:troubleshooting

#2812 tests: explicitly select musl builds when building test container
  tests/RobotFramework/tasks.py
Labels: theme:testing

#2828 docs: remove retain from cmd/health/check examples
  docs/src/references/mqtt-api.md
Labels: documentation

#2829 test(dev): update black version CVE-2024-21503
  tests/RobotFramework/requirements/requirements.dev.txt
Labels: theme:developer-exp, theme:testing

#2841 ci: remove workaround since the upstream microsoft repo has been resolved
  .github/workflows/build-workflow.yml
Labels: ci/cd

#2839 Add apt-get update befor executing apt-get install
  tests/RobotFramework/tasks/E2E_Tutorials/Connect_to_c8y.robot
  tests/RobotFramework/tests/cumulocity/benchmarks/benchmarks.robot
  tests/RobotFramework/tests/cumulocity/monitoring/monitor_device_collectd.robot
  tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
  tests/RobotFramework/tests/installation/install_apt.robot
  tests/RobotFramework/tests/plugin_apt/improve_tedge_apt_plugin_error_messages.robot
Labels: theme:testing

#2779 Entity deregistration API proposals
  design/decisions/0004-entity-dregister-api.md
Labels: theme:mqtt, theme:registration
