Repository thin-edge/thin-edge.io, pull requests merged in 2024-08, with the labels that each got.

#3033 fix: tedge-agent use the root topic when provided by the cli flag
  crates/core/tedge_agent/src/agent.rs
  crates/core/tedge_agent/src/operation_workflows/config.rs
  tests/RobotFramework/tests/tedge_agent/tedge_agent_as_child.robot
Labels: theme:childdevices

#3040 ci: changelog formatting and classification improvements
  cliff.toml
Labels: ci/cd

#3035 fix: tedge-agent skip legacy topic subscription when running as a child device
  crates/core/tedge_agent/src/agent.rs
  tests/RobotFramework/tests/tedge_agent/tedge_agent_as_child.robot
Labels: theme:childdevices

#3041 test: fix unit test to pass when the unit socket file exists
  plugins/c8y_remote_access_plugin/src/input.rs
Labels: theme:plugins, theme:testing

#3042 minor version bump
  Cargo.lock
  Cargo.toml
Labels: skip-release-notes

#3045 Revert "minor version bump"
  Cargo.lock
  Cargo.toml
Labels: skip-release-notes

#3044 ci: changelog generation from tags and don't fail on errors
  .github/workflows/build-workflow.yml
  ci/changelog/changelog.sh
Labels: ci/cd

#3047 minor version bump
  Cargo.lock
  Cargo.toml
Labels: skip-release-notes

#3049 refactor: CommandStatus::Executing takes extra MQTT messages
  crates/extensions/c8y_mapper_ext/src/operations/handlers/config_snapshot.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/config_update.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/firmware_update.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/log_upload.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/mod.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/restart.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/software_update.rs
Labels: refactoring

#3015 feat: add operation mapping for device profile
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/c8y_api/src/json_c8y_deserializer.rs
  crates/core/c8y_api/src/smartrest/inventory.rs
  crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
  crates/core/tedge_api/src/commands.rs
  crates/core/tedge_api/src/device_profile.rs
  crates/core/tedge_api/src/lib.rs
  crates/core/tedge_api/src/mqtt_topics.rs
  crates/extensions/c8y_mapper_ext/src/config.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/lib.rs
  crates/extensions/c8y_mapper_ext/src/operations/convert.rs
  crates/extensions/c8y_mapper_ext/src/operations/handler.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/device_profile.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/mod.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
Labels: theme:c8y, theme:profile

#3059 fix: increase max packet size for built-in bridge
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/extensions/tedge_mqtt_bridge/src/lib.rs
  crates/extensions/tedge_mqtt_bridge/tests/bridge.rs
Labels: theme:mqtt

#3052 feat: make aws and azure topic prefixes configurable in built-in bridge
  Cargo.lock
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/tedge/src/bridge/aws.rs
  crates/core/tedge/src/bridge/azure.rs
  crates/core/tedge/src/bridge/c8y.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge_mapper/src/aws/mapper.rs
  crates/core/tedge_mapper/src/az/mapper.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
  crates/extensions/aws_mapper_ext/Cargo.toml
  crates/extensions/aws_mapper_ext/src/converter.rs
  crates/extensions/az_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/compatibility_adapter.rs
  crates/extensions/c8y_mapper_ext/src/config.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/operations/handler.rs
Labels: theme:c8y, theme:aws, theme:az

#3065 fix: software artifacts are downloaded twice when the `update-list` feature is not available
  crates/core/plugin_sm/src/plugin.rs
  tests/RobotFramework/tests/cumulocity/software_management/dummy-plugin.sh
  tests/RobotFramework/tests/cumulocity/software_management/sm-plugin.robot
Labels: bug, theme:software

#2920 feat: support device profile operation
  Cargo.lock
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/tedge_agent/src/agent.rs
  crates/core/tedge_agent/src/device_profile_manager/mod.rs
  crates/core/tedge_agent/src/lib.rs
  crates/core/tedge_agent/src/operation_workflows/actor.rs
  crates/core/tedge_agent/src/resources/device_profile.toml
  crates/core/tedge_api/Cargo.toml
  crates/core/tedge_api/src/workflow/error.rs
  crates/core/tedge_api/src/workflow/mod.rs
  crates/core/tedge_api/src/workflow/script.rs
  crates/core/tedge_api/src/workflow/state.rs
  crates/core/tedge_api/src/workflow/toml_config.rs
  docs/src/references/agent/device-profile.md
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
  tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
  tests/RobotFramework/tests/tedge_agent/device_profile/firmware_update.toml
  tests/RobotFramework/tests/tedge_agent/device_profile/tedge-configuration-plugin.toml
  tests/RobotFramework/tests/tedge_agent/device_profile/tedge_operator_helper.sh
  tests/images/debian-systemd/debian-systemd.dockerfile
Labels: theme:profile

#3076 feat: add an option to use c8y operation ID to update its status
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
  crates/core/tedge_api/src/mqtt_topics.rs
  crates/extensions/c8y_firmware_manager/src/message.rs
  crates/extensions/c8y_firmware_manager/src/worker.rs
  crates/extensions/c8y_mapper_ext/src/config.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/operations/handler.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/config_snapshot.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/config_update.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/device_profile.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/firmware_update.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/log_upload.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/mod.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/restart.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/software_update.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
  tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot
  tests/RobotFramework/tests/cumulocity/log/log_operation.robot
  tests/RobotFramework/tests/cumulocity/restart/restart_device.robot
  tests/RobotFramework/tests/cumulocity/software_management/software.robot
Labels: theme:c8y

#3087 ci(coverage): add codecov token
  .github/workflows/pull-request-checks.yml
Labels: ci/cd, skip-release-notes

#3089 test: Refactor Cumulocity IoT device profile system tests
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
  tests/RobotFramework/requirements/requirements.txt
  tests/RobotFramework/tests/cumulocity/software_management/sm-plugin.robot
  tests/RobotFramework/tests/installation/install_tedge.robot
  tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
  tests/images/debian-systemd/files/tedge.toml
Labels: theme:c8y, theme:profile

#3069 config-manager: Only use tedge-write after normal copy fails due to permissions and improve tedge-write logging
  Cargo.lock
  crates/common/tedge_config/src/sudo.rs
  crates/core/tedge_write/src/api.rs
  crates/extensions/tedge_config_manager/Cargo.toml
  crates/extensions/tedge_config_manager/src/actor.rs
  crates/extensions/tedge_config_manager/src/error.rs
  tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
Labels: theme:configuration

#3086 refactor: Simplify config manager control flow
  crates/extensions/tedge_config_manager/Cargo.toml
  crates/extensions/tedge_config_manager/src/actor.rs
  crates/extensions/tedge_config_manager/src/lib.rs
  crates/extensions/tedge_config_manager/src/tests.rs
Labels: refactoring, theme:configuration
