Repository thin-edge/thin-edge.io, pull requests merged in 2024-02, with the labels that each got.

#2646 test: collect both parent and child logs on test teardown for child log file operation
  tests/RobotFramework/tests/cumulocity/log/log_operation_child.robot
Labels: theme:testing

#2642 ci: add cloudsmith cleanup job to remove old packages
  .github/workflows/cloudsmith-cleanup.yml
  ci/admin/cloudsmith_admin.sh
Labels: ci/cd, theme:packaging

#2650 docs(getting started): remove explicit timestamps from example commands
  docs/src/start/getting-started.md
  docs/src/start/raise-alarm.md
  docs/src/start/send-events.md
Labels: documentation

#2658 test: fix redirection syntax error in setup
  tests/RobotFramework/bin/setup.sh
Labels: theme:testing

#2657 test: use unique child names when creating devices with an explicit @id field
  tests/RobotFramework/tests/cumulocity/registration/device_registration.robot
Labels: theme:testing

#2662 ci: remove ci_pipeline workflow and dependencies
  .github/workflows/ci_pipeline.yml
  README.md
  ci/az_upload_device_cert.py
  ci/ci_smoke_test_az.sh
  ci/ci_smoke_test_c8y.sh
  ci/configure_bridge.sh
  ci/delete_current_device_c8y.py
  ci/find_device_id.py
  ci/installation_scripts/clean_up_rpi.sh
  ci/installation_scripts/install_for_amd64.sh
  ci/installation_scripts/install_for_arm.sh
  ci/report/build.sh
  ci/report/build_local.sh
  ci/report/download_workflow_artifact.py
  ci/report/final_result.py
  ci/report/report_builder.py
  ci/roundtrip_local_to_az.py
  ci/roundtrip_local_to_c8y.py
Labels: ci/cd, theme:testing

#2664 docs: replace twitter with linkedin
  README.md
Labels: documentation

#2672 fix(apt): disable debian frontend when running apt commands
  plugins/tedge_apt_plugin/src/lib.rs
Labels: theme:software

#2673 test: use a more reliable service pid detection
  tests/RobotFramework/requirements/requirements.adapter-docker.txt
  tests/RobotFramework/requirements/requirements.adapter-local.txt
  tests/RobotFramework/requirements/requirements.adapter-ssh.txt
  tests/RobotFramework/tests/MQTT_health_check/MQTT_health_endpoints.robot
  tests/RobotFramework/tests/MQTT_health_check/health_tedge-agent.robot
  tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-aws.robot
  tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-az.robot
  tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-collectd.robot
  tests/RobotFramework/tests/MQTT_health_check/health_tedge_mapper_c8y.robot
  tests/RobotFramework/tests/configuration/lock_file.robot
  tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
Labels: theme:testing

#2676 docs: fix step6 list rendering error due to erroneous formatting
  docs/src/start/getting-started.md
Labels: documentation

#2675 docs(aws): add aws connection test details
  docs/src/operate/troubleshooting/testing-cloud-connection.md
Labels: documentation, theme:aws

#2665 Merge how-to and reference docs for c8y-firmware-plugin
  docs/src/legacy/child-device-firmware-management.md
  docs/src/legacy/firmware-management.md
Labels: documentation, theme:childdevices, theme:firmware

#2667 docs: refactor and extend software management docs
  .typos.toml
  docs/src/images/start-software-management.png
  docs/src/operate/c8y/images/software-install-1-select.png
  docs/src/operate/c8y/images/software-install-2-review.png
  docs/src/operate/c8y/images/software-install-3-apply.png
  docs/src/operate/c8y/images/software-install-4-done.png
  docs/src/operate/c8y/images/software-install-5-use-result.png
  docs/src/operate/c8y/images/software-remove-1-select.png
  docs/src/operate/c8y/images/software-remove-2-review.png
  docs/src/operate/c8y/images/software-remove-3-apply.png
  docs/src/operate/c8y/images/software-remove-4-done.png
  docs/src/operate/c8y/images/software-repo-1-list.png
  docs/src/operate/c8y/images/software-repo-2-add.png
  docs/src/operate/c8y/images/software-repo-hosted-binary.png
  docs/src/operate/c8y/images/software-self-update-1-select.png
  docs/src/operate/c8y/images/software-self-update-2-review.png
  docs/src/operate/c8y/software-management.md
Labels: documentation, theme:software

#2668 docs: update rugpi instructions to align with rugpi v0.6
  docs/src/extend/firmware-management/building-image/rugpi/tutorial.md
Labels: documentation, theme:firmware

#2674 docs(collectd): simplify instructions by using a community plugin for installation and configuration
  docs/src/operate/troubleshooting/device-monitoring.md
  docs/src/start/device-monitoring.md
  docs/src/start/getting-started.md
  docs/src/start/images/collectd-metrics.png
Labels: documentation, theme:telemetry

#2680 Fix device_registration test teardown
  tests/RobotFramework/tests/cumulocity/registration/device_registration.robot
Labels: theme:testing

#2685 docs: fix typos and grammar on rugpi image build instructions
  docs/src/extend/firmware-management/building-image/rugpi/tutorial.md
Labels: documentation, theme:firmware

#2682 Docs/clarify configuration tools
  docs/src/operate/configuration/configuration-tools.md
  docs/src/operate/configuration/index.md
  docs/src/operate/configuration/mapper-configuration.md
  docs/src/operate/configuration/mosquitto-configuration.md
  docs/src/operate/configuration/path-configuration.md
  docs/src/understand/digital-twin.md
Labels: documentation, theme:configuration, theme:cli

#2683 Replace special characters in package version
  crates/core/plugin_sm/src/plugin.rs
  crates/core/plugin_sm/tests/plugin.rs
  tests/RobotFramework/tests/plugin_apt/build.sh
  tests/RobotFramework/tests/plugin_apt/filter_packages_list_output.robot
  tests/RobotFramework/tests/plugin_apt/install_overwrite_config_files.robot
  tests/RobotFramework/tests/plugin_apt/install_package_with_epoch.robot
  tests/RobotFramework/tests/plugin_apt/nfpm-package-with-epoch.yaml
  tests/RobotFramework/tests/plugin_apt/nfpm-version1.yaml
  tests/RobotFramework/tests/plugin_apt/nfpm-version2.yaml
  tests/RobotFramework/tests/plugin_apt/package-with-epoch_1.2.3_all.deb
  tests/RobotFramework/tests/plugin_apt/sampledeb_1.0.0_all.deb
  tests/RobotFramework/tests/plugin_apt/sampledeb_2.0.0_all.deb
  tests/images/debian-systemd/files/tedge.toml
Labels: theme:software

#2691 docs: fix broken anchor to rugpi instructions
  docs/src/extend/firmware-management/building-image/rugpi/tutorial.md
  docs/src/extend/firmware-management/device-onboarding.md
Labels: documentation

#2699 ci: combine the build and integration-tests workflow
  .github/workflows/build-workflow.yml
  .github/workflows/integration-tests.yml
Labels: ci/cd

#2701 ci: don't build on main as merge_group already builds/publishes
  .github/workflows/build-workflow.yml
Labels: ci/cd

#2703 docs: remove integration test badge
  README.md
Labels: documentation, ci/cd

#2702 ci: improve release workflow
  .github/workflows/autotag.yml
  .github/workflows/build-workflow.yml
  .github/workflows/hosted-post-merge_version_update.yml
Labels: ci/cd

#2708 ci: correct pull request event name
  .github/workflows/build-workflow.yml
Labels: ci/cd

#2710 ci: fix checkout reference when on a PR
  .github/workflows/build-workflow.yml
Labels: ci/cd

#2705 ci: promote cloudsmith artifacts on tags
  .github/workflows/build-workflow.yml
  ci/admin/cloudsmith_admin.sh
  ci/build_scripts/build.sh
  ci/build_scripts/version.sh
Labels: ci/cd

#2711 ci: rename version bump workflow to release
  .github/workflows/release.yml
Labels: ci/cd

#2712 fix: disable memory logging by default to avoid log spamming
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
Labels: theme:troubleshooting

#2714 ci: switch gha to install just to avoid nodejs 16 deprecation warnings
  .github/workflows/build-workflow.yml
  .github/workflows/gh-pages.yml
Labels: ci/cd

#2720 ci: add git user name and email before creating tag
  .github/workflows/autotag.yml
Labels: ci/cd

#2722 ci: correct conditional publishing logic which resulted in job being skipped
  .github/workflows/build-workflow.yml
Labels: ci/cd

#2723 ci: fix job conditionals on publish and publish-containers
  .github/workflows/build-workflow.yml
Labels: ci/cd

#2726 ci: remove unsupported cloudsmith flag on promotion task
  ci/admin/cloudsmith_admin.sh
Labels: ci/cd

#2736 docs(mapper): remove out of date and unused section
  docs/src/understand/tedge-mapper.md
Labels: documentation, theme:mqtt

#2738 feat(logs): only enable ansi colors in logs when stderr is a terminal
  crates/common/tedge_config/src/system_services/log_config.rs
Labels: theme:troubleshooting
