Repository thin-edge/thin-edge.io, pull requests merged in 2024-03, with the labels that each got.

#2752 tests: use posix shell over bash for improved cross platform compatibility
  crates/extensions/c8y_mapper_ext/src/tests.rs
Labels: theme:testing

#2751 refactor: use generic RecommendedWatcher type over platform specific type
  crates/common/tedge_utils/src/notify.rs
Labels: refactoring

#2759 chore: update whoami to fix RUSTSEC-2024-0020
  Cargo.lock
  Cargo.toml
Labels: dependencies, theme:security

#2756 tests: move import into test which is only run on linux targets
  crates/common/download/src/download.rs
Labels: refactoring, theme:testing

#2764 tests: remove git lfs dependency by using official thin-edge.io packages
  .gitattributes
  tests/RobotFramework/bin/setup.sh
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge-agent_0.0.1_amd64.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge-agent_0.0.1_arm64.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge-agent_0.0.1_armhf.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge-agent_0.0.1_armv6.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge-apt-plugin_0.0.1_amd64.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge-apt-plugin_0.0.1_arm64.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge-apt-plugin_0.0.1_armhf.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge-apt-plugin_0.0.1_armv6.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge-mapper_0.0.1_amd64.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge-mapper_0.0.1_arm64.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge-mapper_0.0.1_armhf.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge-mapper_0.0.1_armv6.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge-watchdog_0.0.1_amd64.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge-watchdog_0.0.1_arm64.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge-watchdog_0.0.1_armhf.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge-watchdog_0.0.1_armv6.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge_0.0.1_amd64.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge_0.0.1_arm64.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge_0.0.1_armhf.deb
  tests/RobotFramework/tests/cumulocity/self-update/base-version/tedge_0.0.1_armv6.deb
  tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
Labels: theme:testing

#2765 docs(yocto): add missing build dependency `file`
  docs/src/extend/firmware-management/building-image/yocto/tutorial.md
Labels: documentation, theme:firmware

#2741 feat: compile on macos
  ci/build_scripts/build.sh
  ci/build_scripts/package.sh
  ci/build_scripts/publish_packages.sh
  crates/common/logged_command/src/logged_command.rs
  crates/common/tedge_utils/src/file.rs
  crates/common/tedge_utils/src/notify.rs
  crates/extensions/tedge_file_system_ext/src/lib.rs
  plugins/tedge_apt_plugin/src/lib.rs
Labels: theme:packaging, theme:developer-exp

#2755 docs: Document commands to de-register entities #2700
  docs/src/operate/registration/deregister.md
  docs/src/operate/registration/index.md
Labels: documentation, theme:registration

#2777 build: fix building of virtual packages
  ci/build_scripts/package.sh
Labels: ci/cd, theme:packaging

#2716 Add support for built-in bridge to tedge-mapper-c8y
  Cargo.lock
  Cargo.toml
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/c8y_api/src/http_proxy.rs
  crates/core/c8y_api/src/json_c8y_deserializer.rs
  crates/core/c8y_api/src/smartrest/inventory.rs
  crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
  crates/core/c8y_api/src/smartrest/topic.rs
  crates/core/c8y_api/src/utils.rs
  crates/core/tedge/src/bridge/aws.rs
  crates/core/tedge/src/bridge/azure.rs
  crates/core/tedge/src/bridge/c8y.rs
  crates/core/tedge/src/bridge/config.rs
  crates/core/tedge/src/bridge/mod.rs
  crates/core/tedge/src/cli/certificate/create.rs
  crates/core/tedge/src/cli/config/commands/list.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/cli/connect/jwt_token.rs
  crates/core/tedge_api/src/alarm.rs
  crates/core/tedge_api/src/health.rs
  crates/core/tedge_api/src/lib.rs
  crates/core/tedge_mapper/Cargo.toml
  crates/core/tedge_mapper/src/c8y/mapper.rs
  crates/extensions/c8y_firmware_manager/src/config.rs
  crates/extensions/c8y_firmware_manager/src/lib.rs
  crates/extensions/c8y_firmware_manager/src/tests.rs
  crates/extensions/c8y_firmware_manager/src/worker.rs
  crates/extensions/c8y_http_proxy/src/credentials.rs
  crates/extensions/c8y_mapper_ext/src/actor.rs
  crates/extensions/c8y_mapper_ext/src/alarm_converter.rs
  crates/extensions/c8y_mapper_ext/src/config.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/inventory.rs
  crates/extensions/c8y_mapper_ext/src/operations/config_snapshot.rs
  crates/extensions/c8y_mapper_ext/src/operations/config_update.rs
  crates/extensions/c8y_mapper_ext/src/operations/firmware_update.rs
  crates/extensions/c8y_mapper_ext/src/operations/log_upload.rs
  crates/extensions/c8y_mapper_ext/src/service_monitor.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  crates/extensions/tedge_mqtt_bridge/Cargo.toml
  crates/extensions/tedge_mqtt_bridge/src/lib.rs
  plugins/c8y_firmware_plugin/src/lib.rs
  tests/RobotFramework/tests/cumulocity/shell/shell_operation_built-in_bridge.robot
  tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry_built-in_bridge.robot
Labels: theme:mqtt, theme:c8y

#2775 feat(containers): Draft Kubernetes deployment of tedge
  .gitignore
  kubernetes/README.md
  kubernetes/tedge/.helmignore
  kubernetes/tedge/Chart.yaml
  kubernetes/tedge/templates/_helpers.tpl
  kubernetes/tedge/templates/mosquitto-config.yaml
  kubernetes/tedge/templates/mosquitto.yaml
  kubernetes/tedge/templates/tedge-agent.yaml
  kubernetes/tedge/templates/tedge-pv.yaml
  kubernetes/tedge/templates/tests/test-connection.yaml
  kubernetes/tedge/values.yaml
Labels: theme:containers, theme:packaging

#2788 style: fix Rust doc typo
  crates/extensions/tedge_mqtt_bridge/src/lib.rs
Labels: documentation

#2774 Add deregister test steps to register testcase
  tests/RobotFramework/tests/cumulocity/registration/registration_lifecycle.robot
Labels: theme:testing

#2789 fix: Honor c8y.mqtt setting on tedge connect
  crates/common/tedge_config/src/tedge_config_cli/error.rs
  crates/common/tedge_config/src/tedge_config_cli/models/host_port.rs
  crates/common/tedge_config/src/tedge_config_cli/models/port.rs
  crates/core/c8y_api/src/http_proxy.rs
  crates/core/tedge/src/bridge/aws.rs
  crates/core/tedge/src/bridge/azure.rs
  crates/core/tedge/src/bridge/c8y.rs
  crates/core/tedge/src/bridge/config.rs
  crates/core/tedge/src/cli/certificate/upload.rs
  crates/core/tedge/src/cli/connect/c8y_direct_connection.rs
  crates/core/tedge/src/cli/connect/command.rs
  tests/RobotFramework/README.md
Labels: theme:mqtt, theme:c8y
