Repository thin-edge/thin-edge.io, pull requests merged in 2024-05, with the labels that each got.

#2855 Update doc: Troubleshooting > Monitoring Service Health
  docs/src/operate/troubleshooting/monitoring-service-health.md
Labels: documentation

#2843 feat: create bridge configuration in offline mode
  crates/core/tedge/src/cli/connect/cli.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/cli/reconnect/command.rs
  docs/src/references/cli/tedge-connect.md
  docs/src/start/connect-aws.md
  docs/src/start/connect-azure.md
  docs/src/start/connect-c8y.md
  tests/RobotFramework/tests/tedge_connect/tedge_connect_offline.robot
Labels: theme:cli

#2865 fix(cli): ignore port when comparing cloud urls
  crates/core/tedge/src/cli/connect/command.rs
  tests/RobotFramework/tests/tedge_connect/tedge_connect_test.robot
Labels: bug, theme:cli

#2871 test: update to robotframework 7.0
  tests/RobotFramework/requirements/requirements.adapter-docker.txt
  tests/RobotFramework/requirements/requirements.adapter-local.txt
  tests/RobotFramework/requirements/requirements.adapter-ssh.txt
  tests/RobotFramework/requirements/requirements.dev.txt
  tests/RobotFramework/requirements/requirements.txt
  tests/RobotFramework/tests/cumulocity/benchmarks/benchmarks.robot
  tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device.robot
  tests/RobotFramework/tests/cumulocity/monitoring/monitor_device_collectd.robot
  tests/RobotFramework/tests/cumulocity/telemetry/raise_alarms.robot
  tests/RobotFramework/tests/customizing/data_path_config.robot
  tests/RobotFramework/tests/mqtt/basic_pub_sub.robot
  tests/RobotFramework/tests/mqtt/remote_mqtt_broker.robot
  tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
  tests/RobotFramework/tests/tedge/http_file_transfer_api.robot
  tests/RobotFramework/tests/tedge/tedge_config_get.robot
  tests/RobotFramework/tests/tedge_agent/tedge_agent.robot
  tests/RobotFramework/tests/tedge_agent/workflows/custom_operation.robot
Labels: theme:testing

#2883 feat(packaging): remove adduser debian dependency declaration
  configuration/package_manifests/nfpm.tedge.yaml
Labels: theme:packaging

#2888 fix(remote-access): spawn process using current process path and config dir
  plugins/c8y_remote_access_plugin/src/lib.rs
Labels: theme:troubleshooting

#2905 feat(sm-plugin): skip package download if the url is empty
  crates/common/download/src/download.rs
  crates/core/tedge_api/src/commands.rs
  crates/core/tedge_api/src/software.rs
  tests/RobotFramework/tests/cumulocity/software_management/software.robot
Labels: theme:software

#2909 ci: add explicit dependency on build job
  .github/workflows/build-workflow.yml
Labels: ci/cd

#2910 ci: validate build jobs
  .github/workflows/build-workflow.yml
Labels: ci/cd
