Repository thin-edge/thin-edge.io, pull requests merged in 2024-06, with the labels that each got.

#2913 Cleanup unused code and fix doc related to SmartREST 104
  crates/core/c8y_api/src/smartrest/inventory.rs
  crates/extensions/c8y_mapper_ext/src/service_monitor.rs
  docs/src/operate/c8y/health-monitoring.md
Labels: documentation

#2915 feat: Add reconnection backoff to built-in bridge
  Cargo.lock
  Cargo.toml
  crates/common/tedge_config/Cargo.toml
  crates/common/tedge_config/src/tedge_config_cli/models/seconds.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/common/tedge_config_macros/impl/src/input/parse.rs
  crates/common/tedge_config_macros/impl/src/lib.rs
  crates/common/tedge_config_macros/impl/src/query.rs
  crates/common/tedge_config_macros/impl/src/reader.rs
  crates/core/tedge/src/cli/config/commands/list.rs
  crates/extensions/tedge_mqtt_bridge/Cargo.toml
  crates/extensions/tedge_mqtt_bridge/src/backoff.rs
  crates/extensions/tedge_mqtt_bridge/src/lib.rs
  crates/extensions/tedge_mqtt_bridge/src/topics.rs
  crates/extensions/tedge_mqtt_bridge/tests/bridge.rs
  tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
Labels: theme:mqtt

#2926 ci: auto generate changelog
  .github/workflows/build-workflow.yml
  .gitignore
  ci/changelog/changelog.sh
  cliff.toml
  docs/internal/RELEASE.md
  justfile
Labels: ci/cd

#2930 test(system): fix regex escaping in doc string
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
Labels: theme:testing

#2931 test(system): update c8y system test lib to improve retry logging
  tests/RobotFramework/requirements/requirements.txt
Labels: theme:testing

#2934 docs: update internal release process
  docs/internal/RELEASE.md
Labels: documentation

#2925 refactor: c8y mapper republishes metadata message with `@id`
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  tests/RobotFramework/tests/cumulocity/registration/registration_lifecycle.robot
Labels: refactoring

#2936 fix: Ensure the MQTT connection is properly closed
  Cargo.lock
  crates/common/tedge_config_macros/impl/src/input/parse.rs
  crates/core/tedge/Cargo.toml
  crates/core/tedge/src/cli/disconnect/cli.rs
  crates/core/tedge/src/cli/disconnect/disconnect_bridge.rs
  crates/core/tedge/src/cli/mqtt/cli.rs
  crates/core/tedge/src/cli/mqtt/mod.rs
  crates/core/tedge/src/cli/mqtt/publish.rs
  crates/core/tedge/src/cli/mqtt/subscribe.rs
  crates/core/tedge/src/cli/reconnect/cli.rs
  crates/core/tedge/src/cli/reconnect/command.rs
Labels: theme:mqtt, theme:cli

#2942 fix: improve compatibility of user/group existence check in package maintainer scripts
  configuration/package_scripts/_generated/tedge/apk/postrm
  configuration/package_scripts/_generated/tedge/apk/preinst
  configuration/package_scripts/_generated/tedge/deb/postrm
  configuration/package_scripts/_generated/tedge/deb/preinst
  configuration/package_scripts/_generated/tedge/rpm/postrm
  configuration/package_scripts/_generated/tedge/rpm/preinst
  configuration/package_scripts/tedge/postrm
  configuration/package_scripts/tedge/preinst
Labels: bug, theme:packaging

#2946 fix: Remove unwanted host header before forwarding request to Cumulocity
  crates/extensions/c8y_auth_proxy/src/server.rs
Labels: theme:c8y

#2950 fix: tedge mqtt ignoring ctrl-c when connection fails
  crates/core/tedge/src/cli/mqtt/mod.rs
  crates/core/tedge/src/cli/mqtt/subscribe.rs
Labels: theme:mqtt, theme:cli

#2952 feat: use loopback ip address instead of alias to improve compatibility
  configuration/contrib/collectd/collectd.conf
  crates/common/axum_tls/test_data/_regenerate_certs.sh
  crates/common/mqtt_channel/src/config.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/common/tedge_config_macros/examples/macro.rs
  crates/core/tedge/src/bridge/common_mosquitto_config.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/tedge_mqtt_bridge/src/config.rs
  crates/extensions/tedge_mqtt_bridge/tests/bridge.rs
  crates/tests/mqtt_tests/src/test_mqtt_client.rs
  crates/tests/mqtt_tests/src/test_mqtt_server.rs
  tests/RobotFramework/tests/cumulocity/configuration/generate_certificates.sh
  tests/RobotFramework/tests/mqtt/gen_certs.sh
  tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
  tests/images/debian-systemd/files/bootstrap.sh
Labels: theme:configuration

#2955 docs: change config management permissions in the example
  docs/src/operate/c8y/configuration-management.md
Labels: theme:configuration

#2957 feat: add path and method used to HTTP error messages to improve debugability
  crates/extensions/c8y_http_proxy/src/actor.rs
  crates/extensions/tedge_http_ext/src/actor.rs
  crates/extensions/tedge_http_ext/src/messages.rs
  crates/extensions/tedge_http_ext/src/test_helpers.rs
Labels: theme:troubleshooting

#2956 test: use more robust http parsing in the c8y-proxy host header tests
  Cargo.lock
  Cargo.toml
  crates/extensions/c8y_auth_proxy/Cargo.toml
  crates/extensions/c8y_auth_proxy/src/server.rs
Labels: theme:c8y

#2958 fix: use octal format for file permission in generated example file
  crates/extensions/tedge_config_manager/src/lib.rs
  crates/extensions/tedge_config_manager/src/tests.rs
Labels: theme:configuration

#2965 chore: bump MSRV in the workflow to 1.78
  .github/workflows/build-workflow.yml
Labels: rust

#2962 docs: fix broken links in markdown files
  CODING_GUIDELINES.md
  CONTRIBUTING.md
  docs/internal/RELEASE.md
  docs/src/extend/software-management.md
  docs/src/operate/c8y/apama.md
  docs/src/start/device-monitoring.md
  tests/RobotFramework/README.md
Labels: documentation
