Repository thin-edge/thin-edge.io, pull requests merged in 2024-10, with the labels that each got.

#3150 fix: check if log exists before trying to upload it
  crates/extensions/c8y_mapper_ext/src/operations/upload.rs
Labels: theme:troubleshooting, theme:c8y

#3152 feat: add tedge-apt-plugin as recommended dependency of tedge-agent
  configuration/package_manifests/nfpm.tedge-agent.yaml
Labels: theme:packaging

#3151 fix: add mosquitto as a weak dependency to tedge
  configuration/package_manifests/nfpm.tedge.yaml
  configuration/package_manifests/virtual/nfpm.tedge-full.yaml
  configuration/package_manifests/virtual/nfpm.tedge-minimal.yaml
Labels: theme:packaging

#3144 feat: allow operation handlers to match on json payloads
  crates/core/c8y_api/src/smartrest/operations.rs
  crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/error.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/c8y_Command_1
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/c8y_Command_2
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/command_handler.sh
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/custom_operation_command.robot
Labels: theme:c8y

#3164 docs: add missing variable available in workflow states
  docs/src/references/agent/operation-workflow.md
Labels: documentation, theme:workflows

#3161 refactor: reorder crates/core/c8y_api/src/smartrest/operation.rs
  crates/core/c8y_api/src/smartrest/operations.rs
Labels: refactoring

#3126 refactor: add support to `define_tedge_config` for (optionally) multi-value fields
  Cargo.lock
  Cargo.toml
  crates/common/axum_tls/src/config.rs
  crates/common/tedge_config/src/tedge_config_cli/figment.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/common/tedge_config_macros/Cargo.toml
  crates/common/tedge_config_macros/examples/macro.rs
  crates/common/tedge_config_macros/examples/multi.rs
  crates/common/tedge_config_macros/examples/renaming_keys.rs
  crates/common/tedge_config_macros/impl/Cargo.toml
  crates/common/tedge_config_macros/impl/src/dto.rs
  crates/common/tedge_config_macros/impl/src/input/parse.rs
  crates/common/tedge_config_macros/impl/src/input/validate.rs
  crates/common/tedge_config_macros/impl/src/lib.rs
  crates/common/tedge_config_macros/impl/src/namegen.rs
  crates/common/tedge_config_macros/impl/src/query.rs
  crates/common/tedge_config_macros/impl/src/reader.rs
  crates/common/tedge_config_macros/src/all_or_nothing.rs
  crates/common/tedge_config_macros/src/lib.rs
  crates/common/tedge_config_macros/src/multi.rs
  crates/common/tedge_config_macros/src/option.rs
  crates/common/tedge_config_macros/tests/arc.rs
  crates/common/tedge_config_macros/tests/optional.rs
  crates/core/tedge/src/cli/config/commands/add.rs
  crates/core/tedge/src/cli/config/commands/get.rs
  crates/core/tedge/src/cli/config/commands/list.rs
  crates/core/tedge/src/cli/config/commands/remove.rs
  crates/core/tedge/src/cli/config/commands/set.rs
  crates/core/tedge/src/cli/config/commands/unset.rs
  crates/core/tedge/src/command.rs
  crates/core/tedge_agent/src/file_transfer_server/actor.rs
Labels: theme:configuration, theme:c8y

#3167 test: add bridge health status keywords
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
  tests/RobotFramework/tests/aws/aws_provisioning_jitp.robot
  tests/RobotFramework/tests/aws/aws_server_certificates.robot
Labels: theme:testing

#3168 chore: fix typos
  crates/common/tedge_config_macros/impl/src/reader.rs
  crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
Labels: refactoring, skip-release-notes

#3169 test: format robotframework system tests
  tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/custom_operation_command.robot
  tests/RobotFramework/tests/cumulocity/firmware/firmware_operation.robot
Labels: theme:testing

#3172 dev: update packages in dev container image
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  ci/build_scripts/build.sh
Labels: theme:developer-exp

#3175 build: add support for building against specific gnu libc versions
  ci/build_scripts/build.sh
Labels: theme:developer-exp

#3176 ci: fail on detection of typos in PR check
  .github/workflows/pull-request-checks.yml
Labels: ci/cd

#3177 ci: run format checks on entire code base including Robotframework tests
  .github/workflows/pull-request-checks.yml
Labels: ci/cd

#3181 docs: add notes to firmware on-boarding instructions
  docs/src/extend/firmware-management/device-onboarding.md
Labels: documentation, theme:firmware

#3182 fix: target incompatibility with armv6 package for raspberry pi
  .github/workflows/build-workflow.yml
  ci/build_scripts/build.sh
  ci/build_scripts/detect_target.sh
  ci/build_scripts/package.sh
  ci/build_scripts/publish_packages.sh
  containers/tedge/Dockerfile
Labels: theme:packaging

#3184 chore: replace company references to Cumulocity GmbH
  CONTRIBUTING.md
  CONTRIBUTOR-LICENSE-AGREEMENT.md
  GOVERNANCE.md
  docs/src/operate/security/device-certificate.md
  docs/src/start/getting-started.md
Labels: documentation, skip-release-notes

#3188 fix: remove duplicate subscription in c8y built-in bridge
  crates/core/tedge_mapper/src/c8y/mapper.rs
Labels: theme:c8y, theme:bridge

#3174 feat: add profile support to tedge-mapper
  Cargo.lock
  crates/common/tedge_config/Cargo.toml
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/common/tedge_config_macros/Cargo.toml
  crates/common/tedge_config_macros/examples/multi.rs
  crates/common/tedge_config_macros/impl/src/query.rs
  crates/common/tedge_config_macros/src/multi.rs
  crates/core/c8y_api/src/http_proxy.rs
  crates/core/tedge/src/bridge/aws.rs
  crates/core/tedge/src/bridge/azure.rs
  crates/core/tedge/src/bridge/c8y.rs
  crates/core/tedge/src/bridge/config.rs
  crates/core/tedge/src/bridge/mod.rs
  crates/core/tedge/src/cli/certificate/cli.rs
  crates/core/tedge/src/cli/common.rs
  crates/core/tedge/src/cli/connect/cli.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/cli/connect/error.rs
  crates/core/tedge/src/cli/connect/jwt_token.rs
  crates/core/tedge/src/cli/disconnect/cli.rs
  crates/core/tedge/src/cli/disconnect/disconnect_bridge.rs
  crates/core/tedge/src/cli/reconnect/cli.rs
  crates/core/tedge/src/cli/reconnect/command.rs
  crates/core/tedge/src/cli/refresh_bridges.rs
  crates/core/tedge/src/error.rs
  crates/core/tedge_mapper/src/aws/mapper.rs
  crates/core/tedge_mapper/src/az/mapper.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
  crates/core/tedge_mapper/src/lib.rs
  crates/extensions/c8y_auth_proxy/src/actor.rs
  crates/extensions/c8y_auth_proxy/src/url.rs
  crates/extensions/c8y_firmware_manager/src/config.rs
  crates/extensions/c8y_firmware_manager/src/error.rs
  crates/extensions/c8y_http_proxy/src/lib.rs
  crates/extensions/c8y_mapper_ext/src/availability/mod.rs
  crates/extensions/c8y_mapper_ext/src/config.rs
  plugins/c8y_firmware_plugin/src/lib.rs
  plugins/c8y_remote_access_plugin/src/auth.rs
  plugins/c8y_remote_access_plugin/src/input.rs
  plugins/c8y_remote_access_plugin/src/lib.rs
  tests/RobotFramework/tests/cumulocity/availability/heartbeat.robot
Labels: theme:c8y

#3179 fix: Trim `reason` field in "succeed custom operation" smartrest message
  crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
  tests/RobotFramework/tests/cumulocity/shell/shell_operation.robot
Labels: theme:mqtt, theme:c8y

#3195 chore: Fix Rust 1.82 clippy lints
  crates/common/batcher/src/batchable.rs
  crates/common/flockfile/src/unix.rs
  crates/common/mqtt_channel/src/messages.rs
  crates/common/tedge_utils/src/timestamp.rs
  crates/common/upload/src/upload.rs
  crates/core/c8y_api/src/smartrest/inventory.rs
  crates/core/c8y_api/src/smartrest/operations.rs
  crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
  crates/core/tedge/src/bridge/config.rs
  crates/core/tedge_actors/src/examples/mod.rs
  crates/core/tedge_actors/src/servers/mod.rs
  crates/core/tedge_api/src/entity_store.rs
  crates/core/tedge_api/src/measurement/parser.rs
  crates/core/tedge_write/src/api.rs
  crates/extensions/c8y_mapper_ext/src/operations/handler.rs
Labels: refactoring, ci/cd

#3187 test: check publishing of telemetry data whilst mapper is down
  tests/RobotFramework/tests/mqtt/offline_publishing.robot
  tests/images/debian-systemd/debian-systemd.dockerfile
Labels: theme:mqtt, theme:testing

#3194 docs: add required ports information for cloud connections
  docs/src/references/supported-platforms.md
  docs/src/start/getting-started.md
Labels: documentation

#3193 docs: add tedge-watchdog decision page
  design/decisions/0005-tedge-watchdog.md
Labels: documentation

#3180 feat: support reloading workflows at runtime
  crates/core/tedge_agent/src/agent.rs
  crates/core/tedge_agent/src/operation_workflows/actor.rs
  crates/core/tedge_agent/src/operation_workflows/builder.rs
  crates/core/tedge_agent/src/operation_workflows/config.rs
  crates/core/tedge_agent/src/operation_workflows/message_box.rs
  crates/core/tedge_agent/src/operation_workflows/mod.rs
  crates/core/tedge_agent/src/operation_workflows/persist.rs
  crates/core/tedge_agent/src/operation_workflows/tests.rs
  crates/core/tedge_agent/src/state_repository/state.rs
  crates/core/tedge_api/src/workflow/error.rs
  crates/core/tedge_api/src/workflow/mod.rs
  crates/core/tedge_api/src/workflow/state.rs
  crates/core/tedge_api/src/workflow/supervisor.rs
  tests/RobotFramework/tests/tedge_agent/workflows/download-command-expected.log
  tests/RobotFramework/tests/tedge_agent/workflows/dynamic_workflow_reloading.robot
  tests/RobotFramework/tests/tedge_agent/workflows/gp-command-expected.log
  tests/RobotFramework/tests/tedge_agent/workflows/long-running-command-v1.toml
  tests/RobotFramework/tests/tedge_agent/workflows/long-running-command-v2.toml
  tests/RobotFramework/tests/tedge_agent/workflows/long-running-command-v3.toml
  tests/RobotFramework/tests/tedge_agent/workflows/sleep.toml
  tests/RobotFramework/tests/tedge_agent/workflows/super-command-expected.log
  tests/RobotFramework/tests/tedge_agent/workflows/update-user-command.toml
  tests/RobotFramework/tests/tedge_agent/workflows/user-command-v1.toml
  tests/RobotFramework/tests/tedge_agent/workflows/user-command-v2.toml
Labels: theme:workflows

#3138 test: Create a tedge-watchdog test suite
  crates/core/tedge_watchdog/src/systemd_watchdog.rs
  tests/RobotFramework/tests/tedge_watchdog/health_check_respond.sh
  tests/RobotFramework/tests/tedge_watchdog/tedge-agent.service
  tests/RobotFramework/tests/tedge_watchdog/tedge_watchdog.robot
Labels: theme:monitoring, theme:testing

#3191 Improve validation of SmartREST payloads
  crates/core/c8y_api/Cargo.toml
  crates/core/c8y_api/src/smartrest/alarm.rs
  crates/core/c8y_api/src/smartrest/csv.rs
  crates/core/c8y_api/src/smartrest/inventory.rs
  crates/core/c8y_api/src/smartrest/mod.rs
  crates/core/c8y_api/src/smartrest/operations.rs
  crates/core/c8y_api/src/smartrest/payload.rs
  crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
  crates/extensions/c8y_mapper_ext/src/alarm_converter.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/mod.rs
Labels: theme:mqtt, theme:c8y

#3204 fix: C8Y custom operation script parameters
  crates/core/tedge_api/src/lib.rs
  crates/core/tedge_api/src/script.rs
  crates/core/tedge_api/src/substitution.rs
  crates/core/tedge_api/src/workflow/handlers.rs
  crates/core/tedge_api/src/workflow/log/logged_command.rs
  crates/core/tedge_api/src/workflow/mod.rs
  crates/core/tedge_api/src/workflow/state.rs
  crates/core/tedge_api/src/workflow/toml_config.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/c8y_Command_3
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/custom_operation_command.robot
Labels: theme:c8y

#3209 fix: agent stops processing ill-formed software_update command payloads
  crates/core/tedge_api/src/commands.rs
  tests/RobotFramework/tests/cumulocity/software_management/software.robot
Labels: bug, theme:software

#3208 Make `--debug` flag override `RUST_LOG`
  Cargo.lock
  crates/common/tedge_config/Cargo.toml
  crates/common/tedge_config/src/system_services/log_config.rs
  crates/core/tedge_agent/src/lib.rs
  crates/core/tedge_mapper/src/lib.rs
  crates/core/tedge_watchdog/src/lib.rs
  crates/extensions/c8y_mapper_ext/src/operations/handler.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  plugins/c8y_firmware_plugin/src/lib.rs
Labels: theme:troubleshooting, theme:cli

#3189 feat: support user topics when handling custom operation
  crates/common/mqtt_channel/src/topics.rs
  crates/core/c8y_api/src/smartrest/error.rs
  crates/core/c8y_api/src/smartrest/operations.rs
  crates/extensions/c8y_mapper_ext/src/config.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/inventory.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/c8y_Command_4
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/custom_operation_command.robot
  tests/RobotFramework/tests/cumulocity/shell/c8y_Command
Labels: theme:c8y

#3214 Group workspace crates first in top-level Cargo.toml and deduplicate yansi and toml dependencies
  Cargo.lock
  Cargo.toml
  crates/common/axum_tls/src/config.rs
  crates/core/tedge/src/cli/config/commands/list.rs
Labels: dependencies

#3196 feat: support SmartREST1.0 for Cumulocity
  Cargo.lock
  crates/common/certificate/src/parse_root_certificate.rs
  crates/common/tedge_config/src/tedge_config_cli/models/auth_method.rs
  crates/common/tedge_config/src/tedge_config_cli/models/mod.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/c8y_api/Cargo.toml
  crates/core/c8y_api/src/http_proxy.rs
  crates/core/tedge/Cargo.toml
  crates/core/tedge/src/bridge/aws.rs
  crates/core/tedge/src/bridge/azure.rs
  crates/core/tedge/src/bridge/c8y.rs
  crates/core/tedge/src/bridge/config.rs
  crates/core/tedge/src/cli/connect/c8y_direct_connection.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/error.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
  crates/extensions/c8y_http_proxy/src/credentials.rs
  crates/extensions/tedge_mqtt_bridge/src/config.rs
  plugins/c8y_firmware_plugin/Cargo.toml
  plugins/c8y_firmware_plugin/src/lib.rs
  plugins/c8y_remote_access_plugin/src/auth.rs
  plugins/c8y_remote_access_plugin/src/lib.rs
  plugins/c8y_remote_access_plugin/src/proxy.rs
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
  tests/RobotFramework/resources/common.resource
  tests/RobotFramework/tests/cumulocity/smartrest_one/README.md
  tests/RobotFramework/tests/cumulocity/smartrest_one/smartrest_one.robot
Labels: theme:c8y

#3201 fix: Subscribe to C8Y topics using QoS 1
  crates/core/tedge/src/bridge/c8y.rs
Labels: theme:c8y, theme:bridge

#3217 Attach topic to c8y message conversion error
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/error.rs
Labels: improvement, theme:troubleshooting
