Repository thin-edge/thin-edge.io, pull requests merged in 2025-10, with the labels that each got.

#3804 fix: proxy port parsing issue when using port 80
  crates/common/tedge_config/src/tedge_toml/models/proxy_url.rs
Labels: theme:connectivity

#3802 refactor: Improve error reporting on sudo execution error
  crates/common/tedge_config/src/lib.rs
  crates/common/tedge_config/src/sudo.rs
  crates/core/plugin_sm/src/plugin.rs
  crates/core/plugin_sm/src/plugin_manager.rs
  crates/extensions/tedge_log_manager/src/plugin_manager.rs
  tests/RobotFramework/requirements/requirements.adapter-docker.txt
  tests/RobotFramework/requirements/requirements.adapter-local.txt
  tests/RobotFramework/requirements/requirements.adapter-ssh.txt
  tests/RobotFramework/tests/cumulocity/log/log_operation_plugins.robot
Labels: theme:plugins

#3806 feat: add journald log plugin
  configuration/contrib/log-plugins/journald
  configuration/package_manifests/nfpm.tedge.yaml
  tests/RobotFramework/tests/cumulocity/log/log_operation_plugins.robot
  tests/RobotFramework/tests/cumulocity/log/plugins/journald
Labels: theme:troubleshooting
