Repository thin-edge/thin-edge.io, pull requests merged in 2025-07, with the labels that each got.

#3677 feat: `tedge cert renew c8y` using HSM
  crates/common/certificate/src/lib.rs
  crates/common/certificate/src/parse_root_certificate/mod.rs
  crates/common/tedge_config/src/tedge_toml/tedge_config/mqtt_config.rs
  crates/core/tedge/src/cli/certificate/c8y/download.rs
  crates/core/tedge/src/cli/certificate/c8y/mod.rs
  crates/core/tedge/src/cli/certificate/c8y/renew.rs
  crates/core/tedge/src/cli/certificate/cli.rs
  crates/core/tedge/src/cli/certificate/create.rs
  crates/core/tedge/src/cli/certificate/create_csr.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/main.rs
  crates/extensions/tedge-p11-server/src/pkcs11/mod.rs
  crates/extensions/tedge-p11-server/src/service.rs
  crates/extensions/tedge-p11-server/src/signer.rs
  tests/RobotFramework/tests/pkcs11/private_key_storage.robot
Labels: theme:hsm

#3720 chore: fix clippy warnings
  crates/extensions/tedge_mqtt_ext/src/trie.rs
Labels: refactoring, skip-release-notes

#3728 fix: continue to de-duplicate incoming operations once operation is complete
  crates/extensions/c8y_mapper_ext/src/converter.rs
Labels: theme:c8y

#3727 refactor: Revert "disable problematic tests to allow the CI changes to be merged"
  crates/extensions/tedge_downloader_ext/src/tests.rs
Labels: ci/cd

#3718 feat: create parent directories if missing for config_update operation
  crates/common/tedge_utils/src/atomic.rs
  crates/common/tedge_utils/src/file.rs
  crates/core/tedge_write/src/api.rs
  crates/core/tedge_write/src/bin.rs
  crates/core/tedge_write/src/lib.rs
  crates/extensions/tedge_config_manager/src/actor.rs
  crates/extensions/tedge_config_manager/src/config.rs
  docs/src/operate/c8y/configuration-management.md
  docs/src/references/agent/tedge-configuration-management.md
  tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
  tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot
  tests/RobotFramework/tests/cumulocity/configuration/tedge-configuration-plugin.toml
Labels: theme:configuration

#3735 chore: bump MSRV to 1.85
  Cargo.toml
  ci/build_scripts/build.sh
  crates/common/tedge_config_macros/impl/src/query.rs
  crates/core/tedge_agent/src/entity_manager/tests.rs
  crates/core/tedge_api/src/entity_store.rs
  crates/extensions/tedge_mqtt_bridge/tests/bridge.rs
  crates/extensions/tedge_mqtt_bridge/tests/test_broker/mod.rs
  docs/src/contribute/build.md
Labels: ci/cd

#3743 refactor: ensure gost has started before running related tests
  tests/images/debian-systemd/files/gost-http-proxy.service
Labels: theme:testing

#3745 ci: update to ubuntu-24.04 runner
  .github/workflows/build-workflow.yml
  .github/workflows/pull-request-checks.yml
  .github/workflows/release.yml
Labels: ci/cd

#3744 fix: de-duplicate custom operations on c8y/devicecontrol/notifications
  crates/extensions/c8y_mapper_ext/src/converter.rs
Labels: theme:c8y

#3742 fix: do not overwrite latest twin data from inventory.json values on mapper restart
  crates/core/tedge_agent/src/agent.rs
  crates/core/tedge_agent/src/entity_manager/server.rs
  crates/core/tedge_agent/src/entity_manager/tests.rs
  crates/extensions/c8y_mapper_ext/src/config.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/inventory.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  docs/src/operate/c8y/custom-fragments.md
  tests/RobotFramework/tests/cumulocity/inventory/inventory_update_bootstrap.robot
  tests/RobotFramework/tests/tedge/diag/predefined_plugins.robot
Labels: theme:telemetry
