Repository thin-edge/thin-edge.io, pull requests merged in 2025-01, with the labels that each got.

#3314 test: pretty print json payloads and disable robotidy to preserve leading whitespace
  tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
Labels: theme:testing

#3292 refactor: Simplify SmartREST publish topics
  crates/core/c8y_api/src/smartrest/inventory.rs
  crates/core/c8y_api/src/smartrest/topic.rs
  crates/core/tedge_api/src/entity_store.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/service_monitor.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  crates/extensions/tedge_mqtt_ext/src/test_helpers.rs
Labels: refactoring, theme:c8y

#3313 feat: Trigger tedge multicall with symlinks as well as sub-commands
  crates/core/tedge/Cargo.toml
  crates/core/tedge/src/cli/mod.rs
  crates/core/tedge/src/main.rs
  docs/src/references/cli/index.md
  plugins/tedge_apt_plugin/src/lib.rs
Labels: theme:installation, theme:cli

#3321 refactor: clippy warning unnecessary_map_or
  crates/common/tedge_config_macros/impl/src/input/validate.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/main.rs
  crates/extensions/c8y_auth_proxy/src/server.rs
  crates/extensions/tedge_mqtt_bridge/src/lib.rs
Labels: refactoring, skip-release-notes

#3317 cli: Update component crates descriptions
  crates/core/tedge_mapper/Cargo.toml
  crates/core/tedge_watchdog/Cargo.toml
  plugins/c8y_firmware_plugin/Cargo.toml
  plugins/c8y_remote_access_plugin/Cargo.toml
Labels: theme:cli

#3320 doc: Add documentation exemple missing arg
  docs/src/operate/registration/deregister.md
Labels: documentation

#3316 fix: tedge cert create-csr should use cloud profile's CN
  crates/core/tedge/src/cli/certificate/cli.rs
  tests/RobotFramework/tests/tedge/certificate_signing_request.robot
Labels: bug, theme:cli

#3324 fix: support symlinks in atomic file write methods
  crates/common/tedge_utils/src/fs.rs
Labels: theme:configuration

#3330 patch version bump
  Cargo.lock
  Cargo.toml
Labels: skip-release-notes

#3333 docs: update company references
  docs/src/operate/c8y/apama.md
  docs/src/references/mappers/mqtt-topics.md
Labels: documentation, skip-release-notes

#3332 feat: support shell completions in `tedge` cli
  Cargo.lock
  Cargo.toml
  crates/common/tedge_config/Cargo.toml
  crates/common/tedge_config/src/cli.rs
  crates/common/tedge_config_macros/Cargo.toml
  crates/common/tedge_config_macros/impl/src/input/validate.rs
  crates/common/tedge_config_macros/impl/src/query.rs
  crates/common/tedge_config_macros/tests/cli_completions.rs
  crates/core/tedge/Cargo.toml
  crates/core/tedge/src/cli/certificate/cli.rs
  crates/core/tedge/src/cli/common.rs
  crates/core/tedge/src/cli/completions.rs
  crates/core/tedge/src/cli/config/cli.rs
  crates/core/tedge/src/cli/mod.rs
  crates/core/tedge/src/cli/mqtt/cli.rs
  crates/core/tedge/src/main.rs
  docs/src/install/index.md
  docs/src/operate/troubleshooting/log-files.md
Labels: theme:cli

#3328 test: missing test for custom operation execution using smartrest templates
  docs/src/operate/c8y/smartrest-templates.md
  tests/RobotFramework/requirements/requirements.txt
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_smartrest_template/set_wifi
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_smartrest_template/set_wifi.json
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_smartrest_template/set_wifi.sh
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_smartrest_template/smartrest_template.robot
Labels: theme:c8y, theme:testing

#3335 docs: rename Cumulocity IoT to Cumulocity
  configuration/package_manifests/nfpm.c8y-remote-access-plugin.yaml
  crates/core/tedge/src/cli/certificate/cli.rs
  design/thin-edge-core.md
  docs/src/legacy/child-device-configuration-management.md
  docs/src/legacy/child-device-firmware-management.md
  docs/src/operate/c8y/apama.md
  docs/src/operate/c8y/connect.md
  docs/src/operate/c8y/custom-fragments.md
  docs/src/operate/c8y/device-availability.md
  docs/src/operate/c8y/device-profiles.md
  docs/src/operate/c8y/health-monitoring.md
  docs/src/operate/c8y/index.md
  docs/src/operate/c8y/remote-access.md
  docs/src/operate/c8y/restart-device.md
  docs/src/operate/c8y/smartrest-templates.md
  docs/src/operate/c8y/software-management.md
  docs/src/operate/c8y/supported-operations.md
  docs/src/operate/configuration/index.md
  docs/src/operate/configuration/mapper-configuration.md
  docs/src/operate/security/cloud-authentication.md
  docs/src/operate/security/cumulocity-token.md
  docs/src/operate/security/device-certificate.md
  docs/src/operate/security/https-configuration.md
  docs/src/operate/troubleshooting/device-monitoring.md
  docs/src/operate/troubleshooting/testing-cloud-connection.md
  docs/src/overview.md
  docs/src/references/agent/software-management.md
  docs/src/references/configuration-files.md
  docs/src/references/cumulocity-proxy.md
  docs/src/references/mappers/c8y-mapper.md
  docs/src/start/connect-aws.md
  docs/src/start/connect-azure.md
  docs/src/start/connect-c8y.md
  docs/src/start/getting-started.md
  docs/src/start/raise-alarm.md
  docs/src/start/send-events.md
  docs/src/start/send-measurements.md
  kubernetes/README.md
  tests/RobotFramework/README.md
  tests/RobotFramework/devdata/env.template
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
  tests/RobotFramework/tasks/E2E_Tutorials/Connect_to_c8y.robot
  tests/RobotFramework/tasks/build_install_rpi.robot
  tests/RobotFramework/tests/cumulocity/availability/heartbeat.robot
  tests/RobotFramework/tests/cumulocity/firmware/firmware_operation.robot
  tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
  tests/RobotFramework/tests/cumulocity/software_management/software.robot
  tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
  tests/images/debian-systemd/README.md
  tests/images/debian-systemd/files/bootstrap.sh
Labels: documentation

#3334 docs: update links to Cumulocity documentation pages
  docs/src/extend/firmware-management/building-image/rugpi/tutorial.md
  docs/src/extend/firmware-management/building-image/yocto/tutorial.md
  docs/src/legacy/child-device-firmware-management.md
  docs/src/operate/c8y/configuration-management.md
  docs/src/operate/c8y/connect.md
  docs/src/operate/c8y/custom-fragments.md
  docs/src/operate/c8y/remote-access.md
  docs/src/operate/c8y/smartrest-templates.md
  docs/src/operate/c8y/supported-operations.md
  docs/src/operate/security/device-certificate.md
  docs/src/operate/troubleshooting/testing-cloud-connection.md
  docs/src/overview.md
  docs/src/references/mappers/c8y-mapper.md
  docs/src/start/connect-c8y.md
  docs/src/start/getting-started.md
  docs/src/start/raise-alarm.md
  docs/src/start/send-events.md
  docs/src/start/software-management.md
  docs/src/understand/tedge-mapper.md
  tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
  tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot
  tests/RobotFramework/tests/cumulocity/log/log_operation.robot
  tests/RobotFramework/tests/cumulocity/restart/restart_device.robot
  tests/RobotFramework/tests/cumulocity/software_management/software.robot
Labels: documentation

#3337 docs: update external urls which were being redirected
  CONTRIBUTING.md
  README.md
  design/decisions/0005-tedge-watchdog.md
  docs/README.md
  docs/src/contribute/build.md
  docs/src/operate/monitoring/systemd-watchdog.md
  docs/src/references/supported-platforms.md
  docs/src/start/connect-azure.md
  docs/src/start/device-monitoring.md
  docs/src/start/getting-started.md
  docs/src/understand/faq.md
  docs/src/understand/tedge-mapper.md
Labels: documentation

#3230 feat: Entity registration HTTP API
  Cargo.lock
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/c8y_api/src/json_c8y.rs
  crates/core/c8y_api/src/smartrest/topic.rs
  crates/core/tedge/src/cli/init.rs
  crates/core/tedge_agent/Cargo.toml
  crates/core/tedge_agent/src/agent.rs
  crates/core/tedge_agent/src/entity_manager/mod.rs
  crates/core/tedge_agent/src/entity_manager/server.rs
  crates/core/tedge_agent/src/file_transfer_server/mod.rs
  crates/core/tedge_agent/src/http_server/actor.rs
  crates/core/tedge_agent/src/http_server/entity_store.rs
  crates/core/tedge_agent/src/http_server/error.rs
  crates/core/tedge_agent/src/http_server/file_transfer.rs
  crates/core/tedge_agent/src/http_server/mod.rs
  crates/core/tedge_agent/src/http_server/request_files.rs
  crates/core/tedge_agent/src/http_server/server.rs
  crates/core/tedge_agent/src/lib.rs
  crates/core/tedge_api/Cargo.toml
  crates/core/tedge_api/src/entity.rs
  crates/core/tedge_api/src/entity_store.rs
  crates/core/tedge_api/src/event.rs
  crates/core/tedge_api/src/lib.rs
  crates/core/tedge_api/src/mqtt_topics.rs
  crates/core/tedge_api/src/store/pending_entity_store.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
  crates/extensions/c8y_mapper_ext/src/actor.rs
  crates/extensions/c8y_mapper_ext/src/alarm_converter.rs
  crates/extensions/c8y_mapper_ext/src/availability/actor.rs
  crates/extensions/c8y_mapper_ext/src/availability/mod.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/entity_cache.rs
  crates/extensions/c8y_mapper_ext/src/error.rs
  crates/extensions/c8y_mapper_ext/src/inventory.rs
  crates/extensions/c8y_mapper_ext/src/json.rs
  crates/extensions/c8y_mapper_ext/src/lib.rs
  crates/extensions/c8y_mapper_ext/src/operations/convert.rs
  crates/extensions/c8y_mapper_ext/src/operations/handler.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/device_profile.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/firmware_update.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/log_upload.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/mod.rs
  crates/extensions/c8y_mapper_ext/src/operations/upload.rs
  crates/extensions/c8y_mapper_ext/src/serializer.rs
  crates/extensions/c8y_mapper_ext/src/service_monitor.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  crates/extensions/tedge_health_ext/src/lib.rs
  docs/src/operate/registration/deregister.md
  docs/src/operate/registration/register.md
  tests/RobotFramework/tests/cumulocity/mapper_recovery/recover_and_publish_software_update_message.robot
  tests/RobotFramework/tests/cumulocity/registration/registration_lifecycle.robot
  tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
Labels: theme:childdevices, theme:entity_store

#3346 Refactoring: Simplify entity registration internal API
  crates/core/tedge_agent/src/entity_manager/server.rs
  crates/core/tedge_agent/src/http_server/entity_store.rs
  crates/core/tedge_api/src/entity_store.rs
  crates/core/tedge_api/src/store/pending_entity_store.rs
  crates/extensions/c8y_mapper_ext/src/actor.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/entity_cache.rs
Labels: refactoring, theme:registration

#3348 tests: default to using locally build packages
  .github/workflows/build-workflow.yml
  tests/RobotFramework/README.md
  tests/RobotFramework/tasks.py
Labels: theme:developer-exp, theme:testing

#3349 tests: load image into docker when using buildx
  tests/RobotFramework/tasks.py
Labels: theme:testing

#3352 test: remove workflow transition logic/commit
  .github/workflows/build-workflow.yml
  tests/RobotFramework/tasks.py
Labels: theme:testing, skip-release-notes

#3356 refactor: extract versioning/migration and `TopicPrefix` from tedge config into submodules
  crates/common/tedge_config/src/tedge_config_cli/models/mod.rs
  crates/common/tedge_config/src/tedge_config_cli/models/topic_prefix.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config/append_remove.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config/version.rs
Labels: refactoring

#3358 test: update robotframework-devicelibrary dependency
  tests/RobotFramework/requirements/requirements.adapter-docker.txt
  tests/RobotFramework/requirements/requirements.adapter-local.txt
  tests/RobotFramework/requirements/requirements.adapter-ssh.txt
Labels: theme:testing

#3326 feat: support read-write device.id in tedge cert/connect
  Cargo.lock
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config_location.rs
  crates/common/tedge_config_macros/Cargo.toml
  crates/common/tedge_config_macros/examples/macro.rs
  crates/common/tedge_config_macros/examples/multi.rs
  crates/common/tedge_config_macros/examples/reader_function.rs
  crates/common/tedge_config_macros/impl/src/dto.rs
  crates/common/tedge_config_macros/impl/src/input/parse.rs
  crates/common/tedge_config_macros/impl/src/input/validate.rs
  crates/common/tedge_config_macros/impl/src/query.rs
  crates/common/tedge_config_macros/impl/src/reader.rs
  crates/common/tedge_config_macros/src/define_tedge_config_docs.md
  crates/core/tedge/src/cli/certificate/cli.rs
  crates/core/tedge/src/cli/certificate/create.rs
  crates/core/tedge/src/cli/certificate/create_csr.rs
  crates/core/tedge/src/cli/certificate/renew.rs
  crates/core/tedge/src/cli/config/cli.rs
  crates/core/tedge/src/cli/config/commands/list.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/cli/upload/mod.rs
  crates/core/tedge/tests/main.rs
  docs/src/operate/c8y/smartrest-one.md
  tests/RobotFramework/tests/cumulocity/smartrest_one/smartrest_one.robot
  tests/RobotFramework/tests/tedge/tedge_cert_create.robot
  tests/RobotFramework/tests/tedge_connect/tedge_connect_cn_validation.robot
Labels: theme:configuration

#3367 test: Ignore flaky test failing on spurious OpenSSL errors
  tests/RobotFramework/tests/tedge_connect/tedge_connect_test.robot
Labels: theme:testing, skip-release-notes

#3355 feat: REST API for querying entity store
  crates/core/tedge_agent/src/entity_manager/server.rs
  crates/core/tedge_agent/src/http_server/entity_store.rs
  crates/core/tedge_api/src/entity.rs
  crates/core/tedge_api/src/entity_store.rs
  docs/src/operate/registration/register.md
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
  tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
Labels: theme:entity_store

#3365 feat: add MQTT keepalive_interval config to allow custom value per bridge
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/tedge/src/bridge/aws.rs
  crates/core/tedge/src/bridge/azure.rs
  crates/core/tedge/src/bridge/c8y.rs
  crates/core/tedge/src/bridge/config.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge_mapper/src/aws/mapper.rs
  crates/core/tedge_mapper/src/az/mapper.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
Labels: theme:configuration, theme:mqtt, theme:bridge
