Repository thin-edge/thin-edge.io, pull requests merged in 2025-06, with the labels that each got.

#3669 fix: missing operation file c8y-remote-access-plugin when installed on Alpine Linux
  configuration/contrib/operations/c8y_RemoteAccessConnect
  configuration/package_manifests/nfpm.c8y-remote-access-plugin.yaml
Labels: theme:packaging

#3673 feat: avoid using months when displaying certificate duration
  crates/core/tedge/src/cli/certificate/show.rs
Labels: theme:certificates

#3652 docs: Add JSON schema for MEA MQTT messages
  configuration/schema/tedge-alarm.schema.json
  configuration/schema/tedge-event.schema.json
  configuration/schema/tedge-measurement.schema.json
Labels: documentation, theme:developer-exp

#3668 fix: wrong message being shown on `system.toml` parse error
  crates/core/tedge/src/system_services/managers/general_manager.rs
Labels: theme:cli

#3674 docs: update Apama repository docs to use latest 2026 version
  docs/src/operate/c8y/apama.md
Labels: documentation

#3678 chore: add template.sh.ignore to package and fix typo
  configuration/package_manifests/nfpm.tedge.yaml
  tests/RobotFramework/tests/tedge/diag/tedge_diag_collect.robot
Labels: theme:troubleshooting, skip-release-notes

#3679 chore: remove unused install script
  install.sh
Labels: refactoring, theme:installation

#3676 docs: update build instructions
  docs/src/contribute/build.md
Labels: documentation, theme:developer-exp

#3685 feat: process configuration before software in device profile operations
  crates/extensions/c8y_mapper_ext/src/operations/convert.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/device_profile.rs
  docs/src/references/agent/device-profiles.md
Labels: theme:profile

#3687 feat: tedge diag adds summary output to the archive
  crates/core/tedge/src/cli/diag/collect.rs
  crates/core/tedge/src/cli/diag/logger.rs
  crates/core/tedge/src/cli/diag/mod.rs
  tests/RobotFramework/tests/tedge/diag/tedge_diag_collect.robot
Labels: theme:troubleshooting, skip-release-notes

#3692 docs: add tip on how to download only the root certificate using openssl and awk
  docs/src/operate/security/cloud-authentication.md
  docs/src/start/connect-c8y.md
Labels: documentation, theme:certificates

#3681 fix: clear all retained entity messages on entity deregistration
  crates/core/tedge_agent/src/agent.rs
  crates/core/tedge_agent/src/entity_manager/server.rs
  crates/core/tedge_agent/src/entity_manager/tests.rs
  crates/extensions/tedge_mqtt_ext/src/lib.rs
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
  tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
Labels: theme:entity_store

#3696 chore: tedge diag's tarball path prints out to stdout
  crates/core/tedge/src/cli/diag/collect.rs
  tests/RobotFramework/tests/tedge/diag/tedge_diag_collect.robot
Labels: theme:troubleshooting, skip-release-notes

#3661 refactor: support dynamic MQTT subscriptions in `mqtt-channel`/`tedge-mqtt-ext`
  Cargo.lock
  crates/common/mqtt_channel/src/connection.rs
  crates/common/mqtt_channel/src/tests.rs
  crates/common/mqtt_channel/src/topics.rs
  crates/extensions/tedge_mqtt_ext/Cargo.toml
  crates/extensions/tedge_mqtt_ext/proptest-regressions/trie.txt
  crates/extensions/tedge_mqtt_ext/src/lib.rs
  crates/extensions/tedge_mqtt_ext/src/tests.rs
  crates/extensions/tedge_mqtt_ext/src/trie.rs
Labels: refactoring, theme:mqtt

#3700 fix: clear health status on entity deregister
  crates/core/tedge_agent/src/entity_manager/server.rs
  crates/core/tedge_agent/src/entity_manager/tests.rs
  tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
Labels: skip-release-notes, theme:entity_store

#3702 fix: add connection timeout when connecting to the local broker
  crates/core/c8y_api/src/http_proxy.rs
Labels: theme:troubleshooting

#3691 PKCS11 Extract uri module to another file and improve PKCS11 ECDSA signature formatting
  crates/extensions/tedge-p11-server/src/pkcs11/mod.rs
  crates/extensions/tedge-p11-server/src/pkcs11/uri.rs
Labels: refactoring, theme:hsm

#3714 refactor: cleanup code and outdated comments from the availability actor
  crates/extensions/c8y_mapper_ext/src/availability/actor.rs
  crates/extensions/c8y_mapper_ext/src/availability/builder.rs
  crates/extensions/c8y_mapper_ext/src/availability/mod.rs
  crates/extensions/c8y_mapper_ext/src/inventory.rs
Labels: refactoring, skip-release-notes
