Repository thin-edge/thin-edge.io, pull requests merged in 2025-04, with the labels that each got.

#3259 feat: Integration with Cumulocity CA
  Cargo.lock
  Cargo.toml
  crates/common/certificate/src/lib.rs
  crates/common/tedge_config/src/tedge_toml/tedge_config.rs
  crates/common/tedge_config_macros/src/multi.rs
  crates/core/c8y_api/src/http_proxy.rs
  crates/core/c8y_api/src/json_c8y_deserializer.rs
  crates/core/tedge/Cargo.toml
  crates/core/tedge/src/cli/certificate/c8y/download.rs
  crates/core/tedge/src/cli/certificate/c8y/mod.rs
  crates/core/tedge/src/cli/certificate/c8y/renew.rs
  crates/core/tedge/src/cli/certificate/c8y/upload.rs
  crates/core/tedge/src/cli/certificate/cli.rs
  crates/core/tedge/src/cli/certificate/create.rs
  crates/core/tedge/src/cli/certificate/create_csr.rs
  crates/core/tedge/src/cli/certificate/error.rs
  crates/core/tedge/src/cli/certificate/mod.rs
  crates/core/tedge/src/cli/certificate/renew.rs
  crates/core/tedge/src/cli/certificate/show.rs
  deny.toml
  tests/RobotFramework/tests/cumulocity/registration/cumulocity_ca.robot
  tests/RobotFramework/tests/tedge/tedge_upload_cert.robot
  tests/RobotFramework/tests/tedge/tedge_upload_cert_custom_root_cert_path.robot
Labels: feature, theme:c8y, theme:certificates

#3503 refactor: Shorten entity store service REST API paths
  Cargo.lock
  Cargo.toml
  crates/core/tedge/src/cli/http/cli.rs
  crates/core/tedge_agent/Cargo.toml
  crates/core/tedge_agent/proptest-regressions/entity_manager/tests.txt
  crates/core/tedge_agent/src/entity_manager/tests.rs
  crates/core/tedge_agent/src/http_server/actor.rs
  crates/core/tedge_agent/src/http_server/file_transfer.rs
  crates/core/tedge_agent/src/http_server/server.rs
  crates/core/tedge_agent/src/operation_file_cache/mod.rs
  crates/extensions/c8y_firmware_manager/src/tests.rs
  crates/extensions/c8y_firmware_manager/src/worker.rs
  crates/extensions/c8y_mapper_ext/src/operations/convert.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/config_snapshot.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/config_update.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/firmware_update.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/log_upload.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  crates/extensions/tedge_config_manager/src/actor.rs
  crates/extensions/tedge_config_manager/src/tests.rs
  crates/extensions/tedge_log_manager/src/tests.rs
  design/decisions/0005-entity-registration-api.md
  docs/src/legacy/child-device-configuration-management.md
  docs/src/legacy/child-device-firmware-management.md
  docs/src/operate/registration/register.md
  docs/src/operate/security/https-configuration.md
  docs/src/references/agent/operation-workflow.md
  docs/src/references/agent/tedge-configuration-management.md
  docs/src/references/agent/tedge-log-management.md
  docs/src/references/cli/tedge-http.md
  docs/src/references/file-transfer-service.md
  docs/src/references/mqtt-api.md
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
  tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
  tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot
  tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device.robot
  tests/RobotFramework/tests/cumulocity/log/log_operation.robot
  tests/RobotFramework/tests/tedge/http_file_transfer_api.robot
  tests/RobotFramework/tests/tedge/tedge_http.robot
  tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
  tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
  tests/RobotFramework/tests/tedge_agent/tedge_agent.robot
Labels: skip-release-notes, theme:entity_store

#3527 fix: improve accessibility of tedge cert show
  crates/core/tedge/src/cli/certificate/show.rs
Labels: improvement, theme:cli, theme:certificates

#3525 fix: tedge cert renew returning success exit code on error
  crates/core/c8y_api/src/http_proxy.rs
  crates/core/tedge/src/cli/certificate/c8y/download.rs
  crates/core/tedge/src/cli/certificate/c8y/renew.rs
  crates/core/tedge/src/cli/certificate/create.rs
  crates/core/tedge/src/cli/certificate/create_csr.rs
  crates/core/tedge/src/cli/certificate/error.rs
  crates/core/tedge/src/cli/certificate/mod.rs
  crates/core/tedge/src/cli/certificate/renew.rs
Labels: bug, theme:cli, theme:certificates

#3529 ci: refactor build script and workflow
  .github/workflows/build-workflow.yml
  ci/build_scripts/build.sh
  ci/package_list.sh
  mk/install-build-tools.sh
Labels: ci/cd

#3514 feat: tedge-p11-server packaging
  ci/build_scripts/package.sh
  ci/package_list.sh
  configuration/contrib/tedge-p11-server/tedge-p11-server.conf
  configuration/init/systemd/75-tedge.preset
  configuration/init/systemd/tedge-p11-server.service
  configuration/init/systemd/tedge-p11-server.socket
  configuration/package_manifests/nfpm.tedge-p11-server.yaml
  configuration/package_scripts/_generated/tedge-p11-server/apk/postinst
  configuration/package_scripts/_generated/tedge-p11-server/apk/postrm
  configuration/package_scripts/_generated/tedge-p11-server/apk/preinst
  configuration/package_scripts/_generated/tedge-p11-server/apk/prerm
  configuration/package_scripts/_generated/tedge-p11-server/deb/postinst
  configuration/package_scripts/_generated/tedge-p11-server/deb/postrm
  configuration/package_scripts/_generated/tedge-p11-server/deb/preinst
  configuration/package_scripts/_generated/tedge-p11-server/deb/prerm
  configuration/package_scripts/_generated/tedge-p11-server/rpm/postinst
  configuration/package_scripts/_generated/tedge-p11-server/rpm/postrm
  configuration/package_scripts/_generated/tedge-p11-server/rpm/preinst
  configuration/package_scripts/_generated/tedge-p11-server/rpm/prerm
  configuration/package_scripts/packages.json
  configuration/package_scripts/tedge-p11-server/preinst
  crates/common/tedge_config/src/tedge_toml/tedge_config.rs
  crates/common/tedge_config/src/tedge_toml/tedge_config/mqtt_config.rs
  tests/RobotFramework/tests/pkcs11/data/init_softhsm.sh
  tests/RobotFramework/tests/pkcs11/private_key_storage.robot
  tests/images/debian-systemd/debian-systemd.dockerfile
  tests/images/debian-systemd/files/bootstrap.sh
Labels: theme:packaging, skip-release-notes

#3532 ci: move cargo-test job to build-workflow
  .github/workflows/build-workflow.yml
  .github/workflows/pull-request-checks.yml
Labels: ci/cd

#3542 feat: shorten cryptoki pin debug display placeholder
  crates/extensions/tedge-p11-server/src/pkcs11.rs
Labels: theme:security, theme:certificates, skip-release-notes

#3540 fix: use git semver generated version for tedge-p11-server
  crates/extensions/tedge-p11-server/build.rs
Labels: theme:certificates, skip-release-notes

#3552 fix: c8y mapper config should use the value of c8y.mqtt as mqtt endpoint
  crates/extensions/c8y_mapper_ext/src/config.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/config_update.rs
Labels: theme:c8y

#3558 tests: increase max inflight messages for mosquitto to avoid dropped messages
  tests/images/debian-systemd/files/mosquitto.conf
Labels: theme:mqtt, theme:testing

#3499 fix: clear retained entity twin messages on deregister
  crates/core/tedge_agent/src/entity_manager/server.rs
  crates/core/tedge_agent/src/entity_manager/tests.rs
  crates/core/tedge_api/src/entity_store.rs
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
  tests/RobotFramework/tests/cumulocity/registration/registration_lifecycle.robot
  tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
Labels: theme:mqtt, theme:entity_store

#3556 feat: support CSR file formats from gnutls certtool
  crates/core/tedge/src/cli/certificate/c8y/mod.rs
Labels: theme:cli, theme:certificates

#3560 feat: append the option whether to add c8y_IsDevice to child devices
  crates/common/tedge_config/src/tedge_toml/tedge_config.rs
  crates/core/c8y_api/src/smartrest/inventory.rs
  crates/extensions/c8y_mapper_ext/src/config.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  docs/src/references/mappers/c8y-mapper.md
Labels: theme:c8y, theme:childdevices

#3551 feat: validate new certificate on connect
  crates/common/certificate/src/lib.rs
  crates/core/tedge/src/bridge/c8y.rs
  crates/core/tedge/src/bridge/config.rs
  crates/core/tedge/src/cli/certificate/c8y/download.rs
  crates/core/tedge/src/cli/certificate/c8y/renew.rs
  crates/core/tedge/src/cli/certificate/c8y/upload.rs
  crates/core/tedge/src/cli/certificate/cli.rs
  crates/core/tedge/src/cli/certificate/create.rs
  crates/core/tedge/src/cli/certificate/mod.rs
  crates/core/tedge/src/cli/certificate/remove.rs
  crates/core/tedge/src/cli/certificate/renew.rs
  crates/core/tedge/src/cli/certificate/shift.rs
  crates/core/tedge/src/cli/certificate/show.rs
  crates/core/tedge/src/cli/connect/aws.rs
  crates/core/tedge/src/cli/connect/azure.rs
  crates/core/tedge/src/cli/connect/c8y.rs
  crates/core/tedge/src/cli/connect/c8y_direct_connection.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/cli/connect/jwt_token.rs
  crates/core/tedge/src/cli/connect/mod.rs
  crates/core/tedge/src/cli/mod.rs
  tests/RobotFramework/tests/tedge/certificate_signing_request.robot
  tests/RobotFramework/tests/tedge/tedge_upload_cert.robot
  tests/RobotFramework/tests/tedge/tedge_upload_cert_custom_root_cert_path.robot
  tests/RobotFramework/tests/tedge_connect/tedge_connect_profile_validation.robot
  tests/RobotFramework/tests/tedge_connect/tedge_connect_test.robot
  tests/images/debian-systemd/files/bootstrap.sh
Labels: improvement, theme:cli, theme:certificates

#3522 tests: tedge-p11-server testing
  Cargo.lock
  crates/extensions/tedge-p11-server/Cargo.toml
  crates/extensions/tedge-p11-server/src/lib.rs
  crates/extensions/tedge-p11-server/src/main.rs
  crates/extensions/tedge-p11-server/src/server.rs
  crates/extensions/tedge-p11-server/src/service.rs
Labels: theme:testing

#3567 fix: change references to the removed --self-update flag
  crates/core/tedge/src/cli/certificate/c8y/mod.rs
  crates/core/tedge/src/cli/certificate/cli.rs
Labels: theme:certificates, skip-release-notes

#3523 feat: add certificate renewal service
  configuration/init/systemd/tedge-cert-renewer.target
  configuration/init/systemd/tedge-cert-renewer@.service
  configuration/init/systemd/tedge-cert-renewer@.timer
  configuration/init/systemd/tedge-mapper-c8y.service
  configuration/init/systemd/tedge-mapper-c8y@.service
  configuration/package_manifests/nfpm.tedge-mapper.yaml
  tests/RobotFramework/tests/cumulocity/registration/cumulocity_ca.robot
Labels: theme:certificates

#3564 fix: support relative path args when using tedge cert
  Cargo.lock
  Cargo.toml
  crates/common/tedge_config/Cargo.toml
  crates/common/tedge_config/src/tedge_toml/models/mod.rs
  crates/common/tedge_config/src/tedge_toml/models/path.rs
  crates/common/tedge_config/src/tedge_toml/tedge_config.rs
  crates/common/tedge_config/src/tedge_toml/tedge_config/append_remove.rs
  crates/common/tedge_config/src/tedge_toml/tedge_config/mqtt_config.rs
  crates/common/tedge_config/src/tedge_toml/tedge_config_location.rs
  crates/common/tedge_utils/Cargo.toml
  crates/common/tedge_utils/src/paths.rs
  crates/core/c8y_api/src/http_proxy.rs
  crates/core/tedge/src/bridge/common_mosquitto_config.rs
  crates/core/tedge/src/cli/certificate/cli.rs
  crates/core/tedge/src/cli/certificate/create.rs
  crates/core/tedge/src/cli/certificate/error.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge_agent/src/agent.rs
  crates/core/tedge_agent/src/http_server/request_files.rs
  crates/core/tedge_agent/src/operation_workflows/config.rs
  crates/core/tedge_agent/src/restart_manager/config.rs
  crates/core/tedge_agent/src/software_manager/config.rs
  crates/core/tedge_write/src/bin.rs
  crates/extensions/c8y_auth_proxy/src/actor.rs
  crates/extensions/c8y_firmware_manager/src/config.rs
  crates/extensions/c8y_mapper_ext/src/config.rs
  tests/RobotFramework/tests/mqtt/basic_pub_sub.robot
  tests/RobotFramework/tests/mqtt/disconnect_from_broker.robot
  tests/RobotFramework/tests/tedge/certificate_signing_request.robot
  tests/RobotFramework/tests/tedge/tedge_config_get.robot
Labels: theme:cli, theme:certificates

#3555 feat: Key selection using PKCS #11 URI
  Cargo.lock
  Cargo.toml
  configuration/init/systemd/tedge-p11-server.service
  crates/common/tedge_config/src/tedge_toml/tedge_config/mqtt_config.rs
  crates/extensions/tedge-p11-server/Cargo.toml
  crates/extensions/tedge-p11-server/src/lib.rs
  crates/extensions/tedge-p11-server/src/main.rs
  crates/extensions/tedge-p11-server/src/pkcs11.rs
  crates/extensions/tedge-p11-server/src/service.rs
  crates/extensions/tedge-p11-server/src/signer.rs
  tests/RobotFramework/tests/pkcs11/private_key_storage.robot
Labels: theme:security, theme:certificates, skip-release-notes

#3574 fix: create tedge-p11-server socket parent directory if it does not exist
  crates/extensions/tedge-p11-server/Cargo.toml
  crates/extensions/tedge-p11-server/src/main.rs
Labels: theme:security, theme:certificates, skip-release-notes

#3566 feat: PKCS#11 support for aws and azure
  crates/common/tedge_config/src/tedge_toml/models/cryptoki.rs
  crates/common/tedge_config/src/tedge_toml/tedge_config/mqtt_config.rs
  crates/core/tedge/src/bridge/aws.rs
  crates/core/tedge/src/bridge/azure.rs
  crates/core/tedge/src/bridge/c8y.rs
  crates/core/tedge/src/bridge/config.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/cli/log.rs
  crates/core/tedge_mapper/src/aws/mapper.rs
  crates/core/tedge_mapper/src/az/mapper.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
  crates/extensions/tedge-p11-server/src/client.rs
  tests/RobotFramework/requirements/requirements.txt
  tests/RobotFramework/tests/pkcs11/private_key_storage_aws.robot
Labels: theme:security, theme:certificates

#3568 feat: allow tedge p11 server to be configured through tedge.toml
  Cargo.lock
  configuration/contrib/tedge-p11-server/tedge-p11-server.conf
  configuration/init/systemd/tedge-p11-server.service
  crates/common/tedge_config/src/tedge_toml/tedge_config.rs
  crates/common/tedge_config/src/tedge_toml/tedge_config/mqtt_config.rs
  crates/extensions/tedge-p11-server/Cargo.toml
  crates/extensions/tedge-p11-server/src/main.rs
  crates/extensions/tedge-p11-server/src/pkcs11.rs
  tests/RobotFramework/tests/pkcs11/private_key_storage.robot
  tests/RobotFramework/tests/pkcs11/private_key_storage_aws.robot
Labels: theme:configuration, theme:certificates, skip-release-notes

#3578 fix: ensure EntityTopicId deserialization uses FromStr logic
  crates/core/tedge_api/src/mqtt_topics.rs
Labels: refactoring, skip-release-notes, theme:entity_store

#3581 fix: flush stdout before exiting tedge http command
  crates/core/tedge/src/cli/http/command.rs
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
Labels: theme:cli, skip-release-notes

#3537 feat: Entity PATCH API to update parent of an entity
  crates/core/c8y_api/src/http_proxy.rs
  crates/core/tedge_agent/src/entity_manager/server.rs
  crates/core/tedge_agent/src/entity_manager/tests.rs
  crates/core/tedge_agent/src/http_server/entity_store.rs
  crates/core/tedge_api/src/entity.rs
  crates/core/tedge_api/src/entity_store.rs
  crates/core/tedge_api/src/mqtt_topics.rs
  crates/extensions/c8y_http_proxy/src/actor.rs
  crates/extensions/c8y_http_proxy/src/handle.rs
  crates/extensions/c8y_mapper_ext/src/actor.rs
  crates/extensions/c8y_mapper_ext/src/availability/actor.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/entity_cache.rs
  crates/extensions/c8y_mapper_ext/src/json.rs
  crates/extensions/c8y_mapper_ext/src/serializer.rs
  crates/extensions/c8y_mapper_ext/src/service_monitor.rs
  crates/extensions/tedge_health_ext/src/lib.rs
  crates/extensions/tedge_http_ext/src/messages.rs
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
  tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
Labels: skip-release-notes, theme:entity_store

#3583 fix: Overwritten workflow failure reason
  crates/core/tedge_api/src/workflow/handlers.rs
  crates/core/tedge_api/src/workflow/state.rs
  crates/core/tedge_api/src/workflow/toml_config.rs
Labels: improvement, theme:workflows

#3586 fix: tedge-p11-server fails when configuration is missing
  configuration/init/systemd/tedge-p11-server.service
  crates/extensions/tedge-p11-server/src/main.rs
  tests/RobotFramework/tests/pkcs11/private_key_storage.robot
Labels: theme:configuration, skip-release-notes

#3585 Configure supported cloud backends at compile time
  Cargo.toml
  crates/core/tedge/Cargo.toml
  crates/core/tedge/src/bridge/mod.rs
  crates/core/tedge/src/cli/certificate/cli.rs
  crates/core/tedge/src/cli/common.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/cli/connect/mod.rs
  crates/core/tedge/src/cli/refresh_bridges.rs
  crates/core/tedge/src/lib.rs
  crates/core/tedge_mapper/Cargo.toml
  crates/core/tedge_mapper/src/lib.rs
Labels: theme:c8y, theme:packaging, theme:aws, theme:az

#3588 doc: Entity PATCH API to update entity definition
  docs/src/install/index.md
  docs/src/operate/registration/register.md
Labels: documentation

#3587 refactor: parse entity registration message using serde
  crates/core/tedge_agent/src/entity_manager/server.rs
  crates/core/tedge_agent/src/http_server/entity_store.rs
  crates/core/tedge_api/src/entity_store.rs
  crates/extensions/c8y_mapper_ext/src/availability/builder.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
Labels: refactoring, skip-release-notes

#3589 feat: tedge-p11-server support RSA keys
  crates/extensions/tedge-p11-server/src/pkcs11.rs
  tests/RobotFramework/tests/pkcs11/private_key_storage.robot
Labels: theme:security, theme:certificates, skip-release-notes

#3531 feat: support HTTP CONNECT proxy connection for built-in MQTT bridge
  .typos.toml
  Cargo.lock
  crates/common/certificate/src/cloud_root_certificate.rs
  crates/common/certificate/src/parse_root_certificate/mod.rs
  crates/common/download/examples/simple_download.rs
  crates/common/download/src/download.rs
  crates/common/tedge_config/src/tedge_toml/models/mod.rs
  crates/common/tedge_config/src/tedge_toml/models/proxy_scheme.rs
  crates/common/tedge_config/src/tedge_toml/models/proxy_url.rs
  crates/common/tedge_config/src/tedge_toml/tedge_config.rs
  crates/common/tedge_config/src/tedge_toml/tedge_config/append_remove.rs
  crates/common/upload/src/upload.rs
  crates/core/plugin_sm/src/plugin.rs
  crates/core/plugin_sm/src/plugin_manager.rs
  crates/core/plugin_sm/tests/plugin.rs
  crates/core/tedge/src/bridge/aws.rs
  crates/core/tedge/src/bridge/azure.rs
  crates/core/tedge/src/bridge/c8y.rs
  crates/core/tedge/src/bridge/config.rs
  crates/core/tedge/src/cli/certificate/c8y/download.rs
  crates/core/tedge/src/cli/certificate/c8y/renew.rs
  crates/core/tedge/src/cli/certificate/c8y/upload.rs
  crates/core/tedge/src/cli/certificate/cli.rs
  crates/core/tedge/src/cli/connect/c8y.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/cli/http/cli.rs
  crates/core/tedge/src/cli/log.rs
  crates/core/tedge/src/cli/upload/c8y.rs
  crates/core/tedge/src/cli/upload/mod.rs
  crates/core/tedge_agent/src/agent.rs
  crates/core/tedge_mapper/Cargo.toml
  crates/core/tedge_mapper/src/aws/mapper.rs
  crates/core/tedge_mapper/src/az/mapper.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
  crates/core/tedge_mapper/src/core/mod.rs
  crates/core/tedge_mapper/src/core/mqtt.rs
  crates/extensions/c8y_auth_proxy/src/actor.rs
  crates/extensions/tedge_downloader_ext/src/actor.rs
  crates/extensions/tedge_downloader_ext/src/tests.rs
  crates/extensions/tedge_mqtt_bridge/Cargo.toml
  crates/extensions/tedge_uploader_ext/src/actor.rs
  crates/extensions/tedge_uploader_ext/src/tests.rs
  plugins/c8y_firmware_plugin/src/lib.rs
  tests/RobotFramework/tests/cumulocity/http_proxy/http_proxy_support.robot
  tests/images/debian-systemd/debian-systemd.dockerfile
  tests/images/debian-systemd/files/gost-http-proxy.service
Labels: theme:connectivity
