Repository thin-edge/thin-edge.io, pull requests merged in 2025-02, with the labels that each got.

#3354 docs: add c8y tenant manager note to getting started guide
  docs/src/start/connect-c8y.md
  docs/src/start/getting-started.md
Labels: documentation, theme:c8y

#3372 fix: device.id is derived from device certificate if certificate exists
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/tedge/src/cli/certificate/cli.rs
  crates/core/tedge/src/cli/certificate/create.rs
  crates/core/tedge/src/cli/certificate/create_csr.rs
  crates/core/tedge/src/cli/certificate/renew.rs
  crates/core/tedge/src/cli/connect/command.rs
  tests/RobotFramework/tests/tedge/device_id/device_id_derivation.robot
  tests/RobotFramework/tests/tedge/device_id/device_id_usecases.robot
  tests/RobotFramework/tests/tedge/tedge_cert_create.robot
  tests/RobotFramework/tests/tedge_connect/tedge_connect_cn_validation.robot
Labels: theme:cli, theme:certificates

#3371 Update to hyper 1.0
  .config/nextest.toml
  Cargo.lock
  Cargo.toml
  crates/common/axum_tls/Cargo.toml
  crates/common/axum_tls/src/acceptor.rs
  crates/common/axum_tls/src/config.rs
  crates/common/axum_tls/src/error_matching.rs
  crates/common/axum_tls/src/files.rs
  crates/common/certificate/src/cloud_root_certificate.rs
  crates/common/certificate/src/lib.rs
  crates/common/certificate/src/parse_root_certificate.rs
  crates/common/download/Cargo.toml
  crates/common/download/src/download.rs
  crates/common/mqtt_channel/src/config.rs
  crates/common/upload/src/upload.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/cli/connect/jwt_token.rs
  crates/core/tedge/src/cli/mqtt/mod.rs
  crates/core/tedge/src/cli/mqtt/publish.rs
  crates/core/tedge/src/cli/mqtt/subscribe.rs
  crates/core/tedge_agent/Cargo.toml
  crates/core/tedge_agent/src/http_server/actor.rs
  crates/core/tedge_agent/src/http_server/entity_store.rs
  crates/core/tedge_agent/src/http_server/file_transfer.rs
  crates/core/tedge_agent/src/http_server/request_files.rs
  crates/extensions/c8y_auth_proxy/Cargo.toml
  crates/extensions/c8y_auth_proxy/src/actor.rs
  crates/extensions/c8y_auth_proxy/src/body.rs
  crates/extensions/c8y_auth_proxy/src/server.rs
  crates/extensions/c8y_auth_proxy/src/tokens.rs
  crates/extensions/c8y_mapper_ext/src/operations/error.rs
  crates/extensions/tedge_http_ext/Cargo.toml
  crates/extensions/tedge_http_ext/src/actor.rs
  crates/extensions/tedge_http_ext/src/messages.rs
  crates/extensions/tedge_http_ext/src/test_helpers.rs
  crates/extensions/tedge_http_ext/src/tests.rs
  crates/extensions/tedge_mqtt_bridge/tests/bridge.rs
  crates/tests/mqtt_tests/src/test_mqtt_server.rs
Labels: dependencies

#3379 docs: add missing c8y argument to cloud connect command
  docs/src/operate/c8y/cloud-profiles.md
Labels: documentation, theme:c8y

#3381 docs: fix Cumulocity username/password instructions
  docs/src/operate/c8y/smartrest-one.md
Labels: documentation

#3382 test: re-enable client certificate test
  crates/common/axum_tls/src/acceptor.rs
Labels: theme:testing

#3384 feat: log the auth method when running `tedge connect c8y`
  crates/common/tedge_config/src/tedge_config_cli/models/auth_method.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/cli/log.rs
Labels: theme:c8y, theme:cli

#3383 feat: Query parameter support for entity store query API
  crates/core/tedge_agent/Cargo.toml
  crates/core/tedge_agent/src/entity_manager/server.rs
  crates/core/tedge_agent/src/http_server/entity_store.rs
  crates/core/tedge_api/src/entity.rs
  crates/core/tedge_api/src/entity_store.rs
  docs/src/operate/registration/register.md
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
  tests/RobotFramework/tests/tedge/tedge_http.robot
  tests/RobotFramework/tests/tedge_agent/http_server/entity_query_rest_api.robot
  tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
Labels: theme:entity_store

#3389 test: stop services during setup to prevent tedge init race condition
  tests/RobotFramework/tests/customizing/tedge_init.robot
Labels: theme:testing

#3396 fix: tegde mqtt panics on invalid MQTT topics
  crates/core/tedge/src/cli/mqtt/cli.rs
  crates/core/tedge/src/cli/mqtt/publish.rs
  crates/core/tedge/src/cli/mqtt/subscribe.rs
  tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
Labels: bug, theme:cli

#3398 fix: fix typos in repository
  ci/build_scripts/build.sh
  configuration/contrib/tedge_upgrade/upgrade_tedge_0.6.sh
  configuration/init/initd/tedge
  crates/common/mqtt_channel/src/tests.rs
  crates/common/tedge_config/src/system_services/log_config.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/common/tedge_config_macros/examples/multi.rs
  crates/common/tedge_config_macros/src/define_tedge_config_docs.md
  crates/core/c8y_api/src/smartrest/smartrest_serializer.rs
  crates/core/tedge/src/main.rs
  crates/extensions/az_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/operations/handler.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  crates/extensions/collectd_ext/src/collectd.rs
  crates/extensions/tedge_file_system_ext/Cargo.toml
  crates/extensions/tedge_log_manager/src/manager/log_utils.rs
  design/decisions/0003-c8y-mapper.md
  design/decisions/0005-entity-registration-api.md
  docs/src/operate/c8y/cloud-profiles.md
  docs/src/operate/security/https-configuration.md
  docs/src/operate/troubleshooting/log-files.md
  docs/src/references/agent/device-management-api.md
  docs/src/references/agent/index.md
  docs/src/references/file-transfer-service.md
  docs/src/references/mqtt-api.md
  tests/RobotFramework/tasks/build_install_rpi.robot
  tests/RobotFramework/tests/cumulocity/bridge_config/builtin_bridge.robot
  tests/RobotFramework/tests/cumulocity/bridge_config/local_cleansession.robot
  tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
  tests/RobotFramework/tests/cumulocity/log/workflow/log_workflow.robot
  tests/RobotFramework/tests/cumulocity/supported_operations/mapper-publishing-agent-supported-ops.robot
  tests/RobotFramework/tests/tedge/http_file_transfer_api.robot
  tests/RobotFramework/tests/tedge_watchdog/tedge_watchdog.robot
  tests/RobotFramework/tests/tedge_write.robot
  tests/images/debian-systemd/files/bootstrap.sh
Labels: documentation, refactoring, skip-release-notes

#3397 fix: broken links in tedge http docs
  docs/src/references/cli/tedge-http.md
Labels: documentation, skip-release-notes

#3390 feat: Return entity metadata in delete REST API response
  crates/common/mqtt_channel/src/topics.rs
  crates/core/tedge_agent/src/entity_manager/server.rs
  crates/core/tedge_agent/src/entity_manager/tests.rs
  crates/core/tedge_agent/src/http_server/entity_store.rs
  crates/core/tedge_api/src/entity_store.rs
  docs/src/operate/registration/register.md
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
  tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
Labels: skip-release-notes, theme:entity_store

#3392 refactor: No default service type in entity store
  crates/core/tedge_agent/src/agent.rs
  crates/core/tedge_agent/src/entity_manager/tests.rs
  crates/core/tedge_api/src/entity_store.rs
  tests/RobotFramework/tests/tedge_agent/http_server/entity_query_rest_api.robot
  tests/RobotFramework/tests/tedge_agent/http_server/entity_store_api.robot
Labels: refactoring, theme:entity_store

#3402 fix: fallback to systemctl command when debian helpers are not available
  configuration/package_scripts/_generated/c8y-firmware-plugin/deb/postinst
  configuration/package_scripts/_generated/c8y-firmware-plugin/deb/postrm
  configuration/package_scripts/_generated/c8y-firmware-plugin/deb/prerm
  configuration/package_scripts/_generated/c8y-remote-access-plugin/deb/postinst
  configuration/package_scripts/_generated/c8y-remote-access-plugin/deb/postrm
  configuration/package_scripts/_generated/c8y-remote-access-plugin/deb/prerm
  configuration/package_scripts/_generated/tedge-agent/deb/postinst
  configuration/package_scripts/_generated/tedge-agent/deb/postrm
  configuration/package_scripts/_generated/tedge-agent/deb/prerm
  configuration/package_scripts/_generated/tedge-mapper/deb/postinst
  configuration/package_scripts/_generated/tedge-mapper/deb/postrm
  configuration/package_scripts/_generated/tedge-mapper/deb/prerm
  configuration/package_scripts/_generated/tedge-watchdog/deb/postinst
  configuration/package_scripts/_generated/tedge-watchdog/deb/postrm
  configuration/package_scripts/_generated/tedge-watchdog/deb/prerm
  configuration/package_scripts/templates/deb/postinst-systemd-dont-enable
  configuration/package_scripts/templates/deb/postinst-systemd-enable
  configuration/package_scripts/templates/deb/postinst-systemd-restart
  configuration/package_scripts/templates/deb/postinst-systemd-restartnostart
  configuration/package_scripts/templates/deb/postinst-systemd-start
  configuration/package_scripts/templates/deb/postrm-systemd
  configuration/package_scripts/templates/deb/prerm-systemd
  configuration/package_scripts/templates/deb/prerm-systemd-restart
Labels: theme:yocto, theme:packaging

#3406 test: avoid restarting the tedge-mapper during the test
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_timeout/custom_operation.robot
Labels: theme:testing

#3362 fix: c8y operation fragments for firmware/software update and device profile
  crates/core/c8y_api/src/json_c8y_deserializer.rs
  crates/core/c8y_api/src/smartrest/inventory.rs
  crates/core/tedge_api/src/commands.rs
  crates/core/tedge_api/src/device_profile.rs
  crates/extensions/c8y_mapper_ext/src/operations/convert.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/config_update.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/device_profile.rs
  crates/extensions/tedge_config_manager/src/tests.rs
  tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
  tests/RobotFramework/tests/cumulocity/configuration/sub_config_update.toml
  tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
Labels: theme:software, theme:firmware, theme:profile

#3409 dev: use cargo-bininstall to install additional rust tooling
  .devcontainer/Dockerfile
Labels: theme:developer-exp

#3407 feat: install tedge tab completions during installation
  configuration/package_scripts/_generated/tedge/apk/postinst
  configuration/package_scripts/_generated/tedge/apk/postrm
  configuration/package_scripts/_generated/tedge/deb/postinst
  configuration/package_scripts/_generated/tedge/deb/postrm
  configuration/package_scripts/_generated/tedge/rpm/postinst
  configuration/package_scripts/_generated/tedge/rpm/postrm
  configuration/package_scripts/tedge/postinst
  configuration/package_scripts/tedge/postrm
  docs/src/install/index.md
  tests/images/debian-systemd/debian-systemd.dockerfile
Labels: theme:packaging, theme:cli, skip-release-notes

#3410 fix: only warn if refresh-bridges fails during installation
  configuration/package_scripts/_generated/tedge/apk/postinst
  configuration/package_scripts/_generated/tedge/deb/postinst
  configuration/package_scripts/_generated/tedge/rpm/postinst
  configuration/package_scripts/tedge/postinst
Labels: theme:packaging, theme:installation

#3386 test: add deterministic tests for the built-in bridge
  Cargo.lock
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/tedge_actors/src/runtime.rs
  crates/extensions/tedge_mqtt_bridge/Cargo.toml
  crates/extensions/tedge_mqtt_bridge/src/backoff.rs
  crates/extensions/tedge_mqtt_bridge/src/health.rs
  crates/extensions/tedge_mqtt_bridge/src/lib.rs
  crates/extensions/tedge_mqtt_bridge/src/test_helpers.rs
  crates/extensions/tedge_mqtt_bridge/src/topics.rs
  crates/extensions/tedge_mqtt_bridge/tests/bridge.rs
Labels: theme:testing, theme:bridge

#3400 feat: Initial twin data from entity registration message
  crates/core/tedge_agent/src/entity_manager/server.rs
  crates/core/tedge_agent/src/entity_manager/tests.rs
  crates/core/tedge_agent/src/http_server/entity_store.rs
  crates/core/tedge_api/src/entity.rs
  crates/core/tedge_api/src/entity_store.rs
  crates/core/tedge_api/src/mqtt_topics.rs
  crates/extensions/c8y_mapper_ext/src/availability/actor.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/entity_cache.rs
  crates/extensions/c8y_mapper_ext/src/inventory.rs
  crates/extensions/c8y_mapper_ext/src/service_monitor.rs
  crates/extensions/tedge_health_ext/src/lib.rs
  tests/RobotFramework/tests/cumulocity/inventory/inventory_update.robot
  tests/RobotFramework/tests/cumulocity/registration/registration_lifecycle.robot
  tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot
  tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
  tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry_built-in_bridge.robot
Labels: theme:entity_store

#3422 test: fix `tedge_c8y_upload.robot` not setting device context
  tests/RobotFramework/tests/cumulocity/upload/tedge_c8y_upload.robot
Labels: theme:testing

#3366 feat: HSM auth - c8y connection init & built in bridge
  Cargo.lock
  Cargo.toml
  crates/common/certificate/Cargo.toml
  crates/common/certificate/src/lib.rs
  crates/common/certificate/src/parse_root_certificate/mod.rs
  crates/common/certificate/src/parse_root_certificate/pkcs11.rs
  crates/common/tedge_config/Cargo.toml
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config/append_remove.rs
  crates/common/tedge_config/src/tedge_config_cli/tedge_config/mqtt_config.rs
  crates/core/tedge/src/bridge/aws.rs
  crates/core/tedge/src/bridge/azure.rs
  crates/core/tedge/src/bridge/c8y.rs
  crates/core/tedge/src/bridge/config.rs
  crates/core/tedge/src/cli/connect/c8y_direct_connection.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge_mapper/src/c8y/mapper.rs
  crates/extensions/tedge_mqtt_bridge/src/lib.rs
  docs/src/references/hsm-support.md
Labels: feature, theme:security, skip-release-notes

#3428 test: remove maximum mqtt message count assertion
  tests/RobotFramework/tests/cumulocity/software_management/software.robot
Labels: theme:testing

#3423 tests: update robotframework-c8y library to detect missing source in c8y api
  tests/RobotFramework/requirements/requirements.txt
  tests/RobotFramework/tests/cumulocity/bridge_config/builtin_bridge.robot
Labels: theme:testing

#3433 tests: ensure tedge-mapper-c8y is running before running assertions
  tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
Labels: theme:testing

#3431 test: soften failure reason assertions for certificate required errors
  tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot
Labels: theme:testing

#3435 tests: check if all fragments exist first before checking the value
  tests/RobotFramework/tests/cumulocity/inventory/inventory_update.robot
Labels: theme:testing

#3437 ci: upgrade to ubuntu-22.04
  .github/workflows/build-workflow.yml
  .github/workflows/pull-request-checks.yml
  .github/workflows/release.yml
Labels: ci/cd

#3438 tests: ignore maximum message count assertion due to sporadic test failures
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/custom_operation_command.robot
Labels: theme:testing

#3416 test: get_logs should look at the new location of entity_store.jsonl
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
Labels: theme:testing

#3419 feat: Allow name and type in inventory.json
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/entity_cache.rs
  crates/extensions/c8y_mapper_ext/src/fragments.rs
  crates/extensions/c8y_mapper_ext/src/inventory.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
  docs/src/references/mappers/c8y-mapper.md
  tests/RobotFramework/tests/cumulocity/inventory/inventory.json
  tests/RobotFramework/tests/cumulocity/inventory/inventory_update.robot
Labels: theme:telemetry
