Repository thin-edge/thin-edge.io, pull requests merged in 2025-05, with the labels that each got.

#3595 release: minor version bump
  Cargo.lock
  Cargo.toml
Labels: skip-release-notes

#3593 docs: rename Rugpi to Rugix
  docs/src/extend/firmware-management/building-image/rugix/index.md
  docs/src/extend/firmware-management/building-image/rugix/tutorial.md
  docs/src/extend/firmware-management/building-image/rugpi/index.md
  docs/src/extend/firmware-management/device-onboarding.md
Labels: documentation, theme:firmware

#3596 docs: add instructions and tests on how to install thin-edge.io behind a proxy
  docs/src/install/index.md
  docs/src/start/getting-started.md
  tests/RobotFramework/tests/cumulocity/http_proxy/http_proxy_support.robot
Labels: documentation, theme:connectivity

#3600 fix: support HTTP proxy in c8y remote access plugin
  Cargo.lock
  Cargo.toml
  plugins/c8y_remote_access_plugin/Cargo.toml
  plugins/c8y_remote_access_plugin/src/lib.rs
  plugins/c8y_remote_access_plugin/src/proxy.rs
  tests/RobotFramework/tests/cumulocity/http_proxy/http_proxy_support.robot
Labels: theme:troubleshooting, theme:c8y, theme:connectivity

#3604 test: use new library keyword to get c8y domain
  tests/RobotFramework/requirements/requirements.txt
  tests/RobotFramework/tests/cumulocity/http_proxy/http_proxy_support.robot
  tests/RobotFramework/tests/cumulocity/registration/cumulocity_ca.robot
  tests/RobotFramework/tests/customizing/config_dir.robot
  tests/RobotFramework/tests/pkcs11/private_key_storage.robot
Labels: theme:testing

#3603 fix: ensure that `tedge mqtt pub` fully publishes messages sent with QoS 2
  crates/common/mqtt_channel/src/connection.rs
Labels: theme:mqtt, theme:cli

#3602 fix: pkcs11 signing with a wrong key and a ready check when `TedgeP11Client` is created
  crates/extensions/tedge-p11-server/src/client.rs
  crates/extensions/tedge-p11-server/src/pkcs11.rs
  crates/extensions/tedge-p11-server/src/server.rs
  crates/extensions/tedge-p11-server/src/service.rs
  crates/extensions/tedge-p11-server/src/signer.rs
Labels: theme:hsm

#3597 docs: Add `tedge-p11-server` reference and update `hsm-support.md`
  crates/common/tedge_config/src/tedge_toml/tedge_config.rs
  docs/src/references/hsm-support.md
  docs/src/references/tedge-p11-server.md
Labels: documentation, theme:hsm

#3590 docs: Cumulocity certificate authority documentation
  docs/src/operate/c8y/connect.md
  docs/src/operate/c8y/images/register-c8y-ca-register-1-device.png
  docs/src/operate/c8y/images/register-c8y-ca-register-2-form-details.png
  docs/src/operate/c8y/images/register-c8y-ca-register-3-form-complete.png
  docs/src/operate/c8y/images/register-c8y-ca-register-4-registration-list.png
  docs/src/references/certificate-management.md
Labels: documentation, theme:c8y, theme:certificates

#3609 patch version bump
  Cargo.lock
  Cargo.toml
Labels: skip-release-notes

#3611 docs: Fill in fallback values for sh command blocks
  docs/src/references/hsm-support.md
  docs/src/references/tedge-p11-server.md
  docs/src/references/tedge-write.md
Labels: documentation, theme:hsm

#3610 docs: fix broken document link
  docs/src/references/certificate-management.md
Labels: documentation, skip-release-notes

#3612 tests: Fix tedge-p11-server blocking test
  crates/extensions/tedge-p11-server/src/server.rs
Labels: theme:testing, skip-release-notes, theme:hsm

#3617 tests: enable Cumulocity certificate-authority system tests
  tests/RobotFramework/tests/cumulocity/registration/cumulocity_ca.robot
Labels: theme:c8y, theme:testing

#3619 fix: accept values starting with hypen in flags related to passwords
  crates/core/tedge/src/cli/certificate/cli.rs
Labels: theme:cli

#3615 refactor: Update tests to check for maximum message counts only when appropriate
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_command/custom_operation_command.robot
  tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_smartrest_template/smartrest_template.robot
  tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device_retry.robot
Labels: theme:testing

#3621 refactor: reinstate private key zeroisation
  Cargo.lock
  Cargo.toml
  crates/common/mqtt_channel/Cargo.toml
  crates/common/mqtt_channel/src/config.rs
Labels: refactoring

#3614 refactor: flush after calling write_all
  crates/common/certificate/src/parse_root_certificate/mod.rs
  crates/common/download/src/download.rs
  crates/common/tedge_config/src/system_toml/log_level.rs
  crates/common/tedge_config/src/system_toml/mod.rs
  crates/common/tedge_utils/src/file.rs
  crates/common/tedge_utils/src/paths.rs
  crates/common/upload/src/upload.rs
  crates/core/plugin_sm/src/plugin.rs
  crates/core/plugin_sm/tests/plugin.rs
  crates/core/tedge/src/bridge/common_mosquitto_config.rs
  crates/core/tedge/src/bridge/config.rs
  crates/core/tedge/src/cli/certificate/create.rs
  crates/core/tedge/tests/mqtt.rs
  crates/core/tedge_agent/src/state_repository/state.rs
  crates/extensions/tedge_log_manager/src/manager/log_utils.rs
  crates/extensions/tedge_uploader_ext/src/tests.rs
  crates/tests/tedge_test_utils/src/fs.rs
  plugins/c8y_remote_access_plugin/src/lib.rs
  plugins/c8y_remote_access_plugin/src/proxy.rs
Labels: refactoring

#3627 docs: fix screenshot branding logo
  docs/src/start/images/DevicesList.png
Labels: documentation

#3630 refactor: remove hardcoded temporary directory handling in LoggedCommand
  crates/core/plugin_sm/src/plugin.rs
  crates/core/plugin_sm/src/plugin_manager.rs
  crates/core/plugin_sm/tests/plugin.rs
  crates/core/tedge_api/src/workflow/log/command_log.rs
  crates/core/tedge_api/src/workflow/log/logged_command.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
Labels: refactoring

#3623 feat: Connect summary cryptoki show mode and key URI
  crates/common/tedge_config/src/tedge_toml/tedge_config.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/cli/log.rs
  tests/RobotFramework/tests/pkcs11/private_key_storage.robot
Labels: theme:hsm

#3634 style: upgrade robocop to 6.1.1 and remove robotidy
  tests/RobotFramework/pyproject.toml
  tests/RobotFramework/requirements/requirements.dev.txt
  tests/RobotFramework/resources/common.resource
  tests/RobotFramework/tasks.py
  tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
Labels: theme:developer-exp

#3636 docs: remove unreferenced images
  docs/src/images/installing_from_source_downloading_project.png
  docs/src/images/manual_installation-binaries_init.png
  docs/src/images/manual_installation-download_source_code.png
  docs/src/images/manual_installation-minimum_deb_packages.png
  docs/src/images/manual_installation-tedge_binary_dry_run.png
  docs/src/images/manual_installation-tedge_directories.png
  docs/src/operate/c8y/images/register-c8y-ca-register-4-registration-list.png
  docs/src/operate/c8y/images/software-install-4-done.png
Labels: documentation

#3638 docs: fix broken anchors in HSM / tedge-p11-server docs
  docs/src/references/hsm-support.md
  docs/src/references/tedge-p11-server.md
Labels: documentation, theme:hsm

#3635 refactor: Use one SigningKey struct
  crates/extensions/tedge-p11-server/src/pkcs11.rs
Labels: refactoring, theme:hsm

#3631 feat: PKCS11 support EC SECP384R1 and SECP521R1 keys
  crates/extensions/tedge-p11-server/src/pkcs11.rs
  tests/RobotFramework/tests/pkcs11/private_key_storage.robot
Labels: theme:security, theme:hsm

#3608 feat: new tedge command to collect diagnostic information `tedge diag collect`
  Cargo.lock
  Cargo.toml
  configuration/contrib/diag-plugins/01_tedge.sh
  configuration/contrib/diag-plugins/02_os.sh
  configuration/contrib/diag-plugins/03_mqtt.sh
  configuration/contrib/diag-plugins/04_workflow.sh
  configuration/contrib/diag-plugins/05_entities.sh
  configuration/contrib/diag-plugins/06_internal.sh
  configuration/contrib/diag-plugins/07_mosquitto.sh
  configuration/contrib/diag-plugins/template.sh.ignore
  configuration/package_manifests/nfpm.tedge.yaml
  crates/common/tedge_config/src/tedge_toml/models/path.rs
  crates/common/tedge_config/src/tedge_toml/tedge_config.rs
  crates/core/tedge/Cargo.toml
  crates/core/tedge/src/cli/diag/cli.rs
  crates/core/tedge/src/cli/diag/collect.rs
  crates/core/tedge/src/cli/diag/mod.rs
  crates/core/tedge/src/cli/log.rs
  crates/core/tedge/src/cli/mod.rs
  crates/tests/tedge_test_utils/src/fs.rs
  docs/src/references/diagnostic-plugin.md
  tests/RobotFramework/tests/tedge/diag/00_template.sh
  tests/RobotFramework/tests/tedge/diag/tedge_diac_collect.robot
Labels: theme:troubleshooting, theme:cli

#3647 docs: fix markdown typo in link
  docs/src/understand/faq.md
Labels: documentation, skip-release-notes

#3645 tools: Remove obsolete clippy disallowed rules
  clippy.toml
Labels: theme:developer-exp
