Repository thin-edge/thin-edge.io, pull requests merged in 2025-08, with the labels that each got.

#3752 test: wait for agent to be ready before restarting mapper
  tests/RobotFramework/tests/cumulocity/inventory/inventory_update_bootstrap.robot
Labels: theme:testing

#3750 docs: add info how to display custom fragments in Cumulocity Dev-Mgmt UI
  docs/src/operate/c8y/custom-fragments.md
Labels: documentation

#3753 patch version bump
  Cargo.lock
  Cargo.toml
Labels: skip-release-notes

#3751 refactor(pkcs11): `TedgeP11Service`
  crates/extensions/tedge-p11-server/src/lib.rs
  crates/extensions/tedge-p11-server/src/main.rs
  crates/extensions/tedge-p11-server/src/pkcs11/mod.rs
  crates/extensions/tedge-p11-server/src/proxy/client.rs
  crates/extensions/tedge-p11-server/src/proxy/connection.rs
  crates/extensions/tedge-p11-server/src/proxy/mod.rs
  crates/extensions/tedge-p11-server/src/proxy/server.rs
  crates/extensions/tedge-p11-server/src/service.rs
  crates/extensions/tedge-p11-server/src/signer.rs
Labels: theme:hsm

#3759 ci: workaround cargo-udeps failure
  .github/workflows/pull-request-checks.yml
Labels: ci/cd

#3755 feat: inventory.json support for child devices
  .taplo.toml
  crates/core/tedge_agent/src/agent.rs
  crates/core/tedge_agent/src/entity_manager/server.rs
  crates/core/tedge_agent/src/entity_manager/tests.rs
  crates/core/tedge_agent/src/lib.rs
  crates/core/tedge_agent/src/twin_manager/actor.rs
  crates/core/tedge_agent/src/twin_manager/builder.rs
  crates/core/tedge_agent/src/twin_manager/mod.rs
  crates/core/tedge_agent/src/twin_manager/tests.rs
  crates/core/tedge_api/src/mqtt_topics.rs
  crates/extensions/c8y_mapper_ext/src/actor.rs
  crates/extensions/c8y_mapper_ext/src/converter.rs
  crates/extensions/c8y_mapper_ext/src/inventory.rs
  docs/src/operate/c8y/custom-fragments.md
  docs/src/references/mappers/c8y-mapper.md
  tests/RobotFramework/tests/cumulocity/inventory/inventory_update.robot
  tests/RobotFramework/tests/cumulocity/inventory/inventory_update_child_device.robot
Labels: theme:telemetry

#3769 feat: include mosquitto configuration in diagnostic collection
  configuration/contrib/diag-plugins/07_mosquitto.sh
  tests/RobotFramework/tests/tedge/diag/predefined_plugins.robot
Labels: theme:troubleshooting

#3770 feat: log incoming and outgoing packets in built-in bridge
  crates/extensions/tedge_mqtt_bridge/src/lib.rs
  crates/extensions/tedge_mqtt_bridge/src/mqtt_logging.rs
Labels: theme:troubleshooting
