Repository thin-edge/thin-edge.io, pull requests merged in 2025-03, with the labels that each got.

#3440 refactor: Remove from C8yMapperActor the publish_messages receiver
  crates/extensions/c8y_mapper_ext/src/actor.rs
  crates/extensions/c8y_mapper_ext/src/availability/builder.rs
  crates/extensions/c8y_mapper_ext/src/availability/tests.rs
  crates/extensions/c8y_mapper_ext/src/tests.rs
Labels: refactoring

#3417 fix: make device profile `skip` field optional and skip operation fragment when it is set to `true`
  crates/core/c8y_api/src/json_c8y_deserializer.rs
  crates/core/tedge_api/src/device_profile.rs
  crates/extensions/c8y_mapper_ext/src/operations/handlers/device_profile.rs
  docs/src/references/agent/device-profiles.md
Labels: theme:profile

#3442 docs: use SmartREST 2.0 external id terminology instead of name
  docs/src/operate/c8y/smartrest-templates.md
Labels: documentation, theme:c8y

#3444 tests: Increase restart tedge-agent test timeout
  tests/RobotFramework/tests/tedge_agent/workflows/restart-tedge-agent.toml
Labels: theme:testing

#3443 test: add robot tests for cli tab completions
  crates/common/tedge_config_macros/impl/src/input/validate.rs
  crates/common/tedge_config_macros/impl/src/query.rs
  tests/RobotFramework/tests/tedge/tedge_completions.robot
Labels: theme:cli, theme:testing

#3441 fix: add device.csr_path to cloud profiles
  crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs
  crates/core/tedge/src/cli/certificate/cli.rs
  tests/RobotFramework/tests/tedge/certificate_signing_request.robot
Labels: theme:c8y, theme:aws, theme:az, theme:certificates

#3445 feat: add optional break conditions to `tedge mqtt sub`
  crates/core/tedge/src/cli/mqtt/cli.rs
  crates/core/tedge/src/cli/mqtt/subscribe.rs
  tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
  tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot
  tests/RobotFramework/tests/cumulocity/log/log_operation.robot
  tests/RobotFramework/tests/cumulocity/restart/restart_device.robot
  tests/RobotFramework/tests/cumulocity/software_management/software.robot
  tests/RobotFramework/tests/tedge/tedge_mqtt.robot
Labels: theme:mqtt, theme:cli

#3449 chore: update ring prompted by RUSTSEC-2025-0009
  Cargo.lock
Labels: dependencies, theme:security

#3450 dev: add task to add a git commit hook for adding the signoff option
  .github/pull_request_template.md
  CONTRIBUTING.md
  ci/dev/add-git-hook-prepare-commit.sh
  justfile
Labels: theme:developer-exp

#3453 dev: update commands in contributing guide
  .github/pull_request_template.md
  CODING_GUIDELINES.md
  justfile
Labels: theme:developer-exp

#3452 test: fix robotframework tests lint/format checks and ci checks
  justfile
  tests/RobotFramework/tasks.py
  tests/RobotFramework/tests/tedge/device_id/device_id_derivation.robot
  tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
Labels: ci/cd, theme:testing

#3458 chore: fix typo in gh workflow
  .github/workflows/build-workflow.yml
Labels: ci/cd, skip-release-notes

#3448 fix: don't panic when --duration has less than 1s value
  crates/core/tedge/src/cli/mqtt/cli.rs
  crates/core/tedge/src/cli/mqtt/mod.rs
  crates/core/tedge/src/cli/mqtt/publish.rs
  crates/core/tedge/src/cli/mqtt/subscribe.rs
Labels: theme:cli, skip-release-notes

#3451 ci: add cargo-deny check
  .devcontainer/Dockerfile
  .github/workflows/pull-request-checks.yml
  Cargo.lock
  Cargo.toml
  deny.toml
  justfile
Labels: ci/cd

#3463 ci: ignore unmaintained crate errors due to unnecessary project churn
  .github/workflows/pull-request-checks.yml
  justfile
Labels: ci/cd, skip-release-notes

#3457 refactor: don't show loading spinner if stdout isn't a terminal
  crates/core/tedge/src/cli/log.rs
Labels: theme:cli

#3462 fix: subscribe to topics on reconnection when session persistence is not enabled or broken
  crates/common/mqtt_channel/src/connection.rs
  tests/RobotFramework/tests/mqtt/session_persistence.robot
Labels: theme:mqtt

#3465 ci: ignore pip cache when installing cloudsmith-cli
  ci/admin/cloudsmith_admin.sh
  ci/build_scripts/publish_packages.sh
Labels: ci/cd, skip-release-notes

#3468 refactor: Fix clippy warnings
  crates/common/tedge_config_macros/src/multi.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/core/tedge/src/cli/connect/jwt_token.rs
  crates/core/tedge_agent/src/operation_workflows/persist.rs
  crates/core/tedge_api/src/workflow/state.rs
  plugins/c8y_remote_access_plugin/src/input.rs
Labels: refactoring

#3473 dev: replace deprecated rust language server (rls) with rust-analyzer
  .devcontainer/Dockerfile
  justfile
Labels: theme:developer-exp

#3477 fix: c8y-remote-access-plugin websocket connection
  plugins/c8y_remote_access_plugin/src/proxy.rs
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
  tests/RobotFramework/tasks.py
Labels: theme:troubleshooting, theme:c8y

#3483 docs: move common errors section to its own subheader
  docs/src/start/connect-c8y.md
Labels: documentation, theme:c8y

#3486 refactor: remove dead code
  Cargo.lock
  Cargo.toml
  crates/common/download/Cargo.toml
  crates/common/mqtt_channel/src/lib.rs
  crates/common/mqtt_channel/src/session.rs
  crates/common/mqtt_channel/src/tests.rs
  crates/common/tedge_config/Cargo.toml
  crates/core/c8y_api/Cargo.toml
  crates/core/tedge_agent/Cargo.toml
  crates/core/tedge_mapper/Cargo.toml
  crates/core/tedge_write/Cargo.toml
  crates/extensions/aws_mapper_ext/Cargo.toml
  crates/extensions/az_mapper_ext/Cargo.toml
  crates/extensions/c8y_firmware_manager/Cargo.toml
  crates/extensions/c8y_http_proxy/Cargo.toml
  crates/extensions/c8y_mapper_ext/Cargo.toml
  crates/extensions/tedge_config_manager/Cargo.toml
  crates/extensions/tedge_downloader_ext/Cargo.toml
  crates/extensions/tedge_health_ext/Cargo.toml
  crates/extensions/tedge_http_ext/Cargo.toml
  crates/extensions/tedge_log_manager/Cargo.toml
  crates/extensions/tedge_uploader_ext/Cargo.toml
  plugins/c8y_firmware_plugin/Cargo.toml
  plugins/c8y_remote_access_plugin/Cargo.toml
  plugins/tedge_apt_plugin/Cargo.toml
Labels: refactoring

#3480 test: add rust tests for c8y-remote-access-plugin
  Cargo.lock
  Cargo.toml
  crates/common/certificate/Cargo.toml
  crates/common/certificate/src/lib.rs
  crates/common/certificate/src/parse_root_certificate/pkcs11.rs
  crates/core/c8y_api/src/http_proxy.rs
  crates/core/tedge/src/cli/connect/jwt_token.rs
  plugins/c8y_remote_access_plugin/Cargo.toml
  plugins/c8y_remote_access_plugin/src/auth.rs
  plugins/c8y_remote_access_plugin/src/lib.rs
  plugins/c8y_remote_access_plugin/src/proxy.rs
Labels: theme:troubleshooting, theme:c8y, theme:testing

#3481 ci: remove blockers to build for android targets
  ci/build_scripts/package.sh
  mk/cargo.sh
  mk/install-build-tools.sh
Labels: ci/cd

#3490 tests: fix setup scope issues to improve log collection
  tests/RobotFramework/libraries/ThinEdgeIO/ThinEdgeIO.py
  tests/RobotFramework/tasks/E2E_Tutorials/Connect_to_c8y.robot
  tests/RobotFramework/tests/MQTT_health_check/MQTT_health_endpoints.robot
  tests/RobotFramework/tests/MQTT_health_check/health_tedge-agent.robot
  tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-aws.robot
  tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-az.robot
  tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-collectd.robot
  tests/RobotFramework/tests/MQTT_health_check/health_tedge_mapper_c8y.robot
  tests/RobotFramework/tests/aws/aws_telemetry.robot
  tests/RobotFramework/tests/azure/azure_telemetry.robot
  tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
  tests/RobotFramework/tests/cumulocity/configuration/configuration_operation_multi_cloud.robot
  tests/RobotFramework/tests/cumulocity/telemetry/c8y_child_alarms_rpi.robot
  tests/RobotFramework/tests/customizing/config_dir.robot
  tests/RobotFramework/tests/customizing/data_path_config.robot
  tests/RobotFramework/tests/customizing/log_path_config.robot
  tests/RobotFramework/tests/customizing/tedge_init.robot
  tests/RobotFramework/tests/mqtt/custom_sub_topics_tedge-mapper-aws.robot
  tests/RobotFramework/tests/mqtt/custom_sub_topics_tedge-mapper-az.robot
  tests/RobotFramework/tests/mqtt/custom_sub_topics_tedge-mapper-c8y.robot
  tests/RobotFramework/tests/mqtt/disconnect_from_broker.robot
  tests/RobotFramework/tests/mqtt/remote_mqtt_broker.robot
  tests/RobotFramework/tests/plugin_apt/filter_packages_list_output.robot
  tests/RobotFramework/tests/plugin_apt/improve_tedge_apt_plugin_error_messages.robot
  tests/RobotFramework/tests/tedge/call_tedge.robot
  tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
  tests/RobotFramework/tests/tedge/device_id/device_id_usecases.robot
  tests/RobotFramework/tests/tedge/http_file_transfer_api.robot
  tests/RobotFramework/tests/tedge/tedge_cert_create.robot
  tests/RobotFramework/tests/tedge/tedge_completions.robot
  tests/RobotFramework/tests/tedge/tedge_config_add_remove.robot
  tests/RobotFramework/tests/tedge/tedge_config_get.robot
  tests/RobotFramework/tests/tedge/tedge_mqtt.robot
  tests/RobotFramework/tests/tedge_agent/tedge_agent.robot
  tests/RobotFramework/tests/tedge_agent/workflows/run_workflow_on_child_device.robot
  tests/RobotFramework/tests/tedge_connect/tedge_connect_offline.robot
  tests/RobotFramework/tests/tedge_connect/tedge_connect_profile_validation.robot
  tests/RobotFramework/tests/tedge_connect/tedge_connect_test.robot
  tests/RobotFramework/tests/tedge_to_te_converter/convert_tedge_topics_to_te_topics.robot
  tests/RobotFramework/tests/tedge_watchdog/tedge_watchdog.robot
  tests/RobotFramework/tests/tedge_write.robot
Labels: theme:testing

#3493 tests: replace mosquitto_sub with tedge mqtt sub
  tests/RobotFramework/tests/tedge_agent/tedge_agent.robot
  tests/RobotFramework/tests/tedge_to_te_converter/convert_tedge_topics_to_te_topics.robot
Labels: theme:testing

#3496 test: add robocop lint exception for the large JSON payloads
  tests/RobotFramework/tests/tedge_agent/device_profile/device_profile_operation.robot
Labels: theme:testing

#3495 test: remove unmaintained tests
  tests/RobotFramework/requirements/requirements.browser.txt
  tests/RobotFramework/tasks/E2E_Tutorials/Connect_to_c8y.robot
  tests/RobotFramework/tasks/build_install_rpi.robot
  tests/RobotFramework/tasks/debug.robot
Labels: refactoring, theme:testing

#3497 feat: allow environment variables to be reset by setting them to the empty string
  crates/common/tedge_config/src/tedge_toml/figment.rs
Labels: theme:configuration

#3494 feat: support retained-only flag in tedge mqtt sub
  crates/core/tedge/src/cli/mqtt/cli.rs
  crates/core/tedge/src/cli/mqtt/subscribe.rs
  tests/RobotFramework/tests/tedge/tedge_mqtt.robot
Labels: theme:mqtt, theme:cli

#3421 feat: cryptoki via UNIX socket
  Cargo.lock
  Cargo.toml
  crates/common/certificate/Cargo.toml
  crates/common/certificate/src/parse_root_certificate/mod.rs
  crates/common/tedge_config/Cargo.toml
  crates/common/tedge_config/src/tedge_toml/models/cryptoki.rs
  crates/common/tedge_config/src/tedge_toml/models/mod.rs
  crates/common/tedge_config/src/tedge_toml/tedge_config.rs
  crates/common/tedge_config/src/tedge_toml/tedge_config/append_remove.rs
  crates/common/tedge_config/src/tedge_toml/tedge_config/mqtt_config.rs
  crates/core/tedge/src/cli/connect/command.rs
  crates/extensions/tedge-p11-server/Cargo.toml
  crates/extensions/tedge-p11-server/README.md
  crates/extensions/tedge-p11-server/src/client.rs
  crates/extensions/tedge-p11-server/src/connection.rs
  crates/extensions/tedge-p11-server/src/lib.rs
  crates/extensions/tedge-p11-server/src/main.rs
  crates/extensions/tedge-p11-server/src/pkcs11.rs
  crates/extensions/tedge-p11-server/src/server.rs
  crates/extensions/tedge-p11-server/src/service.rs
  crates/extensions/tedge-p11-server/src/signer.rs
  crates/extensions/tedge-p11-server/src/single_cert_and_key.rs
Labels: theme:security

#3500 chore: Add missing `format!` and resolve trivial clippy 1.87 lints
  crates/common/tedge_config_macros/impl/src/input/parse.rs
  crates/common/tedge_config_macros/impl/src/input/validate.rs
  crates/core/c8y_api/src/smartrest/smartrest_deserializer.rs
  crates/core/plugin_sm/src/plugin_manager.rs
  crates/core/tedge_actors/src/runtime.rs
  crates/core/tedge_api/src/workflow/log/logged_command.rs
  crates/extensions/tedge_script_ext/src/lib.rs
  plugins/c8y_remote_access_plugin/src/lib.rs
Labels: refactoring

#3502 fix: use both mqtt and http address when validating connecting c8y tenant url
  crates/core/tedge/src/cli/connect/command.rs
Labels: theme:c8y

#3509 ci: support filtering the list of packages to publish
  ci/build_scripts/publish_packages.sh
Labels: ci/cd

#3507 ci: allow projects to control where the packages are published to using secrets
  .github/workflows/build-workflow.yml
Labels: ci/cd

#3508 ci: build script fixes for various targets
  ci/build_scripts/publish_packages.sh
  mk/cargo.sh
  mk/install-build-tools.sh
Labels: ci/cd

#3510 ci: parameterize the tarball contents
  ci/build_scripts/package.sh
Labels: ci/cd

#3520 docs: use bi-directional arrow as right-to-left arrows cause a rendering issue in mermaid js
  docs/src/references/agent/index.md
Labels: documentation

#3521 tests: fix flaky default_plugin_config tests
  crates/extensions/tedge_config_manager/src/lib.rs
  crates/extensions/tedge_log_manager/src/lib.rs
Labels: theme:testing

#3505 fix: skip bridge status messages in aws/az mappers
  crates/extensions/aws_mapper_ext/src/converter.rs
  crates/extensions/az_mapper_ext/src/converter.rs
Labels: theme:aws, theme:az
